### ISSUE TITLE
chaosblade-box-agent编译报错

### ISSUE THREAD

**Issue by tytyty123** [chaosblade-io/chaosblade#1000]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
拉取chaosblade-box-agent仓库代码，使用master分支进行启动
编译时报错，报错截图如下
![image](https://github.com/chaosblade-io/chaosblade/assets/30776468/d4c82251-4797-48a3-931b-9a37839262cf)

### Describe what you expected to happen
编译成功

### How to reproduce it (as minimally and precisely as possible)

1. 进入项目目录，执行make build_arm64
2. 
3. 

### Tell us your environment
系统版本
Linux version 4.19.0-arm64-desktop (uosserver@uosserver-PC) (gcc version 8.3.0 (Uos 8.3.0.3-3+rebuild))

go版本
go version go1.19.13 linux/arm64

**Comment by MandssS** [comment]
It looks like you might have an old version of Go installed. 1.17 is required to have embed.
