### ISSUE TITLE
1.7.3版本里面blade server的命令是删除了吗

### ISSUE THREAD

**Issue by Xiaomajohn** [chaosblade-io/chaosblade#1007]
使用-h帮助命令和直接输入命令，都无法使用

**Comment by Xiaomajohn** [comment]
![Uploading 屏幕截图 2024-03-07 100007.png…]()

**Comment by boxker** [comment]
我也遇到了这个问题：

![image](https://github.com/chaosblade-io/chaosblade/assets/21237647/39f9f1b8-e99b-42b9-afd6-d3c9987dc376)

**Comment by DavidLiuXh** [comment]
@Xiaomajohn @boxker 这个问题后来解决了吗？

**Comment by MandssS** [comment]
Since the server model directly exposes services on the user's machine, there are security risks, so this usage method has been removed.
