### ISSUE TITLE
请问对于1.7.3版本的blade，使用yaml形式对内存进行限制参数如何设置呢？

### ISSUE THREAD

**Issue by Lovely-red-scarf** [chaosblade-io/chaosblade#1031]
k8s版本1.2.8，chaosblade:1.7.3

想要通过yaml的形式对pod的内存进行限制，但是官网没有给出具体的 参数，如何设置呢？
![image](https://github.com/chaosblade-io/chaosblade/assets/41297612/0be489c8-450f-42eb-a029-6ec3f2a3421d)

**Comment by xcaspar** [comment]
The minimum k8s version supported by chaosblade is 1.16.
