### ISSUE TITLE
ghcr.io/chaosblade-io/chaosblade-build-musl:latest  can not be downloaded

### ISSUE THREAD

**Issue by xavierW** [chaosblade-io/chaosblade#1033]
## Issue Description

Type: *bug report* , *feature request* or *question*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
We will update to the new address this week.

**Comment by xavierW** [comment]
邮件已收到，我会尽快阅读并回复，谢谢

**Comment by MandssS** [comment]
have pushed, you can try again.
