### ISSUE TITLE
failed to execute command: ./blade create k8s node-disk burn

### ISSUE THREAD

**Issue by keerde** [chaosblade-io/chaosblade#1047]
## Issue Description
The following problem was encountered while injecting node disk IO. How can I solve it

command: ./blade create k8s node-disk burn --names 194.168.0.2 --read --write
result:{"code":63061,"success":false,"error":"`getClient`: k8s exec failed, err: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined"}

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
This is an error when invoking K8s API. Please append the  `--kubeconfig`  parameter to ensure that it can be called normally.
