### ISSUE TITLE
The feature of throwCustomException in JDK21 can be attached, but it doesn't work.

### ISSUE THREAD

**Issue by niko-liu** [chaosblade-io/chaosblade#1053]
如题

**Comment by xcaspar** [comment]
The [JVM-SANBOX ](https://github.com/alibaba/jvm-sandbox/tree/develop-for-20230129) project has not yet officially released support for JDK21, but it has been developed on the https://github.com/alibaba/jvm-sandbox/tree/develop-for-20230129 branch. We will test it based on this branch and expect to release the feature at the end of August.
