### ISSUE TITLE
The flag `--process` in `blade p jvm` command means what

### ISSUE THREAD

**Issue by alisanguo** [chaosblade-io/chaosblade#11]
Type: feature request

the command "blade p jvm --process application name", the application name means what? the PID of java application?

**Comment by xcaspar** [comment]
> Type: feature request
> 
> the command "blade p jvm --process application name", the application name means what? the PID of java application?

keyword of the application process name, for example, the process command line:
`/opt/taobao/java/bin/java -Dproject.name=monkeyking-demo -classpath /home/admin/monkeyking-demo/target/monkeyking-demo  com.taobao.pandora.boot.loader.SarLauncher`

the `--process` value can be `monkeyking-demo` or `project.name` keywords

**Comment by alisanguo** [comment]
if the application is a springboot application ， I run it with "java -jar test.jar",  the --process value can be what？It means that I must run it with "-Dproject.name" property?
thanks~

**Comment by aspnetdb** [comment]
> if the application is a springboot application ， I run it with "java -jar test.jar", the --process value can be what？It means that I must run it with "-Dproject.name" property?
> thanks~

>  "--process xxx" effect to  "ps -ef | grep 'xxx'". In your case, "xxx" can be "test.jar"

**Comment by xcaspar** [comment]
> if the application is a springboot application ， I run it with "java -jar test.jar", the --process value can be what？It means that I must run it with "-Dproject.name" property?
> thanks~

test.jar

**Comment by xcaspar** [comment]
> > if the application is a springboot application ， I run it with "java -jar test.jar", the --process value can be what？It means that I must run it with "-Dproject.name" property?
> > thanks~
> 
> test.jar

@alisanguo Did this answer solve your problem?

**Comment by Hyseen** [comment]
> if the application is a springboot application ， I run it with "java -jar test.jar", the --process value can be what？It means that I must run it with "-Dproject.name" property?
> thanks~

The `jps` command will show the java process name

**Comment by xcaspar** [comment]
> if the application is a springboot application ， I run it with "java -jar test.jar", the --process value can be what？It means that I must run it with "-Dproject.name" property?
> thanks~

I will close the issue, if you still have questions, please open it or submit a new issue.
