### ISSUE TITLE
Does the dd command in the mac system not support the inflag attribute? There will be problems when simulating the disk fill scene

### ISSUE THREAD

**Issue by boomblog** [chaosblade-io/chaosblade#111]
我在mac上执行下面命令会报错：
blade create disk fill -d --mount-point /home --size 1024
错误为：
{"code":604,"success":false,"error":"dd: unknown operand iflag\n exit status 1 exit status 1"}

看了一下上面的讨论，我直接执行下面的命令也会报错
命令为：
dd if=/dev/zero of=/home/chaos_filldisk.log.dat bs=1b count=1 iflag=fullblock
错误为：
dd: unknown operand iflag

**Comment by xcaspar** [comment]
@boomblog 目前磁盘实验没有兼容 mac，你可以在 linux 上执行，我将此 issue 置为待开发项。

**Comment by xcaspar** [comment]
Don't consider implementing mac disk scenarios.
