### ISSUE TITLE
how to apply it in K8s

### ISSUE THREAD

**Issue by iwtbs** [chaosblade-io/chaosblade#115]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by iwtbs** [comment]
I make a project named train-ticket using k8s+istio, I want to add some error to make testbed, how can I use this tool to get that?

**Comment by xcaspar** [comment]
> I make a project named train-ticket using k8s+istio, I want to add some error to make testbed, how can I use this tool to get that?

If you use the tool outside the pod, you can execute delete pod experiment. You can add the tool to the target container image for executing more experiments.
