### ISSUE TITLE
docker disk fill and burn can not work

### ISSUE THREAD

**Issue by HiJasper** [chaosblade-io/chaosblade#119]
## Issue Description

bug report

### Describe what happened (or what feature you want)
The command
"./blade create docker disk fill --size 100 --timeout 10 --container d94bd2a75568"
return
"{"code":502,"success":false,"error":"not support the action command for fill"}"

Did this command also need create a container from image chaosblade_agent?
I‘m a little confused about the usage of this command

### Tell us your environment
chaosblade: 0.1.0
Docker: 1.12.6
CentOS Linux release 7.3.1611

**Comment by xcaspar** [comment]
@HiJasper  Currently not support fill disk or burn io by executing experiment outside of container, you can add the chaosblade tool into the container and execute it.

**Comment by HiJasper** [comment]
> @HiJasper Currently not support fill disk or burn io by executing experiment outside of container, you can add the chaosblade tool into the container and execute it.

Thanks
