### ISSUE TITLE
execute a docker experiment，return Error: No such container

### ISSUE THREAD

**Issue by ray110** [chaosblade-io/chaosblade#12]
### execute a docker experiment
command: `blade  create docker cpu fullload --container containerID` 
return:
> {"code":604,"success":false,"error":"Error:` No such container: 8e8c31d91a2c-cpu\n exit status 1"}

Do i need enter the container and run the command ?

**Comment by xcaspar** [comment]
> blade create docker cpu fullload --container containerID

No need. The execution process of the cpu full load for docker as flows:

Pull docker image `registry.cn-hangzhou.aliyuncs.com/chaosblade/chaosblade-agent:0.0.1` and execute run command like: `docker run -d -t --pid container:<CONTAINERID> --ipc container:<CONTAINERID> --name <CONTAINERID>-cpu sh -c /usr/local/chaosblade/bin/chaos_burncpu --start`

For your problem, please check if you can pull the `registry.cn-hangzhou.aliyuncs.com/chaosblade/chaosblade-agent:0.0.1` image or not.

**Comment by ray110** [comment]
> > blade create docker cpu fullload --container containerID
> 
> No need. The execution process of the cpu full load for docker as flows:
> 
> Pull docker image `registry.cn-hangzhou.aliyuncs.com/chaosblade/chaosblade-agent:0.0.1` and execute run command like: `docker run -d -t --pid container:<CONTAINERID> --ipc container:<CONTAINERID> --name <CONTAINERID>-cpu sh -c /usr/local/chaosblade/bin/chaos_burncpu --start`
> 
> For your problem, please check if you can pull the `registry.cn-hangzhou.aliyuncs.com/chaosblade/chaosblade-agent:0.0.1` image or not.

thx
