### ISSUE TITLE
Chaosblade execution results output to stderror

### ISSUE THREAD

**Issue by konglz** [chaosblade-io/chaosblade#123]
## Issue Description

Type: *bug report*

### Describe what happened

* 执行``./blade version  | grep xxx``时，grep过滤不生效，因为grep只能过滤stdout;

* 执行``./blade version 2>&1 | grep xxx``时，grep过滤生效。

> 因此判断执行结果输出到了stderr

### Describe what you expected to happen

* chaosblade执行结果输出到stdout

### Tell us your environment

* centos 7.4

**Comment by xcaspar** [comment]
@konglz You can download new chaosblade version to solve the issue. Download address: https://github.com/chaosblade-io/chaosblade/releases
