### ISSUE TITLE
error when Compile

### ISSUE THREAD

**Issue by iwtbs** [chaosblade-io/chaosblade#124]
Hello, I use command：【go get github.com/chaosblade-io/chaosblade】 and successfully  downloaded the project to the GOPATH/src/github.com/chaosblade-io/chaosblade directory, but when I use command 【make】，error happend like this:

Makefile:61: recipe for target 'build_burncpu' failed
make: *** [build_burncpu] Error 1

and what should I do?

**Comment by xcaspar** [comment]
@iwtbs Please provide the `go env` output and the absolute path of chaosblade dir.

**Comment by xcaspar** [comment]
@iwtbs 
Please check the $GOPATH value is `/home/aiops/go` or not

**Comment by iwtbs** [comment]
I‘m sure the GOPATH is "/home/aiops/go".
I think maybe the problem is  when I use the commit: "go get github.com/chaosblade-io/chaosblade" and the response is "can't load package: package github.com/chaosblade-io/chaosblade: no buildable Go source files in /home/aiops/go/src/github.com/chaosblade-io/chaosblade"
How can i solve it?

**Comment by xcaspar** [comment]
@iwtbs What's your os version?
