### ISSUE TITLE
dial tcp 127.0.0.1:49994: connect: connection refused

### ISSUE THREAD

**Issue by wanglinan133** [chaosblade-io/chaosblade#126]
## Issue Description
the blade resoult is "{"code":802,"success":false,"error":"Get http://127.0.0.1:49994/sandbox/default/module/http/sandbox-module-mgr/active?1=1\u0026ids=chaosblade: dial tcp 127.0.0.1:49994: connect: connection refused","result":"61d2548933a98a72"}"
when i excute conmmond ./blade prepare jvm --process tomcat

### Describe what you expected to happen
return massage of success:true 

### How to reproduce it (as minimally and precisely as possible)
first: start a service with tomcat 7 and add attribute -DProject.name="tomcat"
second : excute commond ./blade prepare jvm --process tomcat
third : the issuse reproduced

### Tell us your environment
os:CentOS release 6.4 (Final
javaversion 1.8
tomcat 7
chaosblade 0.1.0

**Comment by wanglinan133** [comment]
i think sandbox services is not running

**Comment by xcaspar** [comment]
@wanglinan133 Have you executed sandbox.sh alone or deleted the chaosblade directory?
There are two ways to recover:
1. execute sandbox.sh -p PID -S and re-execute the prepare command
2. restart the application and re-execute the prepare command

**Comment by xcaspar** [comment]
@wanglinan133 You can download new chaosblade version from [releases](https://github.com/chaosblade-io/chaosblade/releases) to solve the problem.

**Comment by wanglinan133** [comment]
I have executed the command according to your comment ,step by step
Finally,this problem is resolved

**Comment by wanglinan133** [comment]
Thanks，adviser ! this issue can be closed
