### ISSUE TITLE
cannot get port from local

### ISSUE THREAD

**Issue by cyxroot** [chaosblade-io/chaosblade#128]
when execute "./blade create dubbo delay --time 3000 --service com.alibaba.demo.HelloService --methodname hello --consumer --process dubbo.consumer"
then return :{"code":500,"success":false,"error":"cannot get port from local"}
![image](https://user-images.githubusercontent.com/4468730/61698025-fe886100-ad6a-11e9-8066-1cdde6f6fec7.png)

**Comment by xcaspar** [comment]
@cyxroot Please execute `prepare` command firstly. see WIKI for details

**Comment by xcaspar** [comment]
The issue has been solved in the chaosblade 0.2.0 version, you can download from [releases](https://github.com/chaosblade-io/chaosblade/releases)

**Comment by cyxroot** [comment]
> @cyxroot Please execute `prepare` command firstly. see WIKI for details

I had execute prepare command firstly.
I checked the example had an error
"./blade create dubbo delay --time 3000 --service com.alibaba.demo.HelloService --methodname hello --consumer --process **dubbo.consumer**"
"dubbo.consumer" should be "dubbo-consumer"
and then succees
