### ISSUE TITLE
Hope chaosblade could support to be invoked by API 

### ISSUE THREAD

**Issue by ivantian** [chaosblade-io/chaosblade#13]
Until now, it could be only used by Blade CLI, but if chaosblade could provide the  invoke ways of API,  it should be more popular in the future.

**Comment by xcaspar** [comment]
@ivantian To implement this feature, blade must be started as a daemon and expose the service by HTTP protocol.

I think this feature will be implemented in 0.0.6 milestones, unless someone is willing to implement it.

**Comment by aspnetdb** [comment]
API is not only the Web API. Well design output can also be good APIs. There are some good ideas we can learn from the following article. Two key part
1. Human-readable output vs machine-readable output.  Machine-readable output is the basis of the top development.
2. json-parseable.  `--json` can also be a common flag.

article url:
https://devcenter.heroku.com/articles/cli-style-guide#human-readable-output-vs-machine-readable-output

**Comment by xcaspar** [comment]
#68
