### ISSUE TITLE
Fail to destroy "network delay'

### ISSUE THREAD

**Issue by Oliver-zou** [chaosblade-io/chaosblade#131]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
I run ./blade create network delay --interface ens33 --time 3000. It's work. Then I destroy this uid. It shows successful but the delay effect still exists and I can create this network delay again. It shows '604 false, file exists\n exit status 2 exit status 1'

### Describe what you expected to happen
When I destroy the network delay, its effect also disappear, and I can create again.

### How to reproduce it (as minimally and precisely as possible)

1. ./blade create network delay --interface ?--time 3000
2.  ./blade destroy Uid(from step 1)
3.  ping some web, the network delay still exists.
4.  ./blade create network delay --interface ?--time 3000    . It shows failure.

### Tell us your environment
Ubuntu 16.04

### Anything else we need to know?
How to use network dns experiment?

**Comment by Oliver-zou** [comment]
Emm... I got it.  If use 'sudo' to destroy Uid, it will work.    I am very interested in this tool, please answer a question：How to use network dns experiment?  Would you make a demo or example to show that?

**Comment by xcaspar** [comment]
@Oliver-zou Thank you for your interest in this tool. The purpose of the dns experiment is to implement the case where the domain name cannot be accessed. For example, if you visit www.baidu.com, the experiment will be performed:
`blade create network dns --domain www.baidu.com --ip 0.0.0.1`

**Comment by Oliver-zou** [comment]
Thanks for your reply. Maybe I will ask some more questions about chaosblade in the future:-). The information about chaos engineering is really too little. By the way, if I can contribute code, it would be better.
