### ISSUE TITLE
confused with param --servletpath --pathinfo with command create servlet delay 

### ISSUE THREAD

**Issue by bryanYao** [chaosblade-io/chaosblade#134]
my code is
@RequestMapping(value = "/bags/pid", method = RequestMethod.GET)
@ResponseBody
 public String getPids(){
 //other code
}
and visit url is http://localhost:8080/bags/pid
but it don't work when I use command
 'blade create servlet delay  --method GET --time=5000 --servletpath=/bags --pathinfo=/pid'
although it shows {"code":200,"success":true,"result":"a388248ff7b57dbe"}

but it works I change command like  'blade create servlet delay  --method GET --time=5000 --servletpath=/bags/pid --method GET'

so I hope use only parameter like  url or path  to instead servletpath and pathinfo

**Comment by xcaspar** [comment]
@bryanYao I agree it. I will modify it in the next version. Thanks.

**Comment by xcaspar** [comment]
@bryanYao Can I assign the issue to you?

**Comment by xcaspar** [comment]
See https://github.com/chaosblade-io/chaosblade-exec-jvm/pull/63 for the detail.
