### ISSUE TITLE
Ask a question:-)

### ISSUE THREAD

**Issue by Oliver-zou** [chaosblade-io/chaosblade#139]
## Issue Description

Type:
### Describe what happened (or what feature you want)
./blade create network drop +port . This means drop data for some port？After successful execution, how to check the effect?  
And, one more question : How to  achieve these chaos experiments for network？Based on  some linux tool like Traffic Control?
Thanks.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
./blade create network drop +port . This means drop data for some port？After successful execution, how to check the effect?
-----
You can use telnet command to test.

And, one more question : How to achieve these chaos experiments for network？Based on some linux tool like Traffic Control?
-----
Yes.

**Comment by Oliver-zou** [comment]
Got it~ Thanks.
