### ISSUE TITLE
disk fill implement discuss

### ISSUE THREAD

**Issue by sequarius** [chaosblade-io/chaosblade#143]
### Issue Description
disk fill make a `dd` system program call eternally. howerver, it may cause io busy and disk free space increase slowly if the fill size is large enough after the experiment exectute. Sometimes, problem is happened by io busy, not space limited. how about use `fallocate` instead `dd`?

Type:  *feature request*

### Tell us your environment
CentOS 7.2

### Anything else we need to know?
[fallocate](http://manpages.ubuntu.com/manpages/bionic/man1/fallocate.1.html)

**Comment by xcaspar** [comment]
@sequarius It's a good idea 👍, can you commit a pr to replace it?

**Comment by sequarius** [comment]
@xcaspar Of course, I will create a pull request when all test are pass
