### ISSUE TITLE
mac build failed

### ISSUE THREAD

**Issue by kounijiwa** [chaosblade-io/chaosblade#15]
Use 'make build_linux'  on mac, occued error.
error meassage :
docker run --rm \
		-v :/go \
		-w /go/src/github.com/chaosblade-io/chaosblade \
		chaosblade-build-musl:latest
make: *** No targets specified and no makefile found.  Stop.
make: *** [build_linux] Error 2

I have to install go env?

**Comment by kounijiwa** [comment]
MACOS  MOJAVE 10.14.2
chaosblade  v0.0.1
 cannot execute binary file

**Comment by xcaspar** [comment]
> Use 'make build_linux' on mac, occued error.
> error meassage :
> docker run --rm 
> -v :/go 
> -w /go/src/github.com/chaosblade-io/chaosblade 
> chaosblade-build-musl:latest
> make: *** No targets specified and no makefile found. Stop.
> make: *** [build_linux] Error 2
> 
> I have to install go env?

Not necessary. Did you compile the project or the release package?
The release package does not need to compile.

**Comment by kounijiwa** [comment]
First, I clone the code, make build_linux  on mac, occured error. 
error message:error meassage :
docker run --rm
-v :/go
-w /go/src/github.com/chaosblade-io/chaosblade
chaosblade-build-musl:latest
make: *** No targets specified and no makefile found. Stop.
make: *** [build_linux] Error 2

Then ,I download  0.0.1 release package,  run ./blade , " cannot execute binary file"

env:
MACOS MOJAVE 10.14.2
chaosblade v0.0.1

**Comment by mingcheng** [comment]
> First, I clone the code, make build_linux on mac, occured error.
> error message:error meassage :
> docker run --rm
> -v :/go
> -w /go/src/github.com/chaosblade-io/chaosblade
> chaosblade-build-musl:latest
> make: *** No targets specified and no makefile found. Stop.
> make: *** [build_linux] Error 2
> 
> Then ,I download 0.0.1 release package, run ./blade , " cannot execute binary file"
> 
> env:
> MACOS MOJAVE 10.14.2
> chaosblade v0.0.1

Just try my PR for build on MacOS, type `make docker_image` to build.

**Comment by xcaspar** [comment]
@kounijiwa please retry the master branch. I have merge the above PR #16  @mingcheng submitted.

**Comment by xcaspar** [comment]
@kounijiwa I will close the issue, please reopen it if your problem has not been solved.
