### ISSUE TITLE
Blade c jvm script will be repeated multiple times

### ISSUE THREAD

**Issue by auyang-0626** [chaosblade-io/chaosblade#150]
### 
通过blade 执行下面的命令多次，第一次成功，之后就报错，看起来没有任何问题。
![image](https://user-images.githubusercontent.com/22674253/62283449-291d9c80-b484-11e9-97ea-09d8d402d342.png)
但是观察到脚本被调用了多次，如下图
![image](https://user-images.githubusercontent.com/22674253/62283598-7732a000-b484-11e9-985b-be61e125b0df.png)
通过阅读源代码发现，每次执行命令，都会走到com.alibaba.chaosblade.exec.bootstrap.jvmsandbox.SandboxModule#add，然后调用sandbox的watch方法添加一个listener。这步完成之后，才会走到判断重复的逻辑，返回错误信息，但是实际上已经再次通过sandbox增强了指定类。
![image](https://user-images.githubusercontent.com/22674253/62284489-47849780-b486-11e9-9083-2dab143e3455.png)
![image](https://user-images.githubusercontent.com/22674253/62284523-579c7700-b486-11e9-9d38-0c689a448341.png)

所以判断重复的操作应该提前进行！

**Comment by xcaspar** [comment]
@auyang-0626 Thanks for reporting the bug. Can you fix it?

**Comment by No-sleeping** [comment]
> ## bug report
> ### ./blade c jvm script 会重复挂载多次watch，导致script-file执行多次
> 通过blade 执行下面的命令多次，第一次成功，之后就报错，看起来没有任何问题。
> ![image](https://user-images.githubusercontent.com/22674253/62283449-291d9c80-b484-11e9-97ea-09d8d402d342.png)
> 但是观察到脚本被调用了多次，如下图
> ![image](https://user-images.githubusercontent.com/22674253/62283598-7732a000-b484-11e9-985b-be61e125b0df.png)
> 通过阅读源代码发现，每次执行命令，都会走到com.alibaba.chaosblade.exec.bootstrap.jvmsandbox.SandboxModule#add，然后调用sandbox的watch方法添加一个listener。这步完成之后，才会走到判断重复的逻辑，返回错误信息，但是实际上已经再次通过sandbox增强了指定类。
> ![image](https://user-images.githubusercontent.com/22674253/62284489-47849780-b486-11e9-9083-2dab143e3455.png)
> ![image](https://user-images.githubusercontent.com/22674253/62284523-579c7700-b486-11e9-9d38-0c689a448341.png)
> 
> 所以判断重复的操作应该提前进行！

麻烦问一下，这里注入的脚本是一定要和目标项目打包在一起么？
或者有没有可能麻烦宁发一下您注入脚本的demo呢。
