### ISSUE TITLE
./sudo blade create cpu fullload but destroy it without root authority

### ISSUE THREAD

**Issue by yixy** [chaosblade-io/chaosblade#152]
## Issue Description

Type: *bug report*

### Describe what happened 

when I create a cpu fullload experiment with root authority, and destroy it without root authority, blade returns success, but actually the pid is not killed and cpu is still fullload.

### How to reproduce it (as minimally and precisely as possible)

```
$ sudo ./blade create cpu fullload --cpu-list=0-1
{"code":200,"success":true,"result":"7c4993627b857336"}

$ ps -e |grep chaos_burncpu
 7889 pts/0    00:03:58 chaos_burncpu
 7911 pts/0    00:03:57 chaos_burncpu

$ ./blade destroy 7c4993627b857336
{"code":200,"success":true,"result":"command: cpu fullload --cpu-list 0-1 --debug false --help false"}

$ ps -e |grep chaos_burncpu
 7889 pts/0    00:06:57 chaos_burncpu
 7911 pts/0    00:06:53 chaos_burncpu
```

### Tell us your environment

```
$ uname -a
Linux ubuntu-desktop 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
```

### Anything else we need to know?

I have fixed the burncpu.go file by myself, could I make a PR?

**Comment by xcaspar** [comment]
@yixy Yes, you can. Thanks for reporting and fixing it.
