### ISSUE TITLE
params parse error

### ISSUE THREAD

**Issue by auyang-0626** [chaosblade-io/chaosblade#160]
### Describe what happened (or what feature you want)
When I execute the following command，--exception no assignment，In theory, it should report an error, but the execution is successful.

```
./blade create servlet throwCustomException --exception  --servletpath /app/list.json
### Describe what you expected to happen
```
And then, all requests will be given an error.
![image](https://user-images.githubusercontent.com/22674253/62762678-3eb24800-babc-11e9-86db-8a5397e77290.png)

I think it is a parameter parsing error.This is very dangerous in the production environment.
![image](https://user-images.githubusercontent.com/22674253/62762780-7d480280-babc-11e9-8770-ebd27ed9f33a.png)

**Comment by bryanYao** [comment]
--exception string           Exception class inherit java.lang.Exception (required)

you should give the exception name you expented, like Exception,
so you can change your command like this:
./blade create servlet throwCustomException --exception Exception  --servletpath /app/list.json

**Comment by auyang-0626** [comment]
I mean --exception is followed by no arguments and can be created successfully.
But it will match all HTTP requests and will throw an exception (the specified exception class could not be found and then throw a runtimeException).
However, I just want to make an interface throw an exception, without parameters, should tell me that the command created is not legal.

我的意思是--exception后面不加参数，也可以创建成功。但是它会匹配到所有的HTTP请求，并且都会抛出异常（找不到指定的异常类，然后抛出了runtimeException）。
但是，我只是想让某个接口抛异常，没加参数，应该告诉我创建的命令不合法。

**Comment by xcaspar** [comment]
@auyang-0626 I understand what you mean. It's a bug. It should return error message for the error parameters. We will fix it in next version.

**Comment by xcaspar** [comment]
Add exception value check. See chaosblade-io/chaosblade-exec-jvm@217f817a7695f42ff1cc2dce88a33390d3a8e54c for the detail.
