### ISSUE TITLE
how to read help

### ISSUE THREAD

**Issue by liangyuanpeng** [chaosblade-io/chaosblade#165]
## Issue Description

Type: *question*

### Describe what happened (or what feature you want)

```
lanren@lanren-virtual-machine:/disk/chaosblade-0.2.0$ ./blade
FATA[0000] select experiment table exists err when invoke db prepare, unable to open database file
lanren@lanren-virtual-machine:/disk/chaosblade-0.2.0$ ./blade help
FATA[0000] select experiment table exists err when invoke db prepare, unable to open database file
```

I just want to learn how to use the blade，but i got some error and i don`t know what this mean

any help? please

### How to reproduce it (as minimally and precisely as possible)

1. download blade from [https://github.com/chaosblade-io/chaosblade/releases](https://github.com/chaosblade-io/chaosblade/releases)
2.  run ``blade``
3. 

### Tell us your environment

ubuntu16

**Comment by hiddenzzh** [comment]
up

**Comment by sanyangji** [comment]
Something wrong with sqlite3. I guess your virtual machine doesn't install sqlite3 (blade depends on sqlite3).
You can check by exec command:`sqlite3`

**Comment by xcaspar** [comment]
@liangyuanpeng Maybe caused by the user permission.
