### ISSUE TITLE
stop process:for linux,the command is kill -19;for mac is kill -18

### ISSUE THREAD

**Issue by zeuskim** [chaosblade-io/chaosblade#167]
i have read the code:

![image](https://user-images.githubusercontent.com/11733402/63694266-a00e4100-c848-11e9-8e1b-785a4019ac28.png)

stop process:for linux,the command is kill -19
![image](https://user-images.githubusercontent.com/11733402/63694163-65a4a400-c848-11e9-9e05-0d00f2d2e0da.png)
for mac(in my imac 10.14.5),the command is kill -18
![image](https://user-images.githubusercontent.com/11733402/63694233-8967ea00-c848-11e9-9d1c-47ab7f7ccec7.png)
Is this a general question?
may be it can be repalced by kill -STOP pid、kill – CONT pid

thanks

**Comment by xcaspar** [comment]
@zeuskim Yes, you are right. Can you submit a pr to fix it?

**Comment by zeuskim** [comment]
@xcaspar of course

**Comment by zeuskim** [comment]
@xcaspar please see https://github.com/chaosblade-io/chaosblade/pull/168
