### ISSUE TITLE
 support to simulate full GC in jvm

### ISSUE THREAD

**Issue by chengshiwen** [chaosblade-io/chaosblade#172]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

*feature request*

### Describe what you expected to happen

support to simulate full GC in jvm

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
@chengshiwen You can use oom experiment with soft mode to simulate full GC. Execute `blade c jvm OutOfMemoryError -h` to see the detail.
