### ISSUE TITLE
Currently there is support for dubbo, will support microservice?

### ISSUE THREAD

**Issue by iwtbs** [chaosblade-io/chaosblade#175]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
Currently there is support for dubbo, will support microservice in k8s?
I make a microservice project in k8s, and I want to inject some error in contain and jvm, how should I do?

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
Some important components will be supported later, such as api gateway, distribute config and service registry. We would like to develop some chaos specifications for microservice components.
