### ISSUE TITLE
fullload:taskset command not exist

### ISSUE THREAD

**Issue by zeuskim** [chaosblade-io/chaosblade#177]
hi ,when I run the command on imac:
 ./blade  create cpu fullload  --timeout 60 --cpu-count 1 --cpu-list 1
{"code":521,"success":false,"error":"taskset command not exist"}

I have read the code, tasket command is called when flag  --cpu-list  is set
Is there a similar tool for tasket on mac?

thanks

**Comment by xcaspar** [comment]
Sorry, I don't know that. If you want to test the feature, you can run it on linux platform.
