### ISSUE TITLE
Adjust the cli directory structure to facilitate third-party development

### ISSUE THREAD

**Issue by yixy** [chaosblade-io/chaosblade#189]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)

The code of chaosblade/cli is the command-line package, not the library package. Therefore, when a third party uses chaosblade to develop it into their own project, it may need to invade the code in the cli directory to modify it, which is not convenient for smooth migration after the subsequent chaosblade upgrade.

### Describe what you expected to happen

Based on the above, Could we adjust the cli directory structure as follows, simplify the main.go content by moving other code into the cmd library package, and facilitate the integration of chaosblade into other projects.

```
▾ chaosblade/
    ▾ cli/
        ▾ cmd/
            cli.go
            commands.go
            ......
        main.go
```

main.go file:

```
package main

import (
	"fmt"
	"os"

	"github.com/chaosblade-io/chaosblade/cli/cmd"
)

func main() {
	baseCommand := cmd.CmdInit()
	if err := baseCommand.CobraCmd().Execute(); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "%s\n", err.Error())
		os.Exit(1)
	}
}
```

Please help confirm if this is appropriate, thank you!

**Comment by xcaspar** [comment]
@yixy Good suggestion.
