### ISSUE TITLE
Simulate docker network latency issues

### ISSUE THREAD

**Issue by yan851** [chaosblade-io/chaosblade#192]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
例如：
 /opt/chaosblade/blade create network delay --interface eth0 --time 3000
在虚拟机上或者实体机上这个命令是可以用的。但在docker中，执行就抛出错误。这是什么原因，请告知，谢谢~！

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
@yan851 
报错信息是什么？
docker 容器的操作系统版本以及使用的 chaosblade 版本是什么？

**Comment by xcaspar** [comment]
如果有问题，请参考：https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/blade-create-docker-network
