### ISSUE TITLE
k8s delete pod experiment get signal killed

### ISSUE THREAD

**Issue by sparrow629** [chaosblade-io/chaosblade#193]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
when use the command of deleting pod by k8s, the pod is deleted successfully in fact. But the result shows like below shows which meas failed. 
```
./blade create k8s delete --pod <podname>  --namespace <namespace>
{"code":604,"success":false,"error":"pods \"<podname>\" deleted\n signal: killed"}
```
It is strange that the correct infomation in the error message that "pods \"<podname>\" deleted\n" actually shows successfully, with a signal of killed. It leads to the return code always show 604, exec command error.

Then use the original k8s command directly:
```
kubectl delete pod <podname>  --namespace=<namespace>
pods "<podname>" deleted
```
The result also return the same infomaiton as the error result mentioned, without the error signal "killed"

### Describe what you expected to happen
It gets the  correct return code when the pod is deleted

### How to reproduce it (as minimally and precisely as possible)

1. ./blade create k8s delete --pod <podname>  --namespace <namespace>
2. 

### Tell us your environment
chaosblade： release version 0.2.0
OS：CentOS Linux release 7.2 (Final)
K8S：v1.12.4

### Anything else we need to know?
Temporarily, I modify part of the file local.go from line 42:
```
output, err := cmd.CombinedOutput()
	if err != nil {
		if err.Error() == "signal: killed"{
			result := string(output)
			return transport.ReturnSuccess(result)
		}
		errMsg := fmt.Sprintf(string(output) + " " + err.Error())
		return transport.ReturnFail(transport.Code[transport.ExecCommandError], errMsg)
	}
```
I wonder if this modification will lead to other problem related to kill process? This can avoid the mistake error report.

**Comment by xcaspar** [comment]
@sparrow629I have not reproduced your question, what is the name of your pod and namespace?

**Comment by sparrow629** [comment]
> @sparrow629I have not reproduced your question, what is the name of your pod and namespace?
> 
> ```
> blade c k8s delete --pod foo-service-85789b958b-tzblr --namespace default
> {"code":200,"success":true,"result":"f92131854391dc39"}
> ```

The pod and namespace is correct, because I can use orignal command and blade command to kill the pod successfully. The difference is that the blade command delete the pod successfully with an   error code 604 whose error message shows "signal: killed"
```
./blade create k8s delete --pod topicrecommendextreadtest-bwq87kz3s68-0 --namespace ns-prj7p5nq-1123873-test
```

**Comment by xcaspar** [comment]
@sparrow629 Please use the latest version to try. 中文使用文档：https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/blade-create-k8s
