### ISSUE TITLE
Under certain circumstances,process of disk burn not quit after timeout

### ISSUE THREAD

**Issue by zeuskim** [chaosblade-io/chaosblade#194]
## Issue Description

i run  ./blade create disk burn --read --timeout 60,and succeed:
{"code":200,"success":true,"result":"0872b9669f970a07"}
but after 60s,the process not quit:
![image](https://user-images.githubusercontent.com/11733402/65156726-2988eb80-da62-11e9-94cf-a54965ec78dd.png)

![image](https://user-images.githubusercontent.com/11733402/65156708-1ece5680-da62-11e9-956d-3625179e2857.png)

then i tried to read the code:
![image](https://user-images.githubusercontent.com/11733402/65156780-3efe1580-da62-11e9-87b6-db999c82d4c3.png)
we find the processid by processname,and kill the proceess id:
![image](https://user-images.githubusercontent.com/11733402/65158403-d5cbd180-da64-11e9-935d-9d4e737ac3ba.png)

the processname like:
![image](https://user-images.githubusercontent.com/11733402/65156905-71a80e00-da62-11e9-83f5-3109f2a3de29.png)
and default value are:var taskName = []string{"if=/dev/zero", "of=/dev/null"}
so i guess the proceessid changed,and read a small file  for testing(will finish reading in serval second one time) :
![image](https://user-images.githubusercontent.com/11733402/65157118-cc416a00-da62-11e9-8082-3367dc00aae3.png)

The process number that "grep" gets is different every time. The problem seems to be: The command “burn disk --read ”is to read a fixed file. When the file is read once, if you read the same file again from the beginning (for loop), the process number of “dd” will change.
In this case, the obtained process number is expired，so the process can not be killed.

i solved it by kill the process“chaosblade-0.2.0/bin/chaos_burnio --file-system overlay --size 1 --count 1024 --read=true --write=false --nohup=true” instead,
which Just replace
![image](https://user-images.githubusercontent.com/11733402/65158174-81285680-da64-11e9-8500-936c93d9ac83.png)
 with 
![image](https://user-images.githubusercontent.com/11733402/65158184-84bbdd80-da64-11e9-8dc2-7eeda9847c86.png) for "disk burn --read"

**Comment by xcaspar** [comment]
@zeuskim Thank for reporting the bug. I will fix it in the next version. Related issue: #195
