### ISSUE TITLE
in my linux os,disk burn  --read   is not work 

### ISSUE THREAD

**Issue by zeuskim** [chaosblade-io/chaosblade#195]
I found that the cause of the problem is: look up the directory through mount-point, sometimes the directory does not exist, resulting in the failure to read

So I hope that you can provide a command to read and write  for a specific files, rather than through the mount-point parameter.

In my case, I temporarily test this by first writing the content to a file and then reading it.
dd if=/dev/zero of=test bs=500M count=1 oflag=dsync
![image](https://user-images.githubusercontent.com/11733402/65159423-a4540580-da66-11e9-9b30-1dc2ec80112d.png)
and then read:
if= test of=/dev/null bs=%sM count=%s iflag=dsync,direct,fullblock

the code:
func burnRead(fileSystem, size, count string) {
   // "if" arg in dd command is file system value, but "of" arg value is related to mount point
   args := fmt.Sprintf(`if=%s of=/dev/null bs=%sM count=%s iflag=dsync,direct,fullblock`, fileSystem, size, count)
   filename := "burniochaosbladewrite"
   for {
      response := channel.Run(context.Background(), "dd", args)
      if !response.Success {
         fmt.Println(fmt.Sprintf("The file system named %s is not supported or %s", fileSystem, response.Err))
         //write file 500M
         if !isFileExists(filename) {
            args := fmt.Sprintf(`if=/dev/zero of=%s bs=500M count=1 oflag=dsync `, filename) // oflag=dsync
            response := channel.Run(context.Background(), "dd", args)
            if !response.Success {
               channel.Run(context.Background(), "rm", fmt.Sprintf(`-rf %s`, filename))
               bin.PrintAndExitWithErrPrefix(response.Err)
               return
            }
         }
         //read
         args = fmt.Sprintf(`if=%s of=/dev/null bs=%sM count=%s iflag=dsync,direct,fullblock`, filename, size, count)
      }
   }
}

thank you !

**Comment by xcaspar** [comment]
@zeuskim Yes, I agree. I'm fixing it.
