### ISSUE TITLE
能不能搞个中文的wiki?

### ISSUE THREAD

**Issue by davichi11** [chaosblade-io/chaosblade#2]
求中文版 英文版看的费劲

**Comment by Maijh97** [comment]
同上

**Comment by mingcheng** [comment]
这个不重要

**Comment by xcaspar** [comment]
我们后续会完善文档并提供中文文档。也非常欢迎大家参与进来，一起共建。

---

We will improve the documentation and provide Chinese documentation in the future. You are also very welcome to participate and build together.

**Comment by jefferent2019** [comment]
chrome浏览器，右键翻译。

**Comment by alisanguo** [comment]
我想在内网搭建搭建一下环境，因为无法联网，只能在外网先下载依赖。问一下chaosblade java agent 和tools.jar 在哪可以下载？

**Comment by xcaspar** [comment]
> 我想在内网搭建搭建一下环境，因为无法联网，只能在外网先下载依赖。问一下chaosblade java agent 和tools.jar 在哪可以下载？

你可以下载 chaosblade [v0.0.1](https://github.com/chaosblade-io/chaosblade/releases/tag/v0.0.1) release 包，里面还有以上文件。

-----

You can download the chaosblade [v0.0.1](https://github.com/chaosblade-io/chaosblade/releases/tag/v0.0.1) release package contains the above files.

**Comment by alisanguo** [comment]
> > 我想在内网搭建搭建一下环境，因为无法联网，只能在外网先下载依赖。问一下chaosblade java agent 和tools.jar 在哪可以下载？
> 
> 你可以下载 chaosblade [v0.0.1](https://github.com/chaosblade-io/chaosblade/releases/tag/v0.0.1) release 包，里面含有以上文件。
> 
> You can download the chaosblade [v0.0.1](https://github.com/chaosblade-io/chaosblade/releases/tag/v0.0.1) release package contains the above files.

thanks

**Comment by xcaspar** [comment]
@davichi11 @Maijh97 ，中文版的 [README](https://github.com/chaosblade-io/chaosblade/blob/master/README_CN.md) 已提供。

新增了 [新手指南](https://github.com/chaosblade-io/chaosblade/wiki/%E6%96%B0%E6%89%8B%E6%8C%87%E5%8D%97)，能快速上手使用 chaosblade
