### ISSUE TITLE
CPU burn can't be executed in docker container

### ISSUE THREAD

**Issue by xcaspar** [chaosblade-io/chaosblade#202]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
`blade c cpu fl`

`{"code":604,"success":false,"error":"create cgroup error, mkdir /sys/fs/cgroup/freezer/chaos_burncpu: read-only file system exit status 1"}`

### Describe what you expected to happen
success

### How to reproduce it (as minimally and precisely as possible)
run it in container

**Comment by yixy** [comment]
run docker with `--privileged=true` would work for this scene. Is this not a good idea? 🤔️

```
docker run -it --privileged=true 2c71c37852c2 /bin/bash
```
