### ISSUE TITLE
./blade create docker mem load error

### ISSUE THREAD

**Issue by ZhangYuJuan** [chaosblade-io/chaosblade#208]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
./blade create docker mem load --container build_nuwa_turing_run_1_d0f0609df51d --mem-percent 100
{"code":502,"success":false,"error":"not support the action command for load"}

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

chaosblade-0.3.0
### Anything else we need to know?

**Comment by ZhangYuJuan** [comment]
docker disk 同样提示 not support the action command for fill/burn

**Comment by xcaspar** [comment]
This feature is already supported in version 0.5.0
