### ISSUE TITLE
create http 

### ISSUE THREAD

**Issue by ZhangYuJuan** [chaosblade-io/chaosblade#209]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
./blade create http delay --uri 127.0.0.1:6055 --time 100
{"code":500,"success":false,"error":"cannot get port from local, please execute prepare command first"}

### Describe what you expected to happen
create http需要先prepare jvm 相关http的java工程吗？

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
chaosblade-0.3.0

**Comment by xcaspar** [comment]
@ZhangYuJuan 是，http 场景是作用于 apache httpclient 组件上，所以依托于 java agent.
