### ISSUE TITLE
Can you support more experiments in k8s?

### ISSUE THREAD

**Issue by lcwus2** [chaosblade-io/chaosblade#210]
## Issue Description

Type:  *feature request*

### Describe what happened (or what feature you want)
some more experiments in k8s, like network delay/loss, about memory and cpu ...

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
K8S

**Comment by xcaspar** [comment]
Yes,  we will release alpha version next week.

**Comment by xcaspar** [comment]
@lcwus2 Please download the latest version 0.4.0. 中文使用文档：https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/blade-create-k8s
