### ISSUE TITLE
if the  cplus experiment does not work, how to check the cause

### ISSUE THREAD

**Issue by haowei0515** [chaosblade-io/chaosblade#213]
## Issue Description

cplus expriment does not work

### Describe what happened (or what feature you want)
socket-server code: 
https://yq.aliyun.com/go/articleRenderRedirect?url=https%3A%2F%2Fchaosbladecplus.oss-cn-beijing.aliyuncs.com%2FSocket-server.tar.gz%3Fspm%3Da2c4e.100239.0.0.75a36fadzUipZ5%26amp%3Bfile%3DSocket-server.tar.gz
socker-client code:
https://yq.aliyun.com/go/articleRenderRedirect?url=https%3A%2F%2Fchaosbladecplus.oss-cn-beijing.aliyuncs.com%2FSocket-client.tar.gz%3Fspm%3Da2c4e.100239.0.0.75a36fadzUipZ5%26amp%3Bfile%3DSocket-client.tar.gz

when i want to make a delay or return exception expriment for the socket code, but it does not work
so i want to know how to check the reason 
eg: delay exception:
./blade create cplus delay --breakLine tcp_server.cpp:42 --delayDuration 5 --fileLocateAndName /home/work/chaosblade/chaosblade-0.3.0/tool/tcp_server/server  --forkMode child --initParams 8998 --processName server

### How to reproduce it (as minimally and precisely as possible)

1. prepare the socket server or socket client, download and complie with g++
start the server:    ./server 8998
2. add the expriment
./blade create cplus delay --breakLine tcp_server.cpp:42 --delayDuration 5 --fileLocateAndName /home/work/chaosblade/chaosblade-0.3.0/tool/tcp_server/server  --forkMode child --initParams 8998 --processName server
3. ./client 127.0.0.1 8998
input something
the socker server will print the input, but it is not delay

### Tell us your environment
centos
java8 
cplus
### Anything else we need to know?
when complie the socket code with g++, you should add the librarys in the flows
#include <cstring>
#include <stdio.h>
#include <cstdlib>
 #include<stdlib.h>

**Comment by xcaspar** [comment]
@leonardo669 please check it.

**Comment by leonardo669** [comment]
hi, @haowei0515 ,  could you let me know if you have read the article follows, and pass the test following the guid?  
https://github.com/chaosblade-io/chaosblade-exec-cplus/wiki/Developer-guide

https://github.com/chaosblade-io/chaosblade-exec-cplus/wiki/%E5%BC%80%E5%8F%91%E8%80%85%E6%8C%87%E5%8D%97

**Comment by haowei0515** [comment]
@leonardo669 yes, my expriment is  as follows
（1）`./blade create cplus delay --breakLine tcp_server.cpp:37 --fileLocateAndName /home/work/chaosblade/chaosblade-0.3.0/tool/tcp_server/server --delayDuration 5 --forkMode parent --initParams 8778 --processName server --libLoad " "`

         the logs is as follows:

        `2019-10-18 10:53:40 INFO  Succeed to create, requestParamsBean: 
         RequestParamsBean{suid='41b8ab4d9377e0a2', target='cplus', action='delay', 
         breakLine='tcp_server.cpp:37', returnValue='null', delayDuration='5', varaibleName='null', 
        varaibleValue='null', initParams='8778', 
        fileLocateAndName='/home/work/chaosblade/chaosblade-0.3.0/tool/tcp_server/server', 
        forkMode='parent', libLoad='', processName='server'}`

(2) the code of tcp_server.cpp:
```
25 int tcp_server::recv_msg() {
 26         while( 1 ){
 27                 socklen_t sin_size = sizeof(struct sockaddr_in);
 28                 if(( accept_fd = accept(socket_fd,(struct sockaddr*) &remote_addr,&sin_siz    e)) == -1 )
 29                 {
 30                         throw "Accept error!";
 31                         continue;
 32                 }
 33                 string startTime = getTime();
 34                 printf("Before print: %s\n", startTime.c_str());
 35
 36                 printf("Received a connection from %s\n",(char*) inet_ntoa(remote_addr.sin    _addr));


 37                 _**this is the line for execption injection**_


 38                 string endTime = getTime();
 39                 printf("After print: %s\n", endTime.c_str());
 40
 41         if( !fork() ) {
 42                         char buffer[MAXSIZE];
 43                         memset(buffer,0,MAXSIZE);
 44                         if( ( read(accept_fd,buffer,MAXSIZE)) < 0 ) {
 45                                 throw("Read() error!");
 46                         } else {
 47                                 printf("Received message: %s\n",buffer);
 48                                 break;
 49                         }
 50                         exit(0);
 51                 }
 52                 close(accept_fd);
 53         }
 54         return 0;
 55 }

```
（3）the result is as follows, it does not delay
```
Before print: 2019-10-18 11:06:59
Received a connection from 127.0.0.1
After print: 2019-10-18 11:06:59
Received message: hello
```
Did I do something wrong?
but the modify exception works:
(1)comamnd
`./blade create cplus modify --varaibleName listen_port --varaibleValue 8977 --breakLine tcp_server.cpp:14 --fileLocateAndName /home/work/chaosblade/chaosblade-0.3.0/tool/tcp_server/server --forkMode child --processName server --initParams 8778 --debug`
(2)result
`./client 127.0.0.1 8977
send message to server:
`

**Comment by leonardo669** [comment]
if seems like in tcp_server.cpp，the line 37， doesn't have any code,  so the injection didn't work, could you change the command from :

    ./blade create cplus delay --breakLine tcp_server.cpp:37 --fileLocateAndName /home/work/chaosblade/chaosblade-0.3.0/tool/tcp_server/server --delayDuration 5 --forkMode parent --initParams 8778 --processName server --libLoad " "

to:  

    ./blade create cplus delay --breakLine tcp_server.cpp:36 --fileLocateAndName /home/work/chaosblade/chaosblade-0.3.0/tool/tcp_server/server --delayDuration 5 --forkMode parent --initParams 8778 --processName server --libLoad " "

then try again?

**Comment by haowei0515** [comment]
@leonardo669 it still does not work
`/blade create cplus delay --breakLine tcp_server.cpp:36 --fileLocateAndName /home/work/chaosblade/chaosblade-0.3.0/tool/tcp_server/server --delayDuration 5 --forkMode parent --initParams 8778 --processName server --libLoad " "`

but the result still does not delay no matter the forkMode is parent or child

`Before print: 2019-10-21 18:18:05
Received a connection from 127.0.0.1
After print: 2019-10-21 18:18:05
Received message: helli
`

**Comment by leonardo669** [comment]
@haowei0515,  I am sorry for replying so late, because a little busy for me recently. I have tested pass the code your uploaded, I found the break line should be added at `tcp_server.cpp`，the line `33`:

    printf("Received a connection from %s\n",(char*) inet_ntoa(remote_addr.sin_addr));

 and the forkMode parameter should be `parent`,  and the value of the parameter `processName` can be set the same as the parameter `fileLocateAndName`, so the delay command should be:

    ./blade create cplus delay --breakLine tcp_server.cpp:33 --fileLocateAndName /home/work/chaosblade/chaosblade-0.3.0/tool/tcp_server/server --delayDuration 5 --forkMode parent --initParams 8778 --processName /home/work/chaosblade/chaosblade-0.3.0/tool/tcp_server/server --libLoad " "

or:

    ./blade create cplus delay --breakLine tcp_server.cpp:33 --fileLocateAndName /home/work/chaosblade/chaosblade-0.3.0/tool/tcp_server/server --delayDuration 5 --forkMode parent --initParams 8778 --processName /home/work/chaosblade/chaosblade-0.3.0/tool/tcp_server/server

Could you test it again, and let me know if it works? thanks!
