### ISSUE TITLE
mem burn can't be executed in docker container

### ISSUE THREAD

**Issue by yixy** [chaosblade-io/chaosblade#216]
## Issue Description ##

Type: bug report ( or kind/question )

## Describe what happened (or what feature you want)  ##

`mem load` can't be executed in docker container, because `mount tmpfs` is worked on root privilege.

```
root@d5fbd52fe32c:/go/chaosblade-0.3.0# ./blade c mem load --mem-percent=50
{"code":604,"success":false,"error":"{\"code\":604,\"success\":false,\"error\":\"mount: permission denied\\n exit status 32\"} exit status 1"}
```

run docker with `--privileged=true`  flag would work for this scene, but I don't know is this a solution for this question?

```
docker run --privileged -it --network mylab --ip 192.168.16.100  golang:1.12.1 /bin/bash

root@e6c70a9b88d2:/go/chaosblade-0.3.0# ./blade c mem load --mem-percent=50
{"code":200,"success":true,"result":"a37d112f2726c1dd"}
root@e6c70a9b88d2:/go/chaosblade-0.3.0# ./blade destroy a37d112f2726c1dd
{"code":200,"success":true,"result":"command: mem load --debug false --help false --mem-percent 50"}
```

## environment ##

chaosblade 0.3.0

## How to reproduce it (as minimally and precisely as possible) ##

run it in container

**Comment by xcaspar** [comment]
@yixy You can download latest version and use the following command to implement:
```
blade create mem load --mem-percent 80 --mode ram
```
You can reopen it if you still have any questions.
