### ISSUE TITLE
./blade create disk fill support --percent flags?

### ISSUE THREAD

**Issue by seamusdlut** [chaosblade-io/chaosblade#217]
## Issue Description
now the *disk fill* command only support --size flag, can you support the --disk-percent flag?   

disk-percent=(used disk size)/(disk total size)

Type: *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

chaosblade 0.3.0

**Comment by xcaspar** [comment]
#241
