### ISSUE TITLE
./blade create docker cpu fullload: "Error: No such container: a016f6daa1f2-cpu\n exit status 1"

### ISSUE THREAD

**Issue by seamusdlut** [chaosblade-io/chaosblade#218]
## Issue Description

#./blade create docker cpu fullload --container a016f6daa1f2 --cpu-percent 80
{"code":604,"success":false,"error":"Error: No such container: a016f6daa1f2-cpu\n exit status 1"}

Type: *bug report* 

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
user: root

#docker --version
Docker version 1.12.6, build 7f8391c BUILDTIME:2019-05-28 17:57:48

#uname -a
Linux xxx  4.9.93-010.ali3000.alios7.x86_64 #1 SMP Fri Apr 20 00:18:51 CST 2018 x86_64 x86_64 x86_64 GNU/Linux

chaosblade version: 0.3.0
### Anything else we need to know?

#ping registry.cn-hangzhou.aliyuncs.com
connect: Network is unreachable

**Comment by xcaspar** [comment]
@seamusdlut Please use the latest version to try. 中文使用文档：https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/blade-create-docker
