### ISSUE TITLE
Suggestions for k8s delete pod

### ISSUE THREAD

**Issue by hechuan73** [chaosblade-io/chaosblade#225]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

Now the command below will delete a pod named "nginx-65f88748fd-7fttw" .
```
./blade c k8s delete --pod nginx-65f88748fd-7fttw
```
But the k8s will create another nginx pod instance immediately.

### Describe what you expected to happen

Can the command work until we delete this experiment? And then allow the k8s to create another pod instance.

Additionally, could you please support to delete pod by pod name not id, for example, we can enter the command:

```
./blade c k8s delete --pod nginx
```
to delete one of the nginx pod instances, or delete all of the instances. Thanks!

BTW, when can we be your early adopters of your new version? :)

### How to reproduce it (as minimally and precisely as possible)

1. kubectl apply -f nginx-deployment-file.yaml
2. ./blade c k8s delete --pod nginx-65f88748fd-7fttw
3. kubectl get pods

### Tell us your environment
1. K8S 1.14.1
2. CentOS 7

**Comment by xcaspar** [comment]
@hechuan73 Thank you for your suggestion. We optimized the kubernetes chaos experiments in the latest version v0.4.0-alpha. 相关的中文文档：https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/blade-create-k8s
