### ISSUE TITLE
blade prepare jvm error: Agent JAR loaded but agent failed to initialize

### ISSUE THREAD

**Issue by JangNum** [chaosblade-io/chaosblade#228]
## Issue Description

Bug report 

### Describe what happened (or what feature you want)

When performing the second experiment according to the novice guide, an error is reported when executing blade prepare jvm --process. The error message is: sandbox load jvm failed: Agent JAR loaded but agent failed to initialize.exit status 255.
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

jdk 1.8.0_192
go 1.13.4

**Comment by xcaspar** [comment]
@JangNum Can you add `-j JAVA_HOME` flag in prepare command to retry? For example, `blade prepare jvm --process xxx -j /opt/xxx/java_1.8`

**Comment by JangNum** [comment]
> @JangNum Can you add `-j JAVA_HOME` flag in prepare command to retry? For example, `blade prepare jvm --process xxx -j /opt/xxx/java_1.8`
It report the same error...It is not compatible with some dubbo applications?

**Comment by JangNum** [comment]
> @JangNum Can you add `-j JAVA_HOME` flag in prepare command to retry? For example, `blade prepare jvm --process xxx -j /opt/xxx/java_1.8`

I solve the error by executing source /etc/profile,thanks.

**Comment by JangNum** [comment]
I used the prepare command to mount the package you gave on the test server and it worked fine, but when using the prepare command on the production machine to mount the tomcat application, the above error appeared again. 
The command is ./blade prepare jvm --pid 16558

**Comment by xcaspar** [comment]
The cause of this problem is that the program cannot get JAVA_HOME, you can specify JAVA_HOME through the -j parameter or execute `export JAVA_HOME=XXX` to solve.

**Comment by xcaspar** [comment]
I remove the strong validate in next version(0.4.0) , but however, the problem is that the tool.jar package may fail to load.

**Comment by JangNum** [comment]
> I remove the strong validate in next version(0.4.0) , but however, the problem is that the tool.jar package may fail to load.

I solved the problem by restarting the application. Maybe this can give you some ideas.

**Comment by xcaspar** [comment]
If you encounter the same problem, you can see #268 to resolve it.
