### ISSUE TITLE
The doc is outdated. No blade create command in 0.4.0 version

### ISSUE THREAD

**Issue by mark-neil-wang** [chaosblade-io/chaosblade#231]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
@mark-neil-wang In the 0.4.0-alpha version create command exists, the chaosblade tool where you downloaded and how to judge the create command does not exit?

**Comment by xcaspar** [comment]
@mark-neil-wang Please download the latest version to test. Thank you.
