### ISSUE TITLE
Under sudo, execute blade create network drop [], can't really destroy [Linux]

### ISSUE THREAD

**Issue by wulixiaobo** [chaosblade-io/chaosblade#24]
cmd
```
sudo ./blade create network drop --service-port 8888
```
response
```
{"code":200,"success":true,"result":"2b3bf570994e859e"}
```
查看iptables下已新增drop配置，接口测试后发现配置生效

cmd
```
sudo ./blade destroy 2b3bf570994e859e
```
接口测试后发现配置依然存在，查看iptables rules发现未被清除

> Table: filter
> Chain INPUT (policy ACCEPT)
> num  target     prot opt source               destination
> 1    DROP       tcp  --  0.0.0.0/0            0.0.0.0/0           tcp dpt:8888
> 2    DROP       udp  --  0.0.0.0/0            0.0.0.0/0           udp dpt:8888

**Comment by xcaspar** [comment]
> cmd
> 
> ```
> sudo ./blade create network drop --service-port 8888
> ```
> response
> 
> ```
> {"code":200,"success":true,"result":"2b3bf570994e859e"}
> ```
> 查看iptables下已新增drop配置，接口测试后发现配置生效
> 
> cmd
> 
> ```
> sudo ./blade destroy 2b3bf570994e859e
> ```
> 接口测试后发现配置依然存在，查看iptables rules发现未被清除
> 
> > Table: filter
> > Chain INPUT (policy ACCEPT)
> > num  target     prot opt source               destination
> > 1    DROP       tcp  --  0.0.0.0/0            0.0.0.0/0           tcp dpt:8888
> > 2    DROP       udp  --  0.0.0.0/0            0.0.0.0/0           udp dpt:8888

Please provide the blade version by `./blade version` command and os version，thank you. @wulixiaobo

**Comment by wulixiaobo** [comment]
> > cmd
> > ```
> > sudo ./blade create network drop --service-port 8888
> > ```
> > response
> > ```
> > {"code":200,"success":true,"result":"2b3bf570994e859e"}
> > ```
> > 查看iptables下已新增drop配置，接口测试后发现配置生效
> > cmd
> > ```
> > sudo ./blade destroy 2b3bf570994e859e
> > ```
> > 接口测试后发现配置依然存在，查看iptables rules发现未被清除
> > > Table: filter
> > > Chain INPUT (policy ACCEPT)
> > > num  target     prot opt source               destination
> > > 1    DROP       tcp  --  0.0.0.0/0            0.0.0.0/0           tcp dpt:8888
> > > 2    DROP       udp  --  0.0.0.0/0            0.0.0.0/0           udp dpt:8888
> 
> Please provide the blade version by `./blade version` command and os version，thank you. @wulixiaobo

version: 0.0.1

**Comment by wulixiaobo** [comment]
try below cmd:
not work: ./blade create jvm tce
do work: ./blade create jvm throwCustomException
result:tce can not effect

**Comment by xcaspar** [comment]
@wulixiaobo I'm very sorry to replay so late.  The first question I have fixed it and the second question I didn't reappear it. Can you provide your os version?

**Comment by xcaspar** [comment]
@wulixiaobo 0.0.2 version has been released, please use the version to retry. Reopen it if your problem has not been solved. Thank you :-)
