### ISSUE TITLE
latest code lost create command

### ISSUE THREAD

**Issue by zousheng** [chaosblade-io/chaosblade#245]
## Issue Description

Type: *bug report* or *feature request*
   bug report
### Describe what happened (or what feature you want)

     I built the latest code, and found create command disappeared from the command list when I run ./blade.

### Describe what you expected to happen
    the crate command should be there and can create a test env.

### How to reproduce it (as minimally and precisely as possible)

1. I download the latest code to a linux box,
2. run make, and no errors
3. run ./blade,  then command list doesn't show create

### Tell us your environment

CentOS Linux release 7.2.1511

### Anything else we need to know?

  I switched to tag v0.3.0, it's working.

**Comment by xcaspar** [comment]
I have fixed it in #243 PR, please pull new codes in master branch and rebuild it.
