### ISSUE TITLE
The way the servlet is created does not work for the delay mechanism

### ISSUE THREAD

**Issue by DontGiveUpWJ** [chaosblade-io/chaosblade#25]
When I was creating a chaotic experiment for a servlet, I wanted a specific access address to be delayed for a few seconds. After the configuration was completed, it did not take effect. The configuration information is as follows.

Jar package start command：nohup java -Dserver.port=8081 -Djava.net.preferIPv4Stack=true -Dproject.name=ttt -jar ttt.jar > ttt.nohup.log 2>&1 &

Java agent：./blade prepare jvm --process ttt

Created command:./blade create servlet delay --time 3300 --pathinfo /test1 --process ttt --servletpath http://192.168.139.135:8081

After the configuration is complete, after all the displays are successful, the URL is accessed and found to be invalid.

If there is a solution, you can send the solution to my email address at dontgiveupwj@163.com

I hope that you can have a detailed Chinese document to describe the role of each parameter and the configuration entry case for mounting different types of services. thank you very much. At the same time, I hope that chaosblade will be more perfect in the future road show and can go further.

**Comment by xcaspar** [comment]
> When I was creating a chaotic experiment for a servlet, I wanted a specific access address to be delayed for a few seconds. After the configuration was completed, it did not take effect. The configuration information is as follows.
> 
> Jar package start command：nohup java -Dserver.port=8081 -Djava.net.preferIPv4Stack=true -Dproject.name=ttt -jar ttt.jar > ttt.nohup.log 2>&1 &
> 
> Java agent：./blade prepare jvm --process ttt
> 
> Created command:./blade create servlet delay --time 3300 --pathinfo /test1 --process ttt --servletpath http://192.168.139.135:8081
> 
> After the configuration is complete, after all the displays are successful, the URL is accessed and found to be invalid.
> 
> If there is a solution, you can send the solution to my email address at [dontgiveupwj@163.com](mailto:dontgiveupwj@163.com)
> 
> I hope that you can have a detailed Chinese document to describe the role of each parameter and the configuration entry case for mounting different types of services. thank you very much. At the same time, I hope that chaosblade will be more perfect in the future road show and can go further.

@DontGiveUpWJ If request url is `http://192.168.139.135:8081/test1`, and you want to drill  `/test1`, the blade command should be `./blade create servlet delay --time 3300  --process ttt --servletpath /test1`.

**Comment by DontGiveUpWJ** [comment]
嗯 已经可以了，谢谢指导
