### ISSUE TITLE
What is the difference between the blade c dubbo and blade c jvm commands? 

### ISSUE THREAD

**Issue by JangNum** [chaosblade-io/chaosblade#252]
## Issue Description

Can the command for injecting faults into the dubbo interface be implemented using the blade c jvm delay classname methodname time ... command in addition to the blade c dubbo delay classname provider methodname ...?

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
The differences are as follows:
1. Dubbo target are simpler and easier to use.
2. The specified class method  in jvm target is more abundant.
