### ISSUE TITLE
blade create k8s node-cpu can not be used

### ISSUE THREAD

**Issue by WillYan881118** [chaosblade-io/chaosblade#258]
## Issue Description
./blade create k8s node-cpu fullload  --name blade-2 --cpu-percent 80 --kubeconfig ~/.kube/config 
kubectl apply -f chaosblade_cpu_load.yaml

I tryed to fullload node cpu uesing the example yml or command,but it can not work 

### How to reproduce it (as minimally and precisely as possible)
after kubectl apply -f 
k8s_chaosblade-operator_chaosblade-operator-779d8c7d8-cgbv5_kube-system_121ef6b0-1708-11ea-9d28-0242ac120003_0{"level":"error","ts":1575517295.069692,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"chaosblade-controller","request":"/cpu-load","error":"ChaosBlade.chaosblade.io \"cpu-load\" is invalid: []: Invalid value: map[string]interface {}{\"kind\":\"ChaosBlade\", \"apiVersion\":\"chaosblade.io/v1alpha1\", \"metadata\":map[string]interface {}{\"creationTimestamp\":\"2019-12-05T03:41:35Z\", \"annotations\":map[string]interface {}{\"kubectl.kubernetes.io/last-applied-configuration\":\"{\\\"apiVersion\\\":\\\"chaosblade.io/v1alpha1\\\",\\\"kind\\\":\\\"ChaosBlade\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"name\\\":\\\"cpu-load\\\",\\\"namespace\\\":\\\"\\\"},\\\"spec\\\":{\\\"experiments\\\":[{\\\"action\\\":\\\"fullload\\\",\\\"desc\\\":\\\"increase node cpu load by names\\\",\\\"matchers\\\":[{\\\"name\\\":\\\"names\\\",\\\"value\\\":[\\\"blade-2\\\"]},{\\\"name\\\":\\\"cpu-percent\\\",\\\"value\\\":[\\\"80\\\"]}],\\\"scope\\\":\\\"node\\\",\\\"target\\\":\\\"cpu\\\"}]}}\\n\"}, \"namespace\":\"\", \"clusterName\":\"\", \"finalizers\":[]interface {}{\"finalizer.chaosblade.io\"}, \"selfLink\":\"/apis/chaosblade.io/v1alpha1/chaosblades/cpu-load\", \"resourceVersion\":\"120987\", \"generation\":1, \"name\":\"cpu-load\", \"uid\":\"22994c61-1711-11ea-9d28-0242ac120003\"}, \"spec\":map[string]interface {}{\"experiments\":[]interface {}{map[string]interface {}{\"matchers\":[]interface {}{map[string]interface {}{\"value\":[]interface {}{\"blade-2\"}, \"name\":\"names\"}, map[string]interface {}{\"name\":\"cpu-percent\", \"value\":[]interface {}{\"80\"}}}, \"scope\":\"node\", \"target\":\"cpu\", \"action\":\"fullload\", \"desc\":\"increase node cpu load by names\"}}}, \"status\":map[string]interface {}{\"expStatuses\":interface {}(nil)}}: validation failure list:\nstatus.expStatuses in body must be of type array: \"null\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tchaosblade-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tchaosblade-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\tchaosblade-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tchaosblade-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tchaosblade-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\nk8s.io/apimachinery/pkg/util/wait.Until\n\tchaosblade-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}

[root@blade-1 chaosblade-0.4.0]# ./blade create k8s node-cpu fullload --name blade-2 --cpu-percent 80 --kubeconfig ~/.kube/config
unknown flag: --name

[root@blade-1 chaosblade-0.4.0]# ./blade create k8s node-cpu fullload blade-2 --cpu-percent 80 --kubeconfig ~/.kube/config
{"code":800,"success":false,"error":"chaosblades.chaosblade.io \"5743fa3974eecd76\" not found","result":{"uid":"5743fa3974eecd76","success":false,"error":"chaosblades.chaosblade.io \"5743fa3974eecd76\" not found","statuses":[{"id":"5743fa3974eecd76","state":"Error","kind":"","error":"chaosblades.chaosblade.io \"5743fa3974eecd76\" not found","success":false}]}}

### Tell us your environment
[root@blade-1 ~]# docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false

Kubernetes v1.10.11

[root@blade-1 chaosblade-0.4.0]# kubectl get pod -n kube-system -o wide | grep chaosblade
chaosblade-operator-779d8c7d8-cgbv5        1/1       Running   0          5h        172.28.36.7    blade-2

**Comment by xcaspar** [comment]
@WillYan881118 `--name` is wrong, please use `--names`.

**Comment by xcaspar** [comment]
@WillYan881118 https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/blade-create-k8s-node-cpu

**Comment by WillYan881118** [comment]
[root@blade-1 chaosblade-0.4.0]# ./blade create k8s node-cpu fullload --names blade-2 --cpu-percent 80 --kubeconfig ~/.kube/config
{"code":800,"success":false,"error":"chaosblades.chaosblade.io \"245c2d8ca9ee5bc1\" not found","result":{"uid":"245c2d8ca9ee5bc1","success":false,"error":"chaosblades.chaosblade.io \"245c2d8ca9ee5bc1\" not found","statuses":[{"id":"245c2d8ca9ee5bc1","state":"Error","kind":"","error":"chaosblades.chaosblade.io \"245c2d8ca9ee5bc1\" not found","success":false}]}}
[root@blade-1 chaosblade-0.4.0]# kubectl get nodes
NAME      STATUS    ROLES                  AGE       VERSION
blade-1   Ready     dcei,master,registry   23h       v1.10.11
blade-2   Ready     <none>                 23h       v1.10.11
[root@blade-1 chaosblade-0.4.0]# kubectl get pod -n kube-system -o wide | grep chaosblade
chaosblade-operator-779d8c7d8-cgbv5        1/1       Running   0          5h        172.28.36.7    blade-2

**Comment by xcaspar** [comment]
The cause of the problem is the chaosblade crd has been deleted, please reinstall chaosblade-operator. The commands as follows:
```
kubectl delete crd chaosblades.chaosblade.io
helm del --purge chaosblade-operator
helm install --namespace kube-system --name chaosblade-operator chaosblade-operator-0.4.0.tgz 
```

**Comment by WillYan881118** [comment]
which verion of helm chaosblade request,   mine helm version is "v3.0.0", 
when I try to command :helm install --namespace kube-system --name chaosblade-operator chaosblade-operator-0.4.0.tgz 
Error: unknown flag: --name
is this means chaosblades  don't support helm 3

**Comment by xcaspar** [comment]
@WillYan881118 Please use `helm install --namespace kube-system chaosblade-operator chaosblade-operator-0.4.0.tgz` command to retry.

**Comment by xcaspar** [comment]
@WillYan881118 I will test it later in the helm v3 environment.

**Comment by WillYan881118** [comment]
I tryed in helm v3 env,
helm install --namespace kube-system chaosblade-operator chaosblade-operator-0.4.0.tgz
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
NAME: chaosblade-operator
LAST DEPLOYED: Thu Dec  5 17:51:43 2019
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for using chaosblade.
container logs:
20003_2{"level":"error","ts":1575539550.079153,"logger":"cmd","msg":"","error":"no matches for kind \"ChaosBlade\" in version \"chaosblade.io/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tchaosblade-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\tchaosblade-operator/cmd/manager/main.go:129\nruntime.main\n\t/usr/local/Cellar/go/1.13/libexec/src/runtime/proc.go:203"}

later, I will try in helm v2,
 thx.

**Comment by WillYan881118** [comment]
uesing helmv2 to install  chaosblade-operator-0.4.0.tgz,   Container always restart ,
here is logs:
{"level":"error","ts":1575598903.4904566,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"ChaosBlade.chaosblade.io","error":"no matches for kind \"ChaosBlade\" in version \"chaosblade.io/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tchaosblade-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\tchaosblade-operator/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:89\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\tchaosblade-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122\ngithub.com/chaosblade-io/chaosblade-operator/pkg/controller/chaosblade.add\n\tchaosblade-operator/pkg/controller/chaosblade/controller.go:75\ngithub.com/chaosblade-io/chaosblade-operator/pkg/controller/chaosblade.Add\n\tchaosblade-operator/pkg/controller/chaosblade/controller.go:52\ngithub.com/chaosblade-io/chaosblade-operator/pkg/controller.AddToManager\n\tchaosblade-operator/pkg/controller/controller.go:29\nmain.main\n\tchaosblade-operator/cmd/manager/main.go:128\nruntime.main\n\t/usr/local/Cellar/go/1.13/libexec/src/runtime/proc.go:203"}

2019-12-06 10:21:43k8s_chaosblade-operator_chaosblade-operator-7c9cd67889-8mbtd_kube-system_a0f30b40-17cd-11ea-9d28-0242ac120003_7{"level":"error","ts":1575598903.4907808,"logger":"cmd","msg":"","error":"no matches for kind \"ChaosBlade\" in version \"chaosblade.io/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tchaosblade-operator/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\tchaosblade-operator/cmd/manager/main.go:129\nruntime.main\n\t/usr/local/Cellar/go/1.13/libexec/src/runtime/proc.go:203"}
after i helm the 0.4.0, i have not found chaosblade crd

**Comment by xcaspar** [comment]
@WillYan881118 Because the chaosblade crd has been deleted, you can execute the following commands to reinstall:
1. `helm delete --purge chaosblade-operator`
2. `helm install --set blade.pullPolicy=Always --namespace kube-system --name chaosblade-operator chaosblade-operator-0.4.0.tgz `

**Comment by WillYan881118** [comment]
before i install 0.4.0,I have already execute    ` helm delete --purge chaosblade-operator`,
it's not working,
in version 0.0.1, after I helm install ,
```
[root@blade-1 ~]# kubectl get crd| grep chaos
chaosblades.chaosblade.io   53s
```
in version 0.4.0,
![image](https://user-images.githubusercontent.com/16386486/70303067-9af26200-1839-11ea-88a5-6e61cf5d414a.png)

**Comment by xcaspar** [comment]
@WillYan881118 Although chaosblade crd exists, it has been identified as deleted and is therefore unavailable. You can refer to the following commands to try to solve:

1. Use `helm install --set blade.pullPolicy=Always --namespace kube-system --name chaosblade-operator chaosblade-operator-0.4.0.tgz --no-crd-hook` to install chaosblade-operator
2. Re-execute the `kubectl delete crd chaosblades.chaosblade.io` command to delete chaosblade crd.
3. Wait for the return. If it has not finished in more than 5 minutes, use `kubectl get blade -o json` to view the specific experimental information. You can also send the results to me (x.caspar@gmail.com)
4. If delete crd is successful, execute `helm delete --purge chaosblade-operator` to delete chaosblade-operator.
5. Execute `helm install --namespace kube-system --name chaosblade-operator chaosblade-operator-0.4.0.tgz` to reinstall chaosblade operator.

**Comment by xcaspar** [comment]
@WillYan881118 Helm v3 issue: https://github.com/chaosblade-io/chaosblade/issues/264
