### ISSUE TITLE
can't delete chaosblades.chaosblade.io

### ISSUE THREAD

**Issue by AnyuanLuo** [chaosblade-io/chaosblade#259]
## Issue Description
bug

### Describe what happened (or what feature you want)
I installed chaosblade 0.4.0 alpha one month ago, I find can't delete chaosblades.chaosblade.io when I want install chaosblade 0.4.0  today, I delete about three hours, but it just hold deleting status, not really deleted.
![image](https://user-images.githubusercontent.com/44501518/70234505-c161c000-179b-11ea-8437-d31cbe240802.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
@AnyuanLuo Please provider results of the flowing commands:
1. `kubectl get pod -n kube-system | grep chaosblade`
2. `kubectl get blade`

**Comment by AnyuanLuo** [comment]
![image](https://user-images.githubusercontent.com/44501518/70235886-d12ed380-179e-11ea-8a77-f5b6068b74af.png)


![image](https://user-images.githubusercontent.com/44501518/70235933-e3107680-179e-11ea-8422-1f0be6c283d1.png)

**Comment by xcaspar** [comment]
Did you execute `helm delete` first, then execute `kubectl delete crd chaosblades.chaosblade.io`?

**Comment by AnyuanLuo** [comment]
yes, I execute `helm delete` first, and then it suggest me to execute `kubectl delete crd chaosblades.chaosblade.io`

**Comment by xcaspar** [comment]
You can try the following command to reinstall:
1. Use `helm install --set blade.pullPolicy=Always --namespace kube-system --name chaosblade-operator chaosblade-operator-0.4.0.tgz --no-crd-hook` to install chaosblade-operator
2. Re-execute the `kubectl delete crd chaosblades.chaosblade.io` command to delete chaosblade crd.
3. Wait for the return. If it has not finished in more than 5 minutes, use `kubectl get blade -o json` to view the specific experimental information. You can also send the results to me (x.caspar@gmail.com)
4. If delete crd is successful, execute `helm delete --purge chaosblade-operator` to delete chaosblade-operator.
5. Execute `helm install --namespace kube-system --name chaosblade-operator chaosblade-operator-0.4.0.tgz` to re-install chaosblade operator.

**Comment by AnyuanLuo** [comment]
Sincerely thank you，I'll have a try.
