### ISSUE TITLE
./blade: cannot execute binary file

### ISSUE THREAD

**Issue by nannan1204** [chaosblade-io/chaosblade#261]
## Issue Description

Type: *bug report* or *feature request*
**Linux OS:** lsb_release -a
LSB Version:    :core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.3 (Final)
Release:        6.3
Codename:       Final

**Blade Version:** chaosblade-0.3.0 / chaosblade-0.4.0

run ./blade create -h
bash: ./blade: cannot execute binary file

**Comment by xcaspar** [comment]
@nannan1204 Which package did you download?

**Comment by nannan1204** [comment]
I am sorry, I did use a wrong package(chaosblade-0.4.0-darwin) on linux os.
There is no problem now.
