### ISSUE TITLE
[Ask a Question]How to copy the chaosblade tools to the container in k8s?

### ISSUE THREAD

**Issue by nkguoym** [chaosblade-io/chaosblade#276]
## Issue Description

> “重点是，对运行中的容器（业务容器，没有 chaosblade 工具）如何做。”

> 请问你是怎么把故障注入到容器中的呢？ 很多业务模块没有golang环境， 你是怎么让你构建故障的脚本在容器中生效的呢？

> 目前基础资源的故障程序不需要 golang 的环境，直接将工具 copy 到目标容器内执行。

I see this comment in the previous issues, I wonder how did you do this? Did you put the chaosblade tools, such as burncpu to the container when the container startup, this means the tools build with your business service together? or you can dynamic copy these tools to the container? 

I am very interesting with chaos engineering project, thanks in advance for your support.

**Comment by xcaspar** [comment]
Dynamic copy chaosblade tools to the running container. You can see the code file: https://github.com/chaosblade-io/chaosblade-exec-docker/blob/master/exec/executor_execin.go

**Comment by nkguoym** [comment]
Thanks for your response. I wonder whether the k8s scenario also use this? sorry, I am not very familiar with k8s.

**Comment by xcaspar** [comment]
Yes, k8s container experiments using the way, such as cpu, process experiments.

**Comment by nkguoym** [comment]
But I didn't see there is something like CopyToContainer for k8s experiments, do you mean k8s experiment also use https://github.com/chaosblade-io/chaosblade-exec-docker/blob/master/exec/executor_execin.go ?

**Comment by xcaspar** [comment]
Invoke `blade create docker` command for k8s container experiments. You can see https://github.com/chaosblade-io/chaosblade-operator/blob/master/exec/container/executor.go code file.

**Comment by nkguoym** [comment]
Thank you very much for your kindly support.
