### ISSUE TITLE
chaosblade-0.4.0 not support aarch64

### ISSUE THREAD

**Issue by jelly-ma** [chaosblade-io/chaosblade#282]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
got CrashLoopBackOff status on chaosblade-tool pods which based on aarch64

chaosblade-tool pod logs：standard_init_linux.go:211: exec user process caused "exec format error"

### Describe what you expected to happen
chaosblade-tool pods' status are Running

### How to reproduce it (as minimally and precisely as possible)

1. you have several  aarch64 arch serve as k8s nodes
2. helm install --namespace kube-system --name chaosblade-operator chaosblade-operator-0.4.0.tgz
3. 

### Tell us your environment
chaosblade-0.4.0-linux-amd64.tar.gz
chaosblade-operator-0.4.0.tgz

### Anything else we need to know?
got Running status on chaosblade-tool pods which based on X86

**Comment by xcaspar** [comment]
@jelly-ma You can rebuild the image on the aarch64 machine to solve the problem.

**Comment by xcaspar** [comment]
I will close this issue first. If there is any problem, you can open it again.
