### ISSUE TITLE
chaosblade prepare jvm prepare with javaHome flags returns "java command not found"

### ISSUE THREAD

**Issue by zousheng** [chaosblade-io/chaosblade#286]
## Issue Description

Type: *bug report* or *feature request*
          bug report
### Describe what happened (or what feature you want)
     when I called prepare api with javaHome flag (host:9526/chaosblade?cmd=prepare%20jvm%20--javaHome=/home/q/java/default%20--process=pf_noah_webapp%), it returned "java command not found" error
     
  {"code":604,"success":false,"error":"sudo: java: command not found\n exit status 1","result":"426204ac84dc27a3"}
### Describe what you expected to happen

   success: true
### How to reproduce it (as minimally and precisely as possible)

1. start java application with non-root user 
2. start blade server mode with sudo
3. call the prepare api and pass javaHome flag

### Tell us your environment

   centos7

**Comment by xcaspar** [comment]
@zousheng Thank you for reporting and fixing it.
