### ISSUE TITLE
Error "too many process" returned when running ./blade prepare jvm --javaHome /home/name/java/default

### ISSUE THREAD

**Issue by zousheng** [chaosblade-io/chaosblade#288]
## Issue Description

Type: *bug report* or *feature request*
           *bug report*
### Describe what happened (or what feature you want)

      when I run ./blade prepare jvm --javaHome /home/name/java/default --process pf_noah_webapp, 
it returned too many process
### Describe what you expected to happen

 {"code":200,"success":true,"result":"537cd831b5e7c613"}
### How to reproduce it (as minimally and precisely as possible)

1. run command sudo ./blade prepare jvm --javaHome /home/name/java/default --process process_name (the javaHome flag is a must, and its value  should contain java in the path )

### Tell us your environment

  centos7
### Anything else we need to know?
 during the debug, found 2 pids, one is our java application, the other is the command we run " ./blade prepare jvm --javaHome /home/name/java/default --process process_name"

**Comment by zousheng** [comment]
I will submit a pr later

**Comment by xcaspar** [comment]
@zousheng Thank you for reporting and fixing it.
