### ISSUE TITLE
compile source code error by make build_linux 

### ISSUE THREAD

**Issue by yixy** [chaosblade-io/chaosblade#298]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)

There are some errors when using `make build_linux` to compile the source code:

1. cannot compile `chaosblade-operator` in docker.
2. `mvn` command not found in docker, because of `M2_HOME` and `PATH` variable not setting in [Dockfile](https://github.com/chaosblade-io/chaosblade/blob/eae5c34e40615446472347399742f65af5b723e2/build/image/musl/Dockerfile#L25).

### Describe what you expected to happen

make build_linux compiles correctly

### Tell us your environment

```
root@instance-1:/myworkspace/src/github.com/chaosblade-io/chaosblade# uname -a
Linux instance-1 4.15.0-1052-gcp #56-Ubuntu SMP Thu Dec 19 10:54:56 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by xcaspar** [comment]
@yixy I have fixed it, please pull the master branch and compile.

**Comment by yixy** [comment]
@xcaspar It works, THX :)
