### ISSUE TITLE
when i blade prepare jvm --process business, it return 604, why?

### ISSUE THREAD

**Issue by MatrixWeb** [chaosblade-io/chaosblade#30]
## Issue Description

when i blade prepare jvm --process business, it return 604, why?
{"code":604,"success":false,"error":"Error: Unable to access jarfile /root/lib/sandbox/lib/sandbox-core.jar\n exit status 1"}

**Comment by xcaspar** [comment]
> ## Issue Description
> when i blade prepare jvm --process business, it return 604, why?
> {"code":604,"success":false,"error":"Error: Unable to access jarfile /root/lib/sandbox/lib/sandbox-core.jar\n exit status 1"}

Please try to use the absolute path of the `blade` file or execute it in the directory where the `blade` file is located.
