### ISSUE TITLE
chaosblade do test on redis.

### ISSUE THREAD

**Issue by SparkandScala** [chaosblade-io/chaosblade#300]
1. i want to do some test on redis cluster of my server,  can the chaosblade do that? 
2. if it can do it, how can i execute it.

thank you!!

**Comment by xcaspar** [comment]
@SparkandScala You must deploy the chaosblade tool on every machine in the redis cluster, and you can execute network, cpu, process experiments to do test.

**Comment by SparkandScala** [comment]
> @SparkandScala You must deploy the chaosblade tool on every machine in the redis cluster, and you can execute network, cpu, process experiments to do test.

got it, thank you!!
