### ISSUE TITLE
Chaosblade create JVM throwcustomexception does not support spaces

### ISSUE THREAD

**Issue by lizhen1412** [chaosblade-io/chaosblade#304]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
Currently, chaosblade does not support injecting exception messages with spaces

### Describe what you expected to happen
1.Support space transmission or splicing
2.Support multi exception message discrimination

Reference command:
./blade c jvm throwCustomException --exception org.apache.hadoop.hbase.client.RetriesExhaustedException --classname org.apache.hadoop.hbase.client.HTable --methodname put p 1491 --exception-message "servers with issues" || --exception-message "location"  --effect-count 20

### How to reproduce it (as minimally and precisely as possible)
According to the official documents, spaces are not supported at present
Official documents are as follows:
https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/blade-create-jvm/blade-create-jvm-throwcustomexception
![image](https://user-images.githubusercontent.com/29331541/74601326-ddf17100-50d7-11ea-90f6-c8f1a1d4b900.png)

### Tell us your environment
All environment

### Anything else we need to know?
nothing

**Comment by xcaspar** [comment]
@lizhen1412 0.5.0 version already supports this message parameter containing blank spaces.
