### ISSUE TITLE
Cannot destroy the experiment if it was kept alive for a long time.

### ISSUE THREAD

**Issue by jenson93** [chaosblade-io/chaosblade#305]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
I created an experiment, such as node-kill-process-by-name, container-network-loss, it succeeded.
However, if I forgot to destroy it and kept it alive for a long time, such as 15h+, I cannot delete it when I want to destroy the experiment.

### Tell us your environment
1. ubuntu 18.06-ce
2. k8s v1.5.12
3. docker v18.06
### Anything else we need to know?
I can see the parameter 'timeout' as to 'container network loss', and it can be used to avoid the above problem. However, Not all experiments include 'timeout'.
Finally, 
```
kubectl edit blade xxx
```
by removing 'finalizers', I resolved the problem
### What I expect?
The way to force to delete is not good enough, whether can add the function by use a parameter in the future?

**Comment by xcaspar** [comment]
@jenson93 Thank you for reporting the issue. Even if the experiment was created for a long time, it also should be deleted. We must find out the reason why it cannot be deleted. If you encounter this situation again, can you provide detailed experimental information used `kubectl get blade xxxx` to get？

>“The way to force to delete is not good enough, whether can add the function by use a parameter in the future?“

This is a good suggestion, and we will add it into the development plan. Thank you again.

**Comment by jenson93** [comment]
@xcaspar I'm very sad that I met the problem again. When I went through the detail by using `kubectl get blade xxx`, I found that `phase` was always 'Destroying':
```
 "expStatuses": [
                .....
                "scope": "node",
                "state": "Error",
                "success": false,
                "target": "process"
            }
        ],
        "phase": "Destroying"
    }
```
Next， I  tried to delete the experiment by `kubectl delete blade node-stop-process-test01 -v 6`, the detail as follows:
```
I0224 16:19:43.766822   19571 loader.go:359] Config loaded from file:  /home/jenson/.kube/config
I0224 16:19:43.785879   19571 round_trippers.go:438] DELETE https://10.0.2.4:6443/apis/chaosblade.io/v1alpha1/chaosblades/node-stop-process-test01 200 OK in 11 milliseconds
chaosblade.chaosblade.io "node-stop-process-test01" deleted
I0224 16:19:43.790570   19571 round_trippers.go:438] GET https://10.0.2.4:6443/apis/chaosblade.io/v1alpha1/chaosblades?fieldSelector=metadata.name%3Dnode-stop-process-test01 200 OK in 4 milliseconds
I0224 16:19:43.791651   19571 round_trippers.go:438] GET https://10.0.2.4:6443/apis/chaosblade.io/v1alpha1/chaosblades?fieldSelector=metadata.name%3Dnode-stop-process-test01&resourceVersion=86524&watch=true 200 OK in 0 milliseconds
```
It seems that `Informer` watch resources failed and  was stuck in call-back?

**Comment by jenson93** [comment]
Also we can see, `--timeout` just means that, once the time is exceeded, the effect will be invalid. However, the experiment still remains unless we delete it manually. So, we must find the the solution to solve the problem.

**Comment by xcaspar** [comment]
@jenson93 
Q：”I'm very sad that I met the problem again. What's more, the experiment was just created half an hour ago. When I went through the detail by using kubectl get blade xxx, I found that phase was always 'Destroying'”
A：What commands have been executed for this experiment or chaosblade resources before the `kubectl get blade xxx command`

**Comment by xcaspar** [comment]
> Also we can see, `--timeout` just means that, once the time is exceeded, the effect will be invalid. However, the experiment still remains unless we delete it manually. I think the above problem has nothing to do with the time, so we must find the the solution to solve the problem.

Yes! `timeout` is currently only valid for experiments created by the blade command. Did you use `blade create k8s xxx` command to execute experiments?

**Comment by xcaspar** [comment]
Please use the latest release version(v0.6.0). You can destroy the  experiment with `--force-remove` flag.
