### ISSUE TITLE
Got a non-json relpy from blade server, seems not convenient to serialize.

### ISSUE THREAD

**Issue by h404z** [chaosblade-io/chaosblade#316]
## Issue Description
the reply is not json type as other blade server replies, so it's not convenient for user to handle

Type: *bug report* or *feature request*
it should be a bug report i think

### Describe what happened (or what feature you want)
this is my request `http://{{host}}:{{port}}/chaosblade?cmd=status`
and i got this as reply `{"code":603,"success":false,"error":"must specify the right type or uid"}
 exit status 1`
### Describe what you expected to happen
`exit status 1` should not be shown

### Tell us your environment
centos7

**Comment by ycwdaaaa** [comment]
我同样遇到了这个问题，我再使用blade server的时候， 尝试使用destroy来销毁实验。但是得到下面的信息：
{"code":200,"success":true,"result":""}
 exit status 1

json中的内容应该是调用成功了， 但是实际上实验没有销毁， 遇到错了应该。  
url：http://172.27.128.190:9526/chaosblade?cmd=destroy%20network%20delay%20--interface%20vethfd53142

**Comment by xcaspar** [comment]
@h404z I'll optimize this issue as soon as possible.
