### ISSUE TITLE
How to execute commands in kubernetes pod?

### ISSUE THREAD

**Issue by linydquantil** [chaosblade-io/chaosblade#317]
RT

I use supervisor to manage our process in kubernetes pod.  I need to execute a command like this（supervisorctl stop xxx） to stop our program.

**Comment by JackeyThmons** [comment]
you can use kubernetes api  ,https://github.com/kubernetes-client
for example, python client ,
https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/CoreV1Api.md#connect_get_namespaced_pod_exec

**Comment by xcaspar** [comment]
@linydquantil You can see https://github.com/chaosblade-io/chaosblade-operator/blob/master/channel/client.go#L72 for the details.
