### ISSUE TITLE
In a container environment, the image may not have a "ps" command (such as the amazoncorretto image), so I cannot use commands such as "blade create docker process kill" for chaos testing

### ISSUE THREAD

**Issue by x22x22** [chaosblade-io/chaosblade#319]
## Issue Description

Type: *bug report* 

### Describe what happened

In a container environment, the image may not have a "ps" command (such as the amazoncorretto image), so I cannot use commands such as "blade create docker process kill" for chaos testing

### Solution

I recommend introducing https://github.com/directly/mitchellh/go-ps or https://github.com/shirou/gopsutil to solve this problem, if you agree, I can contribute code, thank you

**Comment by xcaspar** [comment]
@x22x22 The current execution method of the killing process is to copy the chaosblade toolkit to the container for execution, so it is strongly dependent on commands such as ps.
We can use the sidecar mode to run a container containing the chaosblade tool, reuse the pid namespace of the target container, and kill processes in the target container by the sidecar container, Similar to network scenarios.

**Comment by x22x22** [comment]
@xcaspar 
I have looked at the source code before asking the question, and I know why this problem occurs. I mainly want to discuss the solution, I want to use "go-ps" or "gopsutil" to solve this problem, because they are directly calling the system's api to obtain the process Information. I wonder if you think it is feasible?

**Comment by xcaspar** [comment]
@x22x22 That is also a good solution, I think there is no problem. I assign the issue to you, thank you.
