### ISSUE TITLE
Is there a way to completely delete the created environment.

### ISSUE THREAD

**Issue by No-sleeping** [chaosblade-io/chaosblade#320]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

When I enter "./blade status --type c", I will see all the created or destroyed environments, and there will be many environments over time.

### Describe what you expected to happen
Is there any way to clear the environment inside, it is also more convenient to find.

### How to reproduce it (as minimally and precisely as possible)

1.    enter   "./blade status --type c"
2. 
3. 

### Tell us your environment
 Debian 4.19.28-2kali1  x86_64 GNU/Linux

**Comment by xcaspar** [comment]
@No-sleeping There is currently no delete command, if you want delete the records, you can delete the chaosblade.dat file after stopping all experiments.

**Comment by No-sleeping** [comment]
thanks a lot

**Comment by xcaspar** [comment]
@No-sleeping You can add `--force-remove` flag to delete the experiment since v0.8.0.
