### ISSUE TITLE
cannot destroy experiment by blade server

### ISSUE THREAD

**Issue by ycwdaaaa** [chaosblade-io/chaosblade#321]
I can destroy by command line but when try to use blade server, it return this:
{"code":200,"success":true,"result":""}
 exit status 1

url: http://172.27.128.190:9526/chaosblade?cmd=destroy%20network%20loss%20--interface%20vethfd53142

version: chaosblade-0.5.0-linux-amd64.tar.gz
os version:Linux m7-prod-ssd001 4.4.166-1.el7.elrepo.x86_64 #1 SMP Sat Dec 1 10:48:24 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by xcaspar** [comment]
#316

**Comment by xcaspar** [comment]
@ycwdaaaa Can you provide the create command?

**Comment by ycwdaaaa** [comment]
@xcaspar
http://172.27.128.190:9526/chaosblade?cmd=create%20network%20delay%20%20--interface%20vethfd53142%20--local-port%201111%20--timeout%2060%20--time%203000

**Comment by xcaspar** [comment]
@ycwdaaaa Yes, it's a bug. I'll fix it as soon as possible.
