### ISSUE TITLE
Develop chaos engineering platform based on chaosblade

### ISSUE THREAD

**Issue by xcaspar** [chaosblade-io/chaosblade#353]
Currently, there are two common execution methods for ChaosBlade: cli and http. You need to manually fill in the parameters and send commands to the specified machine for execution, for specific usage methods, see [usage documents] ( https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/ ).

The current problems are:
1. Users must understand the commands and command parameters related to chaosblade.
2. The user must login to the machine or execute instructions through the command channel.
3. Lack of drill record summary, inconvenient for auditing

This topic is intended to provide a chaos engineering experiment console. You can use this console to inject faults into the target machine or cluster where chaosblade is deployed. The features are as follows:
1. All fault scenarios of chaosblade can be displayed on the console, and fault scenarios can be filtered according to scenario categories;
2. The scene parameters in chaosblade can be displayed in the console. You can configure the parameter values;
3. You can specify the target machine or cluster to perform fault injection through the chaosblade tool;
4. The database stores user execution records and scenario parameters

Related issue: #352

**Comment by rpjayasekara** [comment]
I found project Chaosblade project really interesting and I am looking forward to work on this issue during the ASoC 2020. I have gone through the Chaosblade documentation and got a high-level idea of what kind of functions and experiments Chaosblade offers. As long as I have understood about this issue, I think it's to develop a GUI to execute Chaosblade functionalities and view usage history. (Correct me if I am wrong.) This project will take proper planning and discussions so, Is there any community platform/mailing list where we can discuss it further?

**Comment by xcaspar** [comment]
@rpjayasekara Welcome. We have created a slack group where we can discuss it.
slack address: https://join.slack.com/t/chaosblade-io/shared_invite/zt-f0d3r3f4-TDK13Wr3QRUrAhems28p1w

**Comment by rpjayasekara** [comment]
Will ASoC have in this year? @xcaspar

**Comment by orangle** [comment]
@rpjayasekara  this project https://github.com/chaosblade-io/chaosblade-box
