### ISSUE TITLE
Error, build_with_linux on the macos

### ISSUE THREAD

**Issue by DLive** [chaosblade-io/chaosblade#359]
## Issue Description
When I compiled with build_with_linux in macos, It reported an error of "make no target build_with"
Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. git checkout master branch
2. Run with " ARGS="cli os java" make build_with_linux"
3. 

### Tell us your environment
macos 10.15.4
Make 3.81

**Comment by xcaspar** [comment]
#341 
#338
