### ISSUE TITLE
Golang, php language interface support

### ISSUE THREAD

**Issue by superfang01** [chaosblade-io/chaosblade#36]
希望支持 php,golang语言的接口的超时，延时测试，这样会更加有实用性的。 

test_fang@163.com 

## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
We have a plan to support golang. To track this issue #70 , I will close this issue first. If you have any questions, you can reopen it.
