### ISSUE TITLE
exclude-ip is invalid 

### ISSUE THREAD

**Issue by zhyErick** [chaosblade-io/chaosblade#363]
## Issue Description

Type: *bug report* or *feature request*

### Describe what you expected to happen

./blade create network loss --interface eth0 --percent 100 --destination-ip 10.0.0.0/24 --exclude-ip 10.0.0.10
but I can't access 10.0.0.10
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

centos 7.6

**Comment by xcaspar** [comment]
The priority of `destination-ip` is greater than `exclude-ip`. But your chaos experiment is also correct, so we will fix it in next version.

**Comment by xcaspar** [comment]
@zhyErick Of course, you can also submit a pr to fix this problem.

**Comment by tiny-x** [comment]
fix: https://github.com/chaosblade-io/chaosblade-exec-os/pull/41
