### ISSUE TITLE
prepare jvm  doesn't  spourt  openJDK

### ISSUE THREAD

**Issue by Captionofcody** [chaosblade-io/chaosblade#367]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
Please append `-j <JAVA_HOME>` flag to`blade prepare jvm` command to specify the JAVA_HOME path, such as -j /usr/local/java.

**Comment by Captionofcody** [comment]
it works
