### ISSUE TITLE
how to create http experiment    correctly

### ISSUE THREAD

**Issue by Captionofcody** [chaosblade-io/chaosblade#373]
## Issue Description
when  i excute  
./blade create http delay --time 20000 --uri  http://192.168.1.100:8080/chinabond-dcms-service/healthcheck.html --process 13311 
it return  sucess

but  accessing  "http://192.168.1.100:8080/chinabond-dcms-service/healthcheck.html" through browser ,there is no time delay .

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
@Captionofcody Please add `--debug` flag and check logs/chaosblade/chaosblade.log in the user directory of the application process.

**Comment by xcaspar** [comment]
Please see the ~/logs/chaosblade/chaosblade.log, not chaosblade/logs/chaosblade.log.
