### ISSUE TITLE
blade destroy fail，It can't be solved by following the prompts

### ISSUE THREAD

**Issue by dawzhang** [chaosblade-io/chaosblade#376]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
[root@no ~]# blade status --type create --status Success
{
 "code": 200,
 "success": true,
 "result": [
  {
   "Uid": "ea0316ad31711f3b",
   "Command": "jvm",
   "SubCommand": "throwCustomException",
   "Flag": " --methodname=getBodyData --classname=com.itesttech.mock.util.HttpRequestUtil --effect-count=2 --exception=java.lang.Exception --process=32115",
   "Status": "Success",
   "Error": "",
   "CreateTime": "2020-05-21T09:49:36.021089165+08:00",
   "UpdateTime": "2020-05-21T09:49:36.189142991+08:00"
  }
 ]
}
[root@no ~]# blade destroy ea0316ad31711f3b
{"code":500,"success":false,"error":"cannot get port from local, please execute prepare command first"}
[root@no ~]# blade prepare jvm --pid 32115
{"code":602,"success":false,"error":"the 32115 process id doesn't exist."}
[root@no ~]# 

expect：blade destroy success，exp status change to Destroyed。

### Tell us your environment
Linux centos7.5

**Comment by xcaspar** [comment]
We also need to determine whether the process exists to decide whether the destroy is successful.
