### ISSUE TITLE
ChaosBlade Operator 实验场景汇总

### ISSUE THREAD

**Issue by sunny0826** [chaosblade-io/chaosblade#378]
地址：https://github.com/sunny0826/chaosblade-operator-experiment

**Comment by quanwenqi2** [comment]
作为一个测试人员，思想上比较功利，我想了解通过注入如上故障都能发现什么有价值都问题呢？

**Comment by sunny0826** [comment]
> 作为一个测试人员，思想上比较功利，我想了解通过注入如上故障都能发现了什么有价值的问题呢？

https://github.com/chaosblade-io/awesome-chaosblade 
这里有一些文章和视频，是穹谷 @xcaspar 分享和整理的内容，希望对你有帮助
