### ISSUE TITLE
how to stop all experiment?

### ISSUE THREAD

**Issue by chjh0612** [chaosblade-io/chaosblade#384]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
Not supported. You can do it in the following ways:

Query all `Success` experiments and destory. Please replace `/root/chaosblade-0.6.0/blade` path.
```
blades=($(./blade s --type c --status Success | jq -r '.result[].Uid')) && for e in ${blades[@]};do sudo /root/chaosblade-0.6.0/blade d $e;done
```

**Comment by chjh0612** [comment]
@xcaspar thanks a lot
