### ISSUE TITLE
Network latency scenarios cannot be destroyed

### ISSUE THREAD

**Issue by niuxiaojie81** [chaosblade-io/chaosblade#385]
使用0.6.0版本，创建网络延迟场景后生效，destroy uid后，显示成功，但延迟仍然作用在网卡和端口上

**Comment by xcaspar** [comment]
Please use sudo command to execute `blade destroy`. You can execute the following command to destroy:
```
sudo blade destroy network delay --interface XXX
```

**Comment by niuxiaojie81** [comment]
> destroy network delay --interface XXX

It works. Thank you!!!
