### ISSUE TITLE
how to stop chaosblade and sandbox process?

### ISSUE THREAD

**Issue by chjh0612** [chaosblade-io/chaosblade#388]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by Swarag-N** [comment]
you can see the experiments running by `blade s -h`
and than you destroy by `blade d id`
![image](https://user-images.githubusercontent.com/46181010/87963215-fd048c80-cad5-11ea-988c-8df0a09d5e3b.png)

if you are experimenting with chaos blade, To sandbox you can use docker image.
