### ISSUE TITLE
update the pictures in README

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaosblade-io/chaosblade#390]
## Issue Description

The README uses English as default, but the picture contains Chinese. 

https://user-images.githubusercontent.com/3992234/72410783-429d7100-37a4-11ea-8314-540560f8a54f.png
https://user-images.githubusercontent.com/3992234/72340872-eb47c400-3703-11ea-830f-062e117c2e95.png

### Describe what you expected to happen

translate Chinese to English in these two pictures.

**Comment by xcaspar** [comment]
We will update the readme content as soon as possible.
