### ISSUE TITLE
ifconfig is deprecated, but network delay still depend on it

### ISSUE THREAD

**Issue by carolwu-1206** [chaosblade-io/chaosblade#396]
## Issue Description

When running network delay, it calls ifconfig. However, ifconfig has been daprecated on many Linux OS. 

```
# ./blade create network delay --timeout=10 --interface=lo --local-port=8090 --time=1000
{"code":503,"success":false,"error":"ifconfig command not found"}
```
### Describe what you expected to happen
network delay can run without ifconfig

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by tiny-x** [comment]
https://github.com/chaosblade-io/chaosblade-exec-os/pull/56
