### ISSUE TITLE
blade os process stop didn't work as expect

### ISSUE THREAD

**Issue by stutiredboy** [chaosblade-io/chaosblade#398]
## Issue Description

*bug report*

### Describe what happened (or what feature you want)

1. start a stop process experiment:

```
$ ./blade create process stop --process get_cpus
{"code":200,"success":true,"result":"8280640d9b9368eb"}
```
2. try to destroy it

```
$ ./blade -d destroy 8280640d9b9368eb
{"code":604,"success":false,"error":"'get_cpus' process not found exit status 1"}
```

### Describe what you expected to happen

the process been stopped can not be waken

### How to reproduce it (as minimally and precisely as possible)

as above

### Tell us your environment

Debian Linux

### Anything else we need to know?

while calling `./blade create process stop --process get_cpus`, the process is `get_cpus`, but when try to destroy it, the process is `'get_cpus'`, so it can not work as expect

**Comment by tiny-x** [comment]
> ## Issue Description
> _bug report_
> 
> ### Describe what happened (or what feature you want)
> 1. start a stop process experiment:
> 
> ```
> $ ./blade create process stop --process get_cpus
> {"code":200,"success":true,"result":"8280640d9b9368eb"}
> ```
> 
> 1. try to destroy it
> 
> ```
> $ ./blade -d destroy 8280640d9b9368eb
> {"code":604,"success":false,"error":"'get_cpus' process not found exit status 1"}
> ```
> 
> ### Describe what you expected to happen
> the process been stopped can not be waken
> 
> ### How to reproduce it (as minimally and precisely as possible)
> as above
> 
> ### Tell us your environment
> Debian Linux
> 
> ### Anything else we need to know?
> while calling `./blade create process stop --process get_cpus`, the process is `get_cpus`, but when try to destroy it, the process is `'get_cpus'`, so it can not work as expect

Can you provide a blade version? Do you use a blade that you compiled yourself
