### ISSUE TITLE
Can you support the chaos experiment of memory?

### ISSUE THREAD

**Issue by Iris1120** [chaosblade-io/chaosblade#4]
Can you support the chaos experiment of memory, such as, out of memory  and memory leak ? Thank you for all you do.

**Comment by xcaspar** [comment]
Yes. We plan to add in the next version, the features for the JVM chaos experiments include jvm FullGC, OOM, memory leak and method parameter modification. Also welcome to submit pr.

**Comment by mingcheng** [comment]
I think i can implement it, just use stress's memory benchmark algorithm.

**Comment by xcaspar** [comment]
> I think i can implement it, just use stress's memory benchmark algorithm.

Thank you for this. Because of your profile setting, I cannot assign the issue to you, I will assign it to me, but you implement it, OK? @mingcheng

**Comment by xcaspar** [comment]
#162
