### ISSUE TITLE
"disk fill" filled a wrong mount point with MAX file size

### ISSUE THREAD

**Issue by akaroka** [chaosblade-io/chaosblade#40]
## Issue Description

Type: bug report 

### Describe what happened (or what feature you want)
blade create disk fill    
fill the wrong mount point with max size data.
[](url)
### Describe what you expected to happen
fill the right mount point with specified size data. 

### How to reproduce it (as minimally and precisely as possible)

1. Ubuntu 18.04  /   blade 0.0.1   
2. wiki  blade disk fill command.
3. 

### Tell us your environment
Ubuntu 18.04 
blade 0.0.1

### Anything else we need to know?

![avatar](https://i.loli.net/2019/04/14/5cb322f4a7f18.png)
![avatar](https://i.loli.net/2019/04/14/5cb322f4aff4a.png)
![avatar](https://i.loli.net/2019/04/14/5cb322f4b5814.png)

**Comment by akaroka** [comment]
when using the command " ./blade create disk fill  --mount-on / --size 1000",
the tool runs successfully BUT filling the /home, the same folder as the blade file, not the mount point / .
AND write data until the disk is full ( /home )  rather than write the specified size data.

**Comment by xcaspar** [comment]
@akaroka I have fixed it. #41 
You can compile the master branch or wait for the 0.0.2 version release

**Comment by akaroka** [comment]
> @akaroka Thank you for your report. I have fixed it. #41
> You can compile the master branch or wait for the 0.0.2 version release

Cool. 
Possible release date for 0.0.2 version?

**Comment by xcaspar** [comment]
> > @akaroka Thank you for your report. I have fixed it. #41
> > You can compile the master branch or wait for the 0.0.2 version release
> 
> Cool.
> Possible release date for 0.0.2 version?

Tuesday or Wednesday this week.

**Comment by akaroka** [comment]
> > > @akaroka Thank you for your report. I have fixed it. #41
> > > You can compile the master branch or wait for the 0.0.2 version release
> > 
> > 
> > Cool.
> > Possible release date for 0.0.2 version?
> 
> Tuesday or Wednesday this week.

Awesome.
