### ISSUE TITLE
Error when using prepare jvm with java_1.7_64 process

### ISSUE THREAD

**Issue by Harmattan322** [chaosblade-io/chaosblade#400]
## Issue Description

Type: *bug report*

### Describe what happened
0. defined java process from WAS (web application sphere):
<img width="562" alt="Снимок экрана 2020-09-10 в 12 21 13" src="https://user-images.githubusercontent.com/19413892/92712423-4cdb3380-f362-11ea-98a0-16c4872c153c.png">

1. 'bad major version' when using prepare jvm **without** -j $JAVA_HOME:
<img width="1021" alt="Снимок экрана 2020-09-10 в 12 26 21" src="https://user-images.githubusercontent.com/19413892/92711755-7b0c4380-f361-11ea-9773-e922819559ae.png">

2. 'sandbox load jvm failed' when using prepare jvm -j
<img width="553" alt="Снимок экрана 2020-09-10 в 12 23 49" src="https://user-images.githubusercontent.com/19413892/92711974-b444b380-f361-11ea-8ac4-cf7137622dd7.png">

### Describe what you expected to happen
{"code":200,"success":true,"result":"1239c66005a0aadd"}

### How to reproduce it (as minimally and precisely as possible)

1. get PID of  java_1.7_64 process (maybe from WAS);
2. execute 'blade prepare jvm --pid *pid*' or 'blade prepare jvm --pid *pid* -j *path_to_java_1.7_64*' or 'blade prepare jvm --pid *pid* -j *path_to_random_java*'.

### Tell us your environment
OS: RHEL 7
BLADE:
<img width="807" alt="Снимок экрана 2020-09-10 в 12 16 19" src="https://user-images.githubusercontent.com/19413892/92712286-1a313b00-f362-11ea-96f6-bf993963acad.png">

### Anything else we need to know?
With java **8.0** process from WAS 'blade prepare jvm --pid *pid*' works correctly!

**Comment by xcaspar** [comment]
@Harmattan322 Please append `--javaHome` flag to specify JAVA_HOME path.

**Comment by Harmattan322** [comment]
@xcaspar, but I have already tried this option (-j instead of --javaHome, it's alias), check "Describe what happened -> 2", please.
