### ISSUE TITLE
when I use "create network loss --percent 100 --interface eth0 --exclude-port 22,9526" the host can not connect anymore.

### ISSUE THREAD

**Issue by renguangyin** [chaosblade-io/chaosblade#402]
## Issue Description

Type: *bug report*

### How to reproduce it (as minimally and precisely as possible)

1. execute, create network loss --percent 100 --interface eth0 --exclude-port 22,9526
2. telnet ip 22 or request via rest api can not get response anymore
3.

**Comment by tiny-x** [comment]
Are you exec `telnet` command  on the injected machine,that doesn't make sense because the exit flow is restricted.
But multiple ports are a bug

**Comment by renguangyin** [comment]
@tiny-x this issue fixed on 0.7.0, this scenario works well now.
