### ISSUE TITLE
chaosblade-spec-go这个东东到底该怎么使用？没例子没文档

### ISSUE THREAD

**Issue by davidwudv** [chaosblade-io/chaosblade#405]
如题

**Comment by tiny-x** [comment]
定义 ChaosBlade 混沌实验模型的，可以参考[混沌实验模型](https://github.com/chaosblade-io/chaosblade/wiki/%E6%B7%B7%E6%B2%8C%E5%AE%9E%E9%AA%8C%E6%A8%A1%E5%9E%8B)

**Comment by tiny-x** [comment]
> 如题

定义 ChaosBlade 混沌实验模型的，可以参考混沌实验模型

**Comment by tiny-x** [comment]
> 如题

定义 ChaosBlade 混沌实验模型的，可以参考[混沌实验模型](https://github.com/chaosblade-io/chaosblade/wiki/%E6%B7%B7%E6%B2%8C%E5%AE%9E%E9%AA%8C%E6%A8%A1%E5%9E%8B)
