### ISSUE TITLE
jvm return scenario does not  take effect

### ISSUE THREAD

**Issue by theodorezz** [chaosblade-io/chaosblade#412]
## Issue Description

After return scenarios was injected in jvm, I vertified the return of API, it didn't take effect.

### Describe what happened (or what feature you want)
Nothing changed after return scenario injected.

### How to reproduce it (as minimally and precisely as possible)

1. get inside of k8s container

2. deploy chaosblade-jvm

3. exectue return scenario
`./blade c jvm return --value return-does-not-work --classname com.xxx.xxx --methodname getProductList --pid 1 --debug`

4.check out chaosblade.log
```
2020-09-28 06:45:37 INFO  command: create, request: {"headers":{},"params":{"debug":"true","classname":"com.xxx.xxx.xxx","action":"return","pid":"1","suid":"773f00e0fe7fba43","value":"return-does-not-work","methodname":"getProductList","target":"jvm"}}
2020-09-28 06:45:37 INFO  change log level to debug
```

5.verify the return of ProductList API
nothing changed after return scenario's injection

### Tell us your environment
k8s + docker + spring boot

### Anything else we need to know?
To the same class/method(getProductList), delay and throwException scenarios have token effect.

**Comment by tiny-x** [comment]
You should use
````
blade create k8s container-jvm return --value hello-chaosblade --classname com.example.controller.DubboController --methodname hello --names nginx-app --container-ids f1de335b4eeaf --kubeconfig config --namespace default
````

**Comment by theodorezz** [comment]
Succeed. Thank you.
