### ISSUE TITLE
README.md写错了

### ISSUE THREAD

**Issue by XGameCloud** [chaosblade-io/chaosblade#417]
README.md -> CLI Command -> server:
curl "http://xxxx:9526/chaosblade?Cmd=create%20cpu%20fullload"
应该改为
curl "http://xxxx:9526/chaosblade?cmd=create%20cpu%20fullload"
cmd是小写。

**Comment by xcaspar** [comment]
@XGameCloud Welcome to summit a PR to fix it. 😃
