### ISSUE TITLE
网络延迟注入最高支持多长时间？

### ISSUE THREAD

**Issue by XGameCloud** [chaosblade-io/chaosblade#418]
如题。我没有在文档中找到相关说明。

**Comment by theodorezz** [comment]
Once I forgot to destroy the network failure, after hours our dev told me one node in the special env was disconnected for a long time.Then we found out that tc failure injection was not destoryed for more than 24h.

**Comment by xcaspar** [comment]
Maybe 270 seconds.

**Comment by seshenli** [comment]
没测试过更高的，至少10分钟可以
