### ISSUE TITLE
网络丢包排除多个端口的22端口问题请教

### ISSUE THREAD

**Issue by jack-yang-Xia** [chaosblade-io/chaosblade#436]
我网络丢包100%，排除了22,18083两个端口，然后成功后，我可以正常访问服务器和18083端口，但是一段时间未操作，就断开服务器连接，然后一直连不上服务器，直到过期时间到了后，才能连接到服务器，在此期间是可以正常访问18083端口的。服务器有一定时间未操作断开连接的检测，但是在排除22端口后依然断开了22端口，是否服务器tc规则未清理干净导致的？

**Comment by tiny-x** [comment]
I've had this problem too

**Comment by xcaspar** [comment]
@jack-yang-Xia 造成此问题的原因可能是排除掉的端口重新建立连接，对端端口发生变化导致的，我们将在下个版本中通过另一种方式来解决此问题。

**Comment by xcaspar** [comment]
可以通过添加 `exclude-ip` 参数排除 IP 的方式解决。

Add `exclude-ip` parameter to solve the problem.

**Comment by XHao** [comment]
> 可以通过添加 `exclude-ip` 参数排除 IP 的方式解决。
> 
> Add `exclude-ip` parameter to solve the problem.

所以仅仅使用exclude-port是不行的？ @xcaspar
