### ISSUE TITLE
blade create docker -h Examples don't contain argument numcpu

### ISSUE THREAD

**Issue by qilangye** [chaosblade-io/chaosblade#44]
## Issue Description

bug report

### Describe what happened (or what feature you want)

 ./blade create docker -h  Examples don't contain argument numcpu
Examples:
# Create a docker container full cpu load experiment
chaosbd create docker cpu fullload --container 1c8986a4f899

### Tell us your environment
CentOS Linux release 7.2.1511 (Core)

**Comment by xcaspar** [comment]
It's a bug. Strong check on `--numcpu` flag, causing command execution error.
