### ISSUE TITLE
Repeated bytecode enhancement  (reTransform class com.alibaba.druid.pool.DruidDataSource failed )

### ISSUE THREAD

**Issue by xueshaoyi** [chaosblade-io/chaosblade#442]
bug report

### Describe what happened (or what feature you want)
The project uses skywalking, then fault injection
sandbox log :
![image](https://user-images.githubusercontent.com/20856046/99754332-26d0cd00-2b23-11eb-8525-ed812c6c38b6.png)

./blade c druid connectionpoolfull  is fail

skywalking version is : 6.5.0
druid versiong is : 1.1.21

**Comment by xcaspar** [comment]
@tiny-x What's the progress of the issue.

**Comment by tiny-x** [comment]
It was the user who modified skywalking.
