### ISSUE TITLE
"Illegal \"match\"\n exit status 1 exit status 1"

### ISSUE THREAD

**Issue by che1995** [chaosblade-io/chaosblade#443]
## Issue Description

Type: *bug report* 

when I inject nnetwork delay fault,dan set the parameter --exclude-ip,it will  return this info:
{"code":604,"success":false,"error":"Illegal \"match\"\n exit status 1 exit status 1"}

**Comment by che1995** [comment]
the version is v.0.9.0,and i use v.0.8.0 also can't use  -exclude-ip

**Comment by che1995** [comment]
and the mem load experiment,use the '--mode cache ' cant't work

**Comment by xcaspar** [comment]
@che1995  We will fix it as soon as possible in the next version!
