### ISSUE TITLE
Can I just use chaosblade to test linux server without kubernetes?

### ISSUE THREAD

**Issue by donngchao** [chaosblade-io/chaosblade#466]
## Issue Description

Type: *question*

### Describe what happened (or what feature you want)

I am right now testing a linux server, which installed some traditional software such as nginx.
But the environment I am testing now has no relationship with Kubernetes or any other PaaS infrastructure.
Can I use chaosblade to test this linux server?
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
Deploy chaosblade to linux machine, and execute blade command.
