### ISSUE TITLE
Error: Cannot find process

### ISSUE THREAD

**Issue by JamesZBL** [chaosblade-io/chaosblade#500]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)

Process not found

<img width="247" alt="image" src="https://user-images.githubusercontent.com/26003056/118746102-2757df80-b88a-11eb-8a95-fde967e4f718.png">

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/26003056/118746085-1d35e100-b88a-11eb-8c68-a3505e017b29.png">

### Describe what you expected to happen

Process is found

### How to reproduce it (as minimally and precisely as possible)

<img width="247" alt="image" src="https://user-images.githubusercontent.com/26003056/118746102-2757df80-b88a-11eb-8a95-fde967e4f718.png">

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/26003056/118746085-1d35e100-b88a-11eb-8c68-a3505e017b29.png">

### Tell us your environment

Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-05T03:00:29+08:00)
Java version: 1.8.0_221, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/jre
Default locale: en_TW, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"

### Anything else we need to know

Why process exists but cannot be found?

**Comment by xcaspar** [comment]
`--process` flag indicates process command line information, so you can use `XXXApplication` to replace the pid value.

**Comment by JamesZBL** [comment]
I replaced the pid number with XXXApplication, but it throws an error, in this screen shot
<img width="1696" alt="image" src="https://user-images.githubusercontent.com/26003056/118903272-0656c380-b94a-11eb-98b5-17e9a5517901.png">

**Comment by xcaspar** [comment]
You can execute the following commands:
```
./blade p jvm --pid PID
```
Wait for the command execution to complete. Then execute the next command without --process
```
./blade c jvm delay ... 
```
