### ISSUE TITLE
想问一下 针对k8s 针对某个pod 做网络丢包实验，如果忘记关闭实验,pod 重启之后 会有什么影响？

### ISSUE THREAD

**Issue by wuguanyu** [chaosblade-io/chaosblade#517]

**Comment by xcaspar** [comment]
没有影响，Pod重启后会自动恢复注入的网络故障。

---

No effect. The Pod network will be recovery after restart.

**Comment by maofengwang** [comment]
我之前测试丢包率如果超过90的话，timeout时间到了，演练也不会停止，pod开始无限重启，这是个bug

**Comment by wuguanyu** [comment]
> 没有影响，Pod重启后会自动恢复注入的网络故障。
> 
> No effect. The Pod network will be recovery after restart.

还有一个问题 就是 注入丢包100% 之后排除了内网的ip 但是健康检查 还是不过
