### ISSUE TITLE
Support stop system service 

### ISSUE THREAD

**Issue by carolwu-1206** [chaosblade-io/chaosblade#518]
## Issue Description
*feature request*
Type: *bug report* , *feature request* or *question*

### Describe what happened (or what feature you want)
There is process kill feature in Chaosblade. But when the process is managed by a system service, the "timeout" field will be useless. Once the process is killed, another one will be triggered by the service. We cannot simulate the scene that the system is down for a while.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
Thanks for your contributions.
