### ISSUE TITLE
Currently there is support for dubbo, will support springcloud later?

### ISSUE THREAD

**Issue by starmoon1994** [chaosblade-io/chaosblade#52]
目前有对dubbo支持，后续会对springcloud进行支持吗

**Comment by xcaspar** [comment]
> 目前有对dubbo支持，后续会对springcloud进行支持吗

@starmoon1994 这是个好问题， Spring Cloud 是构建分布式系统一站式解决方案，其中包含很多组件，我们需要分别对其组件做支持，所以首先我们需要梳理组件支持的优先级以及需要支持的场景。十分欢迎大家参与讨论，大家可以说说自己的想法。

**Comment by xcaspar** [comment]
#71
