### ISSUE TITLE
Does chaosblade support container-jvm?

### ISSUE THREAD

**Issue by vossss** [chaosblade-io/chaosblade#531]
./blade create k8s container-jvm delay --names chaosdemo-c987d574b-9nnfh --container-ids d6c2cddb537f --kubeconfig ~/.kube/config --namespace default --time 4000 --classname=com.example.controller.DubboController --methodname=sayHello --process business --debug
{"code":200,"success":true,"result":"e8219103bc8edd75"}

但是似乎是无效的，没有delay。

**Comment by xcaspar** [comment]
Support it. Please see details of the chaosblade log under `~/logs/chaosblade` in target container.

**Comment by ruihua-zhao1** [comment]
It seems I run into similar issue.

**Comment by vossss** [comment]
> Support it. Please see details of the chaosblade log under `~/logs/chaosblade` in target container.

root@master:~/chaos/chaosblade-1.2.0# ./blade create k8s container-jvm delay --names chaosdemo-c987d574b-9nnfh --container-ids 14b0f5ab33cc --kubeconfig ~/.kube/config --namespace default --time 4000 --classname=com.example.controller.DubboController --methodname=sayHello --process business --debug
{"code":200,"success":true,"result":"603d26551a2e909e"}
root@master:~/chaos/chaosblade-1.2.0# cd logs
root@master:~/chaos/chaosblade-1.2.0/logs# ls
chaosblade.log
root@master:~/chaos/chaosblade-1.2.0/logs# cat chaosblade.log
time="2021-07-21 10:44:26.797158887 CST" level=info msg="create uid: 603d26551a2e909e, target: jvm, scope: container, action: delay"
time="2021-07-21 10:44:26.804677663 CST" level=error msg="chaosblade result: []" location=github.com/chaosblade-io/chaosblade/exec/kubernetes.QueryStatus uid=603d26551a2e909e
time="2021-07-21 10:44:27.808025549 CST" level=error msg="chaosblade result: []" location=github.com/chaosblade-io/chaosblade/exec/kubernetes.QueryStatus uid=603d26551a2e909e

**Comment by vossss** [comment]
> Support it. Please see details of the chaosblade log under `~/logs/chaosblade` in target container.

it works

./blade create k8s container-jvm delay --names chaosdemo-c987d574b-wtvbv --container-ids 44e60004973c --kubeconfig ~/.kube/config --namespace default --time 4000 --classname=com.example.controller.DubboController --methodname=hello --process business
