### ISSUE TITLE
Can't delay my service pod with this tool?

### ISSUE THREAD

**Issue by ruihua-zhao1** [chaosblade-io/chaosblade#539]
## Issue Description

Type: *bug report* , *feature request* or *question*

### Describe what happened (or what feature you want)

I use minikube create cluster in my local then start some mini services in my local. After I applied the delay command, everything looks good for me. But when I open the docker container and check the service delay time. There is almost no delay. Do you have this kind of sample or documents? Thanks

**Comment by orangle** [comment]
yes

**Comment by ruihua-zhao1** [comment]
Why it can't delay?

**Comment by xcaspar** [comment]
Please provide your blade command or experiment yaml file.

**Comment by xcaspar** [comment]
Network experiment is effective for any pod.
