### ISSUE TITLE
The release version of the package is too large, 89M!

### ISSUE THREAD

**Issue by guohz-git** [chaosblade-io/chaosblade#55]
你好，请问一下能优化一下release版本包大小嘛， 测试版本是 0.0.2 ，截图如下：
![image](https://user-images.githubusercontent.com/12553259/56885279-ab21b200-6a9e-11e9-982d-31f884b58d81.png)

版本包体积太大不方便和其它agent整合，agent分发太耗时！

**Comment by xcaspar** [comment]
@guohz-git 压缩包大小是 56M，可以压缩后分发。
由于程序是使用 golang 编写，为了不依赖平台，所以会将依赖的库全部打进去。

**Comment by guohz-git** [comment]
目前采用 Upx压缩方案，可以进一步压缩安装包大小。
详情参考： https://studygolang.com/articles/10763

**Comment by guohz-git** [comment]
已解决

**Comment by xcaspar** [comment]
> 目前采用 Upx压缩方案，可以进一步压缩安装包大小。
> 详情参考： https://studygolang.com/articles/10763

谢谢提供解决方案。
