### ISSUE TITLE
Support mysql? According to usage create mysql, the  error is: cannot get port from local.Thanks!

### ISSUE THREAD

**Issue by yinqiang001** [chaosblade-io/chaosblade#56]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
@yinqiang001 Currently we are injecting faults on the mysql driver, so it only works for Java applications. Before executing the mysql experiment, please execute `prepare jvm --process <PROCESS NAME>` command first.
