### ISSUE TITLE
Any support plan for Cri-o?

### ISSUE THREAD

**Issue by shaobo76** [chaosblade-io/chaosblade#562]
## Issue Description

Type: feature request

### Describe what happened (or what feature you want)
On our openshift 4 cluster, when applying "loss-pod-network", there is an error saying "code: 63062 error: GetClient : docker exec failed, err: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
Is there any support plan for Cri-o container runtime?

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by MandssS** [comment]
yes, we will support Cri-o  in 1.4.0, please stay tuned for！
