### ISSUE TITLE
How do debug ChaosBlade in Goland

### ISSUE THREAD

**Issue by sanxun0325** [chaosblade-io/chaosblade#570]
## Issue Description

Type: *question*

### Describe what happened (or what feature you want)
How do debug ChaosBlade in Goland

### Describe what you expected to happen
Hopefully can debug ChaosBlade in Goland, learn about it, and contribute

### How to reproduce it (as minimally and precisely as possible)
I set the parameters like this，run it in debug mode, but the results are incorrect

![image](https://user-images.githubusercontent.com/28588342/130612004-a9092edf-6b61-4aa0-8d27-0f3272132f23.png)

![image](https://user-images.githubusercontent.com/28588342/130612406-26b58f25-9229-4de4-84b7-3d7e88e06224.png)

### Tell us your environment
mac os 11.5.2

**Comment by MandssS** [comment]
you can debug by goland. 

" the results are incorrect": you can show your printscreen
