### ISSUE TITLE
k8s cpu 满载实验创建失败了无法销毁 destroy the experiment failed, expected destroyed, but the real value is Running

### ISSUE THREAD

**Issue by NigelWu95** [chaosblade-io/chaosblade#604]
## Issue Description

Type: *bug report* , *feature request* or *question*

### Describe what happened (or what feature you want)

error：

"code":504,"success":false,"error":"forcibly remove e2c13c20b80d1faf resource success, but destroy the experiment failed, expected destroyed, but the real value is Running"

### Describe what you expected to happen
add --force-remove for destroy command is also not useful/working.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
Please provide the chaosblade-operator pod log.

**Comment by NigelWu95** [comment]
> Please provide the chaosblade-operator pod log.
![image](https://user-images.githubusercontent.com/20470818/142149865-6af05c4e-f756-47ee-9281-121d494ec0d5.png)

**Comment by NigelWu95** [comment]
> Please provide the chaosblade-operator pod log.

I destroy it again， then get result：

"code":504,"success":false,"error":"forcibly remove e2c13c20b80d1faf resource success, but destroy the experiment failed, expected destroyed, but the real value is Running"

**Comment by NigelWu95** [comment]
> Please provide the chaosblade-operator pod log.

Use command: "kubectl logs -f chaosblade-operator-xxx", no valid log infomation, like this:

![image](https://user-images.githubusercontent.com/20470818/142150728-3e160336-8566-4155-96ae-a53b1046db7f.png)

**Comment by xcaspar** [comment]
![image](https://user-images.githubusercontent.com/3992234/142157099-33700e2a-39b5-4ae8-b9cd-065c7ec62a20.png)
It can be seen from the log that the destroy operator was successful, but the experimental status update failed. Can you provide the result of the following command?: 
```
kubectl get blade e2c13c20b80d1faf
```

**Comment by NigelWu95** [comment]
> ![image](https://user-images.githubusercontent.com/3992234/142157099-33700e2a-39b5-4ae8-b9cd-065c7ec62a20.png) It can be seen from the log that the destroy operator was successful, but the experimental status update failed. Can you provide the result of the following command?:
> 
> ```
> kubectl get blade e2c13c20b80d1faf -o json
> ```

e2c13c20b80d1faf is not found, use dedd463227137d43 to get blade, result:

# kubectl --all-namespaces=true get blade dedd463227137d43 -o json
{
    "apiVersion": "chaosblade.io/v1alpha1",
    "kind": "ChaosBlade",
    "metadata": {
        "creationTimestamp": "2021-11-16T16:03:20Z",
        "deletionGracePeriodSeconds": 0,
        "deletionTimestamp": "2021-11-17T07:04:51Z",
        "finalizers": [
            "finalizer.chaosblade.io"
        ],
        "generation": 2,
        "name": "dedd463227137d43",
        "resourceVersion": "186964252",
        "selfLink": "/apis/chaosblade.io/v1alpha1/chaosblades/dedd463227137d43",
        "uid": "b84ec7e9-46f6-11ec-b4fa-0cc47a4e0b3a"
    },
    "spec": {
        "experiments": [
            {
                "action": "fullload",
                "desc": "created by blade command",
                "matchers": [
                    {
                        "name": "timeout",
                        "value": [
                            "1200"
                        ]
                    },
                    {
                        "name": "uid",
                        "value": [
                            ""
                        ]
                    },
                    {
                        "name": "evict-percent",
                        "value": [
                            ""
                        ]
                    },
                    {
                        "name": "labels",
                        "value": [
                            ""
                        ]
                    },
                    {
                        "name": "namespace",
                        "value": [
                            "antstack"
                        ]
                    },
                    {
                        "name": "chaosblade-deployed-path",
                        "value": [
                            ""
                        ]
                    },
                    {
                        "name": "cpu-percent",
                        "value": [
                            "100"
                        ]
                    },
                    {
                        "name": "evict-count",
                        "value": [
                            ""
                        ]
                    },
                    {
                        "name": "evict-group",
                        "value": [
                            ""
                        ]
                    },
                    {
                        "name": "names",
                        "value": [
                            "finsit-mq-msgbroker-3",
                            "finsit-mq-msgbroker-2",
                            "finsit-mq-msgbroker-4",
                            "finsit-mq-msgbroker-1"
                        ]
                    },
                    {
                        "name": "climb-time",
                        "value": [
                            ""
                        ]
                    },
                    {
                        "name": "cpu-list",
                        "value": [
                            ""
                        ]
                    },
                    {
                        "name": "cpu-count",
                        "value": [
                            ""
                        ]
                    }
                ],
                "scope": "pod",
                "target": "cpu"
            }
        ]
    },
    "status": {
        "expStatuses": [
            {
                "action": "fullload",
                "resStatuses": [
                    {
                        "id": "62cf91b5948a9530",
                        "identifier": "antstack/11.166.83.13/finsit-mq-msgbroker-3/finsit-mq-msgbroker-3/eef7d523ac81",
                        "kind": "pod",
                        "state": "Success",
                        "success": true
                    },
                    {
                        "id": "0e0b359a8620f7bb",
                        "identifier": "antstack/11.166.85.237/finsit-mq-msgbroker-2/finsit-mq-msgbroker-2/f39aea4d52f0",
                        "kind": "pod",
                        "state": "Success",
                        "success": true
                    },
                    {
                        "id": "d48f5a6d552fd1a6",
                        "identifier": "antstack/11.166.85.226/finsit-mq-msgbroker-4/finsit-mq-msgbroker-4/3a68f0c44d83",
                        "kind": "pod",
                        "state": "Success",
                        "success": true
                    },
                    {
                        "id": "82b7194be24597b4",
                        "identifier": "antstack/11.166.83.5/finsit-mq-msgbroker-1/finsit-mq-msgbroker-1/91f56c2a4bbf",
                        "kind": "pod",
                        "state": "Success",
                        "success": true
                    }
                ],
                "scope": "pod",
                "state": "Success",
                "success": true,
                "target": "cpu"
            }
        ],
        "phase": "Running"
    }
}

**Comment by xcaspar** [comment]
The above experiment is in running, will it fail when destroying? Which chaosblade version are you using?

**Comment by NigelWu95** [comment]
> The above experiment is in running, will it fail when destroying? Which chaosblade version are you using?

Sorry, maybe the version is too outdated, I will first update it to use latest chaosblade.
