### ISSUE TITLE
blade cli can't run on MacOS Montery Version 12.0.1 (21A559)

### ISSUE THREAD

**Issue by NigelWu95** [chaosblade-io/chaosblade#606]
## Issue Description

Type: *bug report* , *feature request* or *question*

### Describe what happened (or what feature you want)

straightly killed:

![image](https://user-images.githubusercontent.com/20470818/142640343-34e6dd32-05a9-4f31-b271-1d026e8d00ce.png)

![image](https://user-images.githubusercontent.com/20470818/142640153-2b239885-3b96-4b5c-b227-861219789e7a.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by NigelWu95** [comment]
I straightly run go build: GOOS="darwin" GOARCH="amd64" go build  -o blade ./cli
![image](https://user-images.githubusercontent.com/20470818/142643422-db8df1f2-4244-44d7-848f-0b20ff5fb9ec.png)

**Comment by xcaspar** [comment]
Because of the macos sercurity policy, you can solve the problem by local compilation.

**Comment by NigelWu95** [comment]
> Because of the macos sercurity policy, you can solve the problem by local compilation.

Thank you, but why build command in Makefile has no GOOS and GOARCH value set for MacOS build?

**Comment by NigelWu95** [comment]
> 

I found the problem to explain why blade can not run in MacOS Monterey, because of the upx compression, compiled blade can run normally before upx build, after that the exec binary damaged.
