### ISSUE TITLE
docker network scene experiment can straightly exec in target container instead of sidecar container?

### ISSUE THREAD

**Issue by NigelWu95** [chaosblade-io/chaosblade#607]
## Issue Description

Type: *bug report* , *feature request* or *question*

### Describe what happened (or what feature you want)
![image](https://user-images.githubusercontent.com/20470818/142799743-b51fee4d-f81e-4075-be4d-b6ab0a939c6b.png)
Ask, can network scene use another way instead of sidecar?

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
Yes, you can use `NewRunCmdInContainerExecutorByCP` to replace it, like CPU scenarios.

**Comment by NigelWu95** [comment]
> Yes, you can use `NewRunCmdInContainerExecutorByCP` to replace it, like CPU scenarios.

Yeah, thanks.
