### ISSUE TITLE
can't prepare jvm

### ISSUE THREAD

**Issue by fangchengjie** [chaosblade-io/chaosblade#612]
## Issue Description

Type: *bug report* , *feature request* or *question*

### Describe what happened (or what feature you want)
i try `blade prepare jvm --pid 12344`,but it doesn't work,and return `Unable to access jarfile /usr/local/bin/lib/sandbox/lib/sandbox-core.jar\n exit status 1`

### Describe what you expected to happen
return 200

### How to reproduce it (as minimally and precisely as possible)

1. /usr/local/bin/blade prepare jvm --pid 12344
2. 
3. 

### Tell us your environment
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (build 1.8.0_201-b09)
OpenJDK 64-Bit Server VM (build 25.201-b09, mixed mode)

kafka 3.1.0

**Comment by jfl929930** [comment]
你看一下你的包是否有问题，提示sandbox-core.jar文件的问题

**Comment by fangchengjie** [comment]
> 你看一下你的包是否有问题，提示sandbox-core.jar文件的问题

如果jvm进程运行在kafka用户下会有这个问题，请问有解决方案吗

**Comment by jfl929930** [comment]
blade需要在root用户下进行操作。
