### ISSUE TITLE
CPU负载在不同编译环境下表现不同

### ISSUE THREAD

**Issue by jerry-sc** [chaosblade-io/chaosblade#613]
## Issue Description

*question*

### Describe what happened (or what feature you want)

1. 分别通过make 和 make build_linux 得到的chaos_burncpu；
2. 然后分别执行：./chaos_burncpu -nohup -cpu-percent 80 （注入80%CPU）
3. 发现前者到达80%负载特别慢。

查看Dockerfile发现，两者差异在musl-gcc的使用上。

疑问：
1. musl-gcc使用的目的是？
2. 不同编译方式得到的编译产物是否应该保持一致？
3. 看代码，为什么废弃cgroup方式？

**Comment by jfl929930** [comment]
你好，请问你是如何通过不同的方式make的么？可以详细描述一下么？

**Comment by jfl929930** [comment]
请问你所说的两种编译方式分别是在什么平台编译的，并且分别编译的是什么版本。麻烦详细描述一下

**Comment by jerry-sc** [comment]
>

**Comment by jerry-sc** [comment]
是否是和golang版相关呢？发现dockerfile中的golang是1.13的，我升级为1.14表现就不同了

**Comment by jfl929930** [comment]
您是本地的golang版本变化了么？

**Comment by jerry-sc** [comment]
是的，看上去是go版本有关系，试了几个不同版本，只有在go1.14上，cpu负载有问题，每个核的负载也不均衡

**Comment by jfl929930** [comment]
那建议你先换个版本使用，我们这边会深入研究一下其中的原因

**Comment by jerry-sc** [comment]
好的，可以看下是否是go1.14引入的调度的变更引起的

我这边也一起看下。issue我先关了
