### ISSUE TITLE
只有按照新手教程没法运行么？

### ISSUE THREAD

**Issue by ShiwenSun** [chaosblade-io/chaosblade#622]
我查看了日志，没有任何报错信息

![image](https://user-images.githubusercontent.com/40228676/145034514-e72a2e10-7601-463d-b8c0-4cd7efa5f5c0.png)

**Comment by ShiwenSun** [comment]
{"code":405,"success":false,"error":"b-params illegal json","result":"0495975b0efd164e"} 返回这个

**Comment by MandssS** [comment]
查看chaosblade/chaosblade.log日志，是啥情况

**Comment by xcaspar** [comment]
@ShiwenSun v1.4.0 引入的一个bug导致的，你可以先使用 v1.3.0 版本，1.5.0 会修复这个问题。
