### ISSUE TITLE
Use chaosblade to exercise mysql failure with pod multi-container in k8s

### ISSUE THREAD

**Issue by LH533** [chaosblade-io/chaosblade#623]
## Currently I use the shared process method in k8s. In the same pod, two containers are deployed, one is the application container and the other is the chaosblade container. The basic images of these two containers are the same. I performed a mysql failure simulation on the application container in chaosblade, and the following failures occurred
当前我在k8s中使用了共享进程的方式，在同一个pod中，部署了两个容器，一个是应用容器，一个是chaosblade容器，这两个容器的基础镜像都是一致的

我在chaosblade对应用容器进行mysql的故障模拟，出现了下列故障
![image](https://user-images.githubusercontent.com/43714304/145143485-b7972698-f7aa-4ef6-a2e4-f484e129b294.png)
1. 此处两个都是在root用户下进行的操作
2. 两个容器里面的/tmp有一定的不同，不清楚是哪里的差距
### 环境
java环境：
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

k8s集群：1.17.13

**Comment by MandssS** [comment]
这是因为不同container之间存在 MNT名称空间隔离导致的，在应用容器中是拿不到blade容器中的sandbox的。

在pod的yaml中两个container都共享chaosblade目录和/tmp目录就行了
