### ISSUE TITLE
802 error，can't attach jvm client

### ISSUE THREAD

**Issue by fangchengjie** [chaosblade-io/chaosblade#624]
## Issue Description

Type: *bug report* , *feature request* or *question*

### Describe what happened (or what feature you want)

{"code":802,"success":false,"error":"response code is 404, result: \u003chtml\u003e\n\u003chead\u003e\n\u003cmeta http-equiv=\"Content-Type\" content=\"text/html;charset=ISO-8859-1\"/\u003e\n\u003ctitle\u003eError 404 Not Found\u003c/title\u003e\n\u003c/head\u003e\n\u003cbody\u003e\n\u003ch2\u003eHTTP ERROR: 404\u003c/h2\u003e\n\u003cp\u003eProblem accessing /sandbox/default/module/http/chaosblade/status. Reason:\n\u003cpre\u003e    Not Found\u003c/pre\u003e\u003c/p\u003e\n\u003chr /\u003e\u003ci\u003e\u003csmall\u003ePowered by Jetty://\u003c/small\u003e\u003c/i\u003e\n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n                                                \n\u003c/body\u003e\n\u003c/html\u003e\n","result":"3191667c33ef89a6"}
### Describe what you expected to happen

执行`blade p jvm --pid 5450`,但是会提示802错误
### How to reproduce it (as minimally and precisely as possible)

1. `blade p jvm --pid 5450`
2. 
3. 

### Tell us your environment
-

### Anything else we need to know?
-

**Comment by MandssS** [comment]
麻烦确定下，当前是否存在5450的进程

**Comment by fangchengjie** [comment]
> 麻烦确定下，当前是否存在5450的进程

进程是存在的，后面我使用sh sandbox.sh -S -p 5450重启之后恢复了

**Comment by fangchengjie** [comment]
-
