### ISSUE TITLE
Prepare jvm is invalid,empty Uid

### ISSUE THREAD

**Issue by dopeter** [chaosblade-io/chaosblade#629]
## Issue Description

"prepare jvm -n -p ${prj_name} " on java8 or java17 , result is empty , but status is success

### Describe what you expected to happen
![image](https://user-images.githubusercontent.com/9638883/145950171-c079d985-0801-4317-a371-080b1bf4c02a.png)
![image](https://user-images.githubusercontent.com/9638883/145950243-f9b15ca4-765d-4a03-a5b8-47d08859d963.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
java8
java17
centos7

**Comment by xcaspar** [comment]
Don't use `-n` flag, the flag is used internally by the tool, if you want to prepare asynchronously, please use `-a` flag.

**Comment by dopeter** [comment]
3ks , that's alright
