### ISSUE TITLE
Ambiguous parameter of CPU FULLLOAD in version 0.0.3

### ISSUE THREAD

**Issue by akaroka** [chaosblade-io/chaosblade#63]
## Issue Description

Type:  bug report

### Describe what happened (or what feature you want)
when create cpu fulload, setting cpu-count and cpu-list parameters at the same time, only the cpu-list parameter works and the system ignores the cpu-count parameter.
创建cpu fullload故障时，如果同时设定cpu-count和cpu-list参数，只有cpu-list参数生效，系统自动无视了cpu-count参数

### Describe what you expected to happen
Add extra parameter explanation or prohibit coexistence.
添加额外的参数解释，或禁止两个参数共存

### How to reproduce it (as minimally and precisely as possible)

1. follow the official instrutions
2. 
3. 

### Tell us your environment
Ubuntu 19.04

**Comment by xcaspar** [comment]
@akaroka Yes, as you said, when both `cpu-count` and `cpu-list` parameters exist, only `cpu-list` takes effect. There is no parameter verification here. Can you fix this problem?

**Comment by akaroka** [comment]
> @akaroka Yes, as you said, when both `cpu-count` and `cpu-list` parameters exist, only `cpu-list` takes effect. There is no parameter verification here. Can you fix this problem?

I‘ll try to do it
