### ISSUE TITLE
 Source Build failed on Apple M1

### ISSUE THREAD

**Issue by 15669072513** [chaosblade-io/chaosblade#634]
It looks like darwin/arm64 is not supported yet by chaosblade.
when I exec the following command :
` make build_darwin
`
it shows the following error :
`make -C target/cache/chaosblade-exec-cplus
rm -rf build-target/chaosblade-1.4.0
mkdir -p build-target/chaosblade-1.4.0/yaml build-target/chaosblade-1.4.0/lib/cplus/script
env CGO_ENABLED=1 GO111MODULE=on go build  -o build-target/chaosblade-1.4.0/lib/cplus/chaosblade-exec-cplus main.go
# github.com/shirou/gopsutil/cpu
/Users/liuhq/go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/cpu/cpu_darwin_cgo.go:13:5: warning: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]
# github.com/shirou/gopsutil/process
/Users/liuhq/go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/process/process_darwin.go:576:34: undefined: KinfoProc
/Users/liuhq/go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/process/process_darwin.go:577:8: undefined: KinfoProc
/Users/liuhq/go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/process/process_darwin.go:590:32: undefined: KinfoProc
/Users/liuhq/go/pkg/mod/github.com/shirou/gopsutil@v2.20.5+incompatible/process/process_darwin.go:594:62: undefined: KinfoProc
make[1]: *** [build_cplus] Error 2
make: *** [cplus] Error 2
`

**Comment by 15669072513** [comment]
close

**Comment by antstudio-git** [comment]
got the same error, is there any way to resolve?

**Comment by 15669072513** [comment]
no，apple m1  not support 。



---- Replied Message ----
| From | ***@***.***> |
| Date | 08/12/2022 20:52 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [chaosblade-io/chaosblade] Source Build failed on Apple M1 (Issue #634) |

got the same error, is there any way to resolve?

**Comment by antstudio-git** [comment]
got it , thanks
