### ISSUE TITLE
Cannot get the return value when executing the command

### ISSUE THREAD

**Issue by tangyuhan0816** [chaosblade-io/chaosblade#64]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
<img width="552" alt="WX20190505-141636@2x" src="https://user-images.githubusercontent.com/38600085/57189369-9f236d80-6f40-11e9-93f1-e475eb21fc6a.png">

<img width="582" alt="WX20190505-141848@2x" src="https://user-images.githubusercontent.com/38600085/57189380-c11cf000-6f40-11e9-91d7-2e2ca9c96345.png">

### Describe what you expected to happen

预期：希望允许Java代码能够获取返回值
实际：不能获取返回值

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by guohz-git** [comment]
可以采用双流并读方案读取，命令返回值！ 目前有些命令会返回到Error输出流里面！
`Process process = Runtime.getRuntime().exec("./blade status uid");
        InputStream inputStream = process.getInputStream();
        InputStream errorStream = process.getErrorStream();`

**Comment by guohz-git** [comment]
可以采用双流并读方案读取，命令返回值！ 目前有些命令会返回到Error输出流里面！
Process process = Runtime.getRuntime().exec("./blade status uid"); 
InputStream inputStream = process.getInputStream(); 
InputStream errorStream = process.getErrorStream();

**Comment by xcaspar** [comment]
@guohz-git I have change the output to stdout when return success in chaosblade 0.2.0 version.
