### ISSUE TITLE
The error "cannot create directory '/opt/chaosblade': Permission denied" happen when use chaos-operator

### ISSUE THREAD

**Issue by ycwdaaaa** [chaosblade-io/chaosblade#645]
as the title， I have many containers without root permission, even has no sh or bash shell.    I guess the operator is try to install chaos-blade cli in the container to complete the injection job.  but in fact, a lot of pods cannot do that. so is there any solution?

**Comment by MandssS** [comment]
You can choose a path with permissions: 

      --chaosblade-path string           Chaosblade tool deployment path, default value is /opt. Please select a path with write permission
