### ISSUE TITLE
CPU Load

### ISSUE THREAD

**Issue by JohnMatty** [chaosblade-io/chaosblade#654]
## Issue Description

Type: *question*

### Describe what happened (or what feature you want)
I have a similar question to this https://github.com/chaosblade-io/chaosblade-exec-os/issues/108
I would like to know the logic for CPU Load used in Linux. We would like to do some customization. Where is the logic present?

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by sanxun0325** [comment]
The execution logic is here:https://github.com/chaosblade-io/chaosblade-exec-os/tree/master/exec/bin/burncpu
