### ISSUE TITLE
执行./blade prepare jvm --process tomcat报错

### ISSUE THREAD

**Issue by lihao18** [chaosblade-io/chaosblade#66]
## Issue Description

Type: *bug report* or *feature request*
![image](https://user-images.githubusercontent.com/34645100/57228700-03305980-7047-11e9-9104-a4363c5894b5.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
Centos

java version "1.8.0_171"

**Comment by xcaspar** [comment]
@lihao18 能否提供一下进程信息，包括 pid、ppid、user、command line

**Comment by xcaspar** [comment]
@lihao18 I think that you can download the chaosblade latest version and use `--javaHome` argument when executing jvm preparation to solve the problem.
I will close the issue and you can reopen it if the problem isn't solved.
