### ISSUE TITLE
http/dubbo，使用b-params参数报illegal json，json应该是什么格式

### ISSUE THREAD

**Issue by lss9981** [chaosblade-io/chaosblade#662]
## Issue Description

![image](https://user-images.githubusercontent.com/42905828/154021817-67b6f274-2e91-4e60-a621-d3dac8c7d12f.png)

![image](https://user-images.githubusercontent.com/42905828/154021714-4191f2c3-0073-4bba-8e39-8c08f256b938.png)

![image](https://user-images.githubusercontent.com/42905828/154021659-ef62692a-8099-4030-b32f-b291a6d3ad94.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
Please see the [PR](https://github.com/chaosblade-io/chaosblade-exec-jvm/pull/207) for the details.
