### ISSUE TITLE
./blade create docker cpu fullload fail on the centos system

### ISSUE THREAD

**Issue by kounijiwa** [chaosblade-io/chaosblade#67]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

First:
Though I read issue #12, I still can't understand.
I haven't pull docker image registry.cn-hangzhou.aliyuncs.com/chaosblade/chaosblade-agent:0.0.3 or other version. When I run
./blade create docker cpu fullload --container 4c5c3a7706ec --numcpu 8 on the Ubuntu system ,it return {"code":200,"success":true,"result":"83484e440a710e46"} .
But when I run on the Centos system, it return ******no such container .

Second:
When create docker cpu fullload failed on the Centos System, I pull the images "registry.cn-hangzhou.aliyuncs.com/chaosblade/chaosblade-agent:0.0.3" , and run "docker run -d -t --pid container:4c5c3a7706ec --ipc container:4c5c3a7706ec --name 4c5c3a7706ec-cpu sh -c /usr/local/chaosblade/bin/chaos_burncpu --start " , it return "docker: --pid:invalid PID mode". Where is my mistake?
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
@kounijiwa Can you provide the centos version and docker version?

**Comment by kounijiwa** [comment]
centos 6.3
Docker version 1.6.0

**Comment by HiJasper** [comment]
`docker run -d -t --pid container:4c5c3a7706ec --ipc container:4c5c3a7706ec --name 4c5c3a7706ec-cpu sh -c /usr/local/chaosblade/bin/chaos_burncpu --start`
Did this command need declare the image like 
`docker run -d -t --pid container:4c5c3a7706ec --ipc container:4c5c3a7706ec --name 4c5c3a7706ec-cpu registry.cn-hangzhou.aliyuncs.com/chaosblade/chaosblade-agent:0.0.3 sh -c /usr/local/chaosblade/bin/chaos_burncpu --start`
Even add the image,the container still exited immediately.And the command "/blade create docker cpu fullload --container 4c5c3a7706ec" would't work ok

**Comment by xchnshi** [comment]
I also met this exactly issue, 
Centos: CentOS Linux release 7.4.1708 (Core) 
Docker Version:         1.13.1
chaosblade-agent:0.0.3

the container ID used is in running status:
CONTAINER ID        IMAGE               COMMAND                   CREATED             STATUS              PORTS                                            NAMES
343214d46ee8        halyard:stable      "/bin/sh -c \"/opt/..."   2 days ago          Up 2 days

**Comment by xcaspar** [comment]
@kounijiwa Please download the latest version(v0.4.0-alpha) to retry. 中文使用文档：https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/blade-create-docker
