### ISSUE TITLE
Support Restful API mode calls

### ISSUE THREAD

**Issue by xcaspar** [chaosblade-io/chaosblade#68]
## Issue Description

Type: *feature request*

### Describe what you expected to happen

Currently the blade tool only supports cli mode calls, we need to add a `server` command, start it as web mode, and expose the Restful service.

If you are interested in this topic, please refer to : #73

**Comment by rohanjulka19** [comment]
Hi , I want to work on this project , can you please elaborate what exactly is required. thank you

**Comment by xcaspar** [comment]
> Hi , I want to work on this project , can you please elaborate what exactly is required. thank you

Please submit the proposal according to the process mentioned in the issue(#73 ). If you have any questions about this issue, you can reply under the issue.

**Comment by sounak98** [comment]
@xcaspar I want to work on this, can you  please guide me?

**Comment by xcaspar** [comment]
@sounak98 I am very sorry for that the time for submission of the proposal has expired. Thank you for your interest in this project.
