### ISSUE TITLE
Optimize and extend existing network chaos experiments

### ISSUE THREAD

**Issue by xcaspar** [chaosblade-io/chaosblade#69]
## Issue Description

Type:  *feature request*

### Describe what you expected to happen

The current network experiment scenario includes delay, packet loss, and port blocking. and there are many other network experiment scenarios, such as packet corruption and packet duplication.
And now the bottom of the network experiment scenario is implemented by the `tc` and `iptables` tools, is there a better way to achieve it?

If you are interested in this topic, please refer to : #73

**Comment by jievince** [comment]
Hi mentor, I am interested in this idea, can you guide me how to start?

**Comment by jievince** [comment]
I have submitted a proposal to you about this idea.

**Comment by xcaspar** [comment]
> I have submitted a proposal to you about this idea.

Thank you for your interest in the SOC project. I will reply to you after reviewing.

**Comment by jievince** [comment]
Hi xcaspar, Is there any problem with my proposal?

**Comment by jievince** [comment]
@xcaspar

**Comment by xcaspar** [comment]
@jievince I will reply to you before tomorrow, sorry to let you wait so long.

**Comment by xcaspar** [comment]
@jievince I have replied to you by email.

**Comment by jievince** [comment]
@xcaspar I have replied to you.
