### ISSUE TITLE
怎么详细模拟docker-compose内指定两个容器间通信的丢包，包括发送时候丢，接收时候丢

### ISSUE THREAD

**Issue by vipcxj** [chaosblade-io/chaosblade#691]
比如用docker-compose建立了容器A，B，B向A的80端口发送请求，如何指定30%概率请求压根发不到A，30%概率请求发到A，但返回的包给丢了，剩下的情况成功。另外还能叠加延迟吗？

**Comment by MandssS** [comment]
可以使用 docker network loss 这个场景，具体参见：https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/blade-create-network-loss
