### ISSUE TITLE
Feature Request: network delay for windows

### ISSUE THREAD

**Issue by dianny123** [chaosblade-io/chaosblade#698]
## Issue Description

Type: *feature request* 

### Describe what happened (or what feature you want)

I'm looking for windows support using chaosblade. Do you have plan to support? 

### Describe what you expected to happen
inject network delay fault into windows.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
windows

**Comment by MandssS** [comment]
There are currently no plans. But our enterprise edition supports Windows。

[chaos](https://www.aliyun.com/product/aliware/ahas/chaos?spm=5176.21213303.8115314850.4.699f53c9ax4LBQ&scm=20140722.S_card@@%E4%BA%A7%E5%93%81@@596791._.ID_card@@%E4%BA%A7%E5%93%81@@596791-RL_ahas-OR_ser-V_2-P0_0)
