### ISSUE TITLE
Network command prompt to optimize

### ISSUE THREAD

**Issue by aspnetdb** [chaosblade-io/chaosblade#7]
## Issue Description

*feature request*

### Describe what happened (or what feature you want)
Network command prompt to optimize. After change the port command will be easier to understand. 
> invoke-port change to **foreign-port** 
> service-port change to **local-port** 

```
blade create network delay --invoke-port 9527 --time 5000 --device eth0

      --invoke-port string    Port for invoke
      --offset string         Delay offset time, ms
      --service-port string   Port for external service
```

**Comment by xcaspar** [comment]
Agree, `--local-port` and `--foreign-port` are more able to express the port to be drilled than `--invoke-port ` and `--service-port`. We will add this change to the next version.
