### ISSUE TITLE
Initialisation time with Download option

### ISSUE THREAD

**Issue by anvmga** [chaosblade-io/chaosblade#704]
## Issue Description

Type: *question*

### Tell us your environment
Chaosblade v1.5.0

Any particular reason for doing the DeployToPod in sequence rather than using goroutine?

**Comment by anvmga** [comment]
Currently kubectl exec is done to perform each tests like file exists or not and also while downloading its waiting for the response status from the target containers. With goroutine, download/copy the blade binaries would have been faster. Hence checking

**Comment by MandssS** [comment]
There's no particular reason, it's just designed that way.

If you have an idea, you can create PR
