### ISSUE TITLE
1.6.0 版本创建 cri 和 k8s 的网络实验时没有 delay 等类型

### ISSUE THREAD

**Issue by NigelWu95** [chaosblade-io/chaosblade#714]
## Issue Description

cli 只是一个客户端，k8s 场景下执行实验的目标容器不是 mac 的啊，为什么会因为本地是 mac 就不能对目标执行 network 的 delay、loss 实验。。。
![image](https://user-images.githubusercontent.com/20470818/168068147-c13846bc-1eda-480a-9a6c-187be8841c54.png)

Type: *bug report* , *feature request* or *question*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
Yes, you are right. In the next version, we will add these scenarios to the K8s experiments.

**Comment by MandssS** [comment]
please use v1.6.1. Resolved in version 1.6.1

-------
请使用1.6.1版本，在该版本中已解决该问题
