### ISSUE TITLE
chaosblade-exec-jvm 这个包单独使用怎么使用呢

### ISSUE THREAD

**Issue by TomQiu** [chaosblade-io/chaosblade#729]
你好，就是请教下，我这边有演练相关的计划，场景， 然后我只想单独使用 chaosblade-exec-jvm 这个下面的注入能力可以使用吗，我看文档上并没有写的很清楚。 就是单独使用这个包来完整对机器的注入

**Comment by MandssS** [comment]
如果只需要java相关演练场景，也需要chaosblade模块一起的
