### ISSUE TITLE
[BUG]使用HTTP Server模式url转义问题

### ISSUE THREAD

**Issue by cyrly97** [chaosblade-io/chaosblade#739]
chaosblade1.3.0
使用HTTP Server模式
使用此场景时
https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/blade-create-jvm/blade-create-jvm-script
base64编码后java代码带有+或=时，因为请求参数必须编码后变成%2B或%3D，此时chaosblade无法正常解析
如base64编码后为
aW1wb3J0IHh4LnJlc3BvbnNlLkNvbnRyb2xsZXJSZXNwb25zZTsKaW1wb3J0IHh4LnJlc3BvbnNlLlJlc3BvbnNlQ29kZTsKCmltcG9ydCBqYXZhLnV0aWwuTWFwOwoKLyoqCiAqIEBBdXRob3I6IGN5cgogKiBARGF0ZTogMjAyMi82LzIwIDEzOjI0CiAqLwpwdWJsaWMgY2xhc3MgVGVzdENvbnRyb2xsZXIgewoKICAgIHB1YmxpYyBPYmplY3QgcnVuKE1hcDxTdHJpbmcsIE9iamVjdD4gbWFwKXsKICAgICAgICBtYXAucHV0KCJpZCIsIDc3Nyk7CiAgICAgICAgcmV0dXJuIG5ldyBDb250cm9sbGVyUmVzcG9uc2UoUmVzcG9uc2VDb2RlLlNVQ0NFU1MsOTk5KTsKICAgIH0KfQo=

源代码：
import xx.response.ControllerResponse;
import xx.response.ResponseCode;

import java.util.Map;

/**
 * @Author: cyr
 * @Date: 2022/6/20 13:24
 */
public class TestController {

    public Object run(Map<String, Object> map){
        map.put("id", 777);
        return new ControllerResponse(ResponseCode.SUCCESS,999);
    }
}
![image](https://user-images.githubusercontent.com/43930599/174573170-12e60d8f-4f23-47ef-bd56-a399db8ef4a6.png)

**Comment by Icesource** [comment]
@cyrly97  你好，我尝试后发现无法复现该问题，script-content在UrlEncode编码后可以在chaosblade中得到正确的解码
例如：
```
blade c jvm script --classname com.example.demo.controller.HelloController --methodname hello --script-content aW1wb3J0IGphdmEudXRpbC5NYXA7CgovKioKICogQGF1dGhvciBDaGFuZ2p1biBYaWFvCiAqLwpwdWJsaWMgY2xhc3MgRXhjZXB0aW9uU2NyaXB0IHsKICAgIHB1YmxpYyBPYmplY3QgcnVuKE1hcDxTdHJpbmcsIE9iamVjdD4gcGFyYW1zKSAgewogICAgICAgIHJldHVybiAiY2hhb3MgaGVsbG8iOwogICAgfQp9Cg==  --script-name exception
```
该命令使用http模式，进行urlencode后得到如下指令，该指令可以正确被解析并注入到JVM中
```
curl "http://localhost:9526/chaosblade?cmd=create%20jvm%20script%20--classname%20com.example.demo.controller.HelloController%20--methodname%20hello%20--script-content%20aW1wb3J0IGphdmEudXRpbC5NYXA7CgovKioKICogQGF1dGhvciBDaGFuZ2p1biBYaWFvCiAqLwpwdWJsaWMgY2xhc3MgRXhjZXB0aW9uU2NyaXB0IHsKICAgIHB1YmxpYyBPYmplY3QgcnVuKE1hcDxTdHJpbmcsIE9iamVjdD4gcGFyYW1zKSAgewogICAgICAgIHJldHVybiAiY2hhb3MgaGVsbG8iOwogICAgfQp9Cg%3D%3D%20%20--script-name%20exception"
```
在我的Case中，Hello World返回值成功被修改为了chaos hello

**Comment by Icesource** [comment]
或许你可以尝试升级chaosblade来解决这个问题

**Comment by Icesource** [comment]
或许你可以尝试升级chaosblade来解决这个问题

**Comment by antstudio-git** [comment]
@cyrly97 你的问题解决了吗，我也遇到这个问题了
