### ISSUE TITLE
编译过程中需要下载的yaml失败

### ISSUE THREAD

**Issue by livecm** [chaosblade-io/chaosblade#746]
--2022-06-28 00:39:42--  https://chaosblade.oss-cn-hangzhou.aliyuncs.com/agent/github/1.6.0/chaosblade-check-spec-1.6.0.yaml
正在解析主机 chaosblade.oss-cn-hangzhou.aliyuncs.com (chaosblade.oss-cn-hangzhou.aliyuncs.com)... 47.110.177.9
正在连接 chaosblade.oss-cn-hangzhou.aliyuncs.com (chaosblade.oss-cn-hangzhou.aliyuncs.com)|47.110.177.9|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 403 Forbidden
2022-06-28 00:39:43 错误 403：Forbidden。

**Comment by Icesource** [comment]
@livecm 您可以使用1.6.1版本的check yaml来编译，1.6.0版本存在部分问题，可以在MakeFile中将check-yaml的连接改为如下1.6.1版本的url
```
https://chaosblade.oss-cn-hangzhou.aliyuncs.com/agent/github/1.6.1/chaosblade-check-spec-1.6.1.yaml
```
