### ISSUE TITLE
1.6.1 mem load question

### ISSUE THREAD

**Issue by binbin0325** [chaosblade-io/chaosblade#752]
## Issue Description

Type: *bug report* , *feature request* or *question*

### Describe what happened (or what feature you want)
In version 1.6.1, memory load not work
1: Memory usage is not rising
2:cannot get the chaos_os program

1.6.1版本下 内存加载好像不生效，如果注入的时间持续的长一点（例如几分钟）。销毁时会出现找不到chaos_os的错误

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/28588342/177089872-8fdc5ba7-c94b-4758-bc42-eef1d2f9c472.png">

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by tiny-x** [comment]
机器的总内存多少，如果本身内存比较小的话，指定 90% 可能是占用太多被操作系统杀掉了；

**Comment by xcaspar** [comment]
执行 destroy 命令报错这个是需要优化的。我们还需要排查是否是被系统 oomkiller 杀掉。请提供linux 系统版本和内核版本。

**Comment by sanxun0325** [comment]
> 执行 destroy 命令报错这个是需要优化的。我们还需要排查是否是被系统 oomkiller 杀掉。请提供linux 系统版本和内核版本。

和tiny-x沟通过，在1.6.1版本中不支持在容器内直接故障注入，可能是因为这个原因导致到。后面在1.6.2版本中可以兼容回来

**Comment by tiny-x** [comment]
1.7.0 已经支持
