### ISSUE TITLE
1.6.1 bug: blade disk burn experiment failed when using ssh channel

### ISSUE THREAD

**Issue by pipsqueakup** [chaosblade-io/chaosblade#755]
I run disk burn experiment with chaos blade 1.6.1 , but failed with panic, command looks like 
`-d create disk burn --read --write --timeout 1800 --channel ssh --ssh-host xxx --ssh-user root --ssh-password xx`

the related panic error is 
`panic: interface conversion: interface {} is string, not int goroutine 1 [running]: github.com/chaosblade-io/chaosblade/cli/cmd.(*CreateCommand).actionRunEFunc.func1(0xc000158dc0, {0x52f7d48, 0x1e, 0x1e}) /Users/zhangli/Documents/code/golang/chaosblade/chaosblade/cli/cmd/create.go:210 +0x15c6 github.com/spf13/cobra.(*Command).execute(0xc000158dc0, {0xc00000c3c0, 0x1e, 0x1e}) /Users/zhangli/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x60e github.com/spf13/cobra.(*Command).ExecuteC(0xc00052e000) /Users/zhangli/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad github.com/spf13/cobra.(*Command).Execute(...) /Users/zhangli/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887 main.main() /Users/zhangli/Documents/code/golang/chaosblade/chaosblade/cli/main.go:28 +0x25`

After debugging, I found the Result field of  response is string, not int, which causes the panic
![chaosblade_error](https://user-images.githubusercontent.com/9692093/178186173-cb0d6ea4-6ada-4a17-a3b7-6945d213f406.png)

**Comment by tiny-x** [comment]
#763
