### ISSUE TITLE
chaosblade1.6.1 exec k8s pod cpu test error

### ISSUE THREAD

**Issue by zhouxt** [chaosblade-io/chaosblade#759]
## Issue Description

Type: *bug report* , *feature request* or *question*

### Describe what happened (or what feature you want)
This error was reported during k8s container CPU testing using chaosblade1.6.1

![企业微信截图_16578573306122](https://user-images.githubusercontent.com/24519090/179148113-65b534d5-b75f-4d72-85a6-bd0cdad20b35.png)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by MandssS** [comment]
Please check: the operator version of your k8s cluster is 1.6.1 ?

**Comment by zhouxt** [comment]
> Please check: the operator version of your k8s cluster is 1.6.1 ?

thanks ,my operator version of  k8s cluster is latest, not 1.6.1

**Comment by MandssS** [comment]
please, be consistent
