### ISSUE TITLE
Improve the project quality

### ISSUE THREAD

**Issue by xcaspar** [chaosblade-io/chaosblade#76]
## Issue Description

Type:  *feature request*

### Describe what you expected to happen

At present, the quality of software is controlled by incomplete unit testing and manual testing.
You can do things that you think can improve the quality of the project, including code, specifications, workflows, etc., such as completing unit tests, adding automated test tools, and more.

If you are interested in this topic, please refer to : #73

**Comment by xiaoerlaigeid** [comment]
I am interested in this project. what should  I do?

**Comment by xcaspar** [comment]
> I am interested in this project. what should I do?

Thanks for your interest in the SoC project. Please check this issue(#73 ) for details and specific participation process. If you have questions about this issue, please reply under it.

**Comment by Kaushl2208** [comment]
@xcaspar Hey, I am interested in solving this issue as my Soc2019 project. Can you guide me through where to start off? Or is there any platform you guys use to have discussions like gitter?

**Comment by xcaspar** [comment]
> @xcaspar Hey, I am interested in solving this issue as my Soc2019 project. Can you guide me through where to start off? Or is there any platform you guys use to have discussions like gitter?

Please select at least three issues from the [soc](https://github.com/chaosblade-io/chaosblade/labels/SoC2019) ideas and submit the corresponding proposal, proposal submission address: https://developer.aliyun.com/summerofcode2019
If you have other questions, you can send me a mail directly.

**Comment by sjha2048** [comment]
@xcaspar I have submitted the proposal for Ali SOC , can you please review it once?

**Comment by xcaspar** [comment]
I have received it and will announce the results next week.

Sahil Jha <notifications@github.com> 于2019年6月18日周二 下午10:02写道：

**Comment by xcaspar** [comment]
> @xcaspar I have submitted the proposal for Ali SOC , can you please review it once?

I have received it and will announce the results next week.

**Comment by sjha2048** [comment]
Thanks.
