### ISSUE TITLE
[ChaosBlade官网文档完善] 优化完善ChaosBlade官网命令文档（混沌工程实验类型）

### ISSUE THREAD

**Issue by Icesource** [chaosblade-io/chaosblade#766]
大家好，

该 Issue 为 [官网完善Issue](https://github.com/chaosblade-io/chaosblade/issues/758) 的补充Issue，用于详细介绍如何贡献 ChaosBlade [官网命令文档](https://chaosblade.io/docs/experiment-types/host/blade%20create%20cpu%20load)（混沌工程实验类型），您参与的贡献会被记录在[chaosblade-website](https://github.com/chaosblade-io/chaosblade-website)，只要您参与贡献，就可以成为 ChaosBlade 社区的 Contributor，并可根据后续贡献程度成为社区 Member

官网现有的命令（混沌工程实验类型）条目如下：
- 物理主机
  - 模拟CPU负载实验
  - 模拟内存占用实验
  - 模拟磁盘IO负载实验
  - 模拟磁盘填充实验
  - 模拟网络延迟实验
  - 模拟篡改DNS解析实验
  - 模拟网络屏蔽实验
  - 模拟网络丢包实验
  - 模拟网络包损坏实验
  - 模拟网络包重排序实验
  - 模拟网络包重复实验
  - 模拟网络本地端口占用实验
  - 模拟杀进程实验
  - 模拟暂停进程实验
- kubernetes
  - 模拟Kubernetes相关实验场景
  - 模拟节点CPU负载实验场景
  - 模拟节点网络相关场景
  - 模拟节点进程相关场景
  - 模拟节点磁盘场景
  - 模拟Pod资源自身场景
  - 模拟Pod文件系统I/O异常
  - 模拟Pod网络相关场景
  - 模拟容器内CPU负载实验场景
  - 模拟容器内网络实验场景
  - 模拟容器内进程场景
  - 模拟容器资源自身场景
- jvm
  - 挂载Java Agent
  - 模拟指定类方法调用延迟
  - 模拟指定类方法返回值
  - 模拟指定Java进程CPU满载
  - 模拟内存溢出场景
  - 模拟CodeCache填充
  - 模拟指定类方法抛指定异常
  - 模拟Java web请求延迟
  - 模拟Java web请求异常

以上条目来自[官网命令文档页面](https://chaosblade.io/docs/experiment-types/host/blade%20create%20cpu%20load/)，这些文档是由[gitbook](https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/)迁移过来的，存在文档内容不全、缺漏、超链接错误等情况，需要您对其进行完善或简单的勘误。 

贡献步骤：
1. fork 并 clone [chaosblade-website](https://github.com/chaosblade-io/chaosblade-website)官网项目
2. 在该 Issue 下回复你想要贡献的范围或具体哪些文档，以免有人和你的工作重复了
3. 在项目中找到文档对应的目录路径，中文文档目录 `/chaosblade-website/i18n/zh/docusaurus-plugin-content-docs/current/experiment-types/host/blade_create_disk_fill.md`，英文文档目录`/chaosblade-website/docs/experiment-types/host/blade_create_disk_fill.md`，目前首要的工作为完善中文文档，若能在中文文档完善之余，翻译为英文则更好
4. 根据文档原文或[gitbook](https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/)中对应的原文，参考后文中的**提要模板**完善优化文档，过程中若搭建ChaosBlade环境并真实执行命令辅助完善文档更好，该部分可参考现有[完善文档PR Commit](https://github.com/chaosblade-io/chaosblade-website/pull/54/commits/981e81576a46b3f08244921766d870e29bef37b9)，该Commit中可以看到对原文档的改动
5. 修改完成后，提交并push到fork仓库，并在仓库发起pull request，请在pr描述中附带该Issue链接，标识pr附属该Issue
6. PR校验通过后会生成预览页面，在PR校验中的Deploy Preview可以查看预览页面

> 注：上述条目仅包含 Gitbook 中的系统资源和 Kubernetes 资源实验场景，Gitbook 中的其他场景（例如Jvm）也需要迁移到官网并进行完善，若您对这部分感兴趣，也可在该Issue下回复并进行迁移和完善工作。

参考PR：https://github.com/chaosblade-io/chaosblade-website/pull/54/commits/981e81576a46b3f08244921766d870e29bef37b9
相关页面：https://chaosblade.io/docs/experiment-types/host/blade%20create%20cpu%20load
                  https://chaosblade.io/docs/experiment-types/k8s/blade%20create%20k8s%20container-cpu

***
**完善提要模板**
1. 文档标题
2. 文档抬头（对文档的整体性概括介绍）
3. 场景介绍： 这是什么场景、有什么作用、会达到什么效果
4. 参数解析
5. 示例（主机模式下仅需通过cli命令行的使用示例，k8s下需要加上crd yaml使用示例）
6. 使用限制
7. 注意事项
  a. 是否需要特殊环境（例如网络部分需要tc命令）
  b. 特殊条件下可能造成的影响（例如杀进程不可恢复）

**注：上述模板的部分条目非必须，可根据命令的实际情况补充或减少对应条目**

***
1. 物理主机
  - [x] - 模拟CPU负载实验
  - [x] - 模拟内存占用实验
  - [x] - 模拟磁盘IO负载实验
  - [x] - 模拟磁盘填充实验
  - [x] - 模拟网络延迟实验
  - [x] - 模拟篡改DNS解析实验
  - [x] - 模拟网络屏蔽实验
  - [x] - 模拟网络丢包实验
  - [x] - 模拟网络包损坏实验
  - [x] - 模拟网络包重排序实验
  - [x] - 模拟网络包重复实验
  - [x] - 模拟网络本地端口占用实验
  - [x] - 模拟杀进程实验
  - [x] - 模拟暂停进程实验

2. kubernetes
  - [x] - 模拟Kubernetes相关实验场景
  - [x] - 模拟节点CPU负载实验场景
  - [x] - 模拟节点网络相关场景
  - [x] - 模拟节点进程相关场景
  - [x] - 模拟节点磁盘场景
  - [x] - 模拟Pod资源自身场景
  - [x] - 模拟Pod文件系统I/O异常
  - [x] - 模拟Pod网络相关场景
  - [x] - 模拟容器内CPU负载实验场景
  - [x] - 模拟容器内网络实验场景
  - [x] - 模拟容器内进程场景
  - [x] - 模拟容器资源自身场景

3. Jvm
  - [ ] - 挂载Java Agent
  - [ ] - 模拟指定类方法调用延迟
  - [ ] - 模拟指定类方法返回值
  - [ ] - 模拟指定Java进程CPU满载
  - [ ] - 模拟内存溢出场景
  - [ ] - 模拟CodeCache填充
  - [ ] - 模拟指定类方法抛指定异常
  - [ ] - 模拟Java web请求延迟
  - [ ] - 模拟Java web请求异常

**Comment by tiny-x** [comment]
模拟磁盘IO负载实验
模拟磁盘填充实验
模拟网络延迟实验
模拟篡改DNS解析实验

**Comment by Icesource** [comment]
接下来我会完善这些文档
- 模拟网络屏蔽实验
- 模拟网络丢包实验
- 模拟网络包损坏实验
- 模拟网络包重排序实验
- 模拟网络包重复实验
- 模拟网络本地端口占用实验
