### ISSUE TITLE
Unsupported major.minor version 52.0\n exit status 255 on release 0.0.3

### ISSUE THREAD

**Issue by smileyLuckychen** [chaosblade-io/chaosblade#77]
### Issue Description

Type: *bug report* or *feature request*
using command    " ./blade prepare jvm --process xxxxx"  but return false
key infomation is " sandbox load jvm failed : com/sun/tools/attach/VirtualMachine : Unsupported major.minor version 52.0\n exit status 255"

### Tell us your environment
Centos
java version:  1.8.0_171
chaosblade version:  chaosblade-0.0.3

**Comment by xcaspar** [comment]
Can you execute the `sh lib/sandbox/bin/sandbox.sh -p PID` command in the chaosblade directory and provide the return message?

`PID` is your java application process id.

**Comment by smileyLuckychen** [comment]
> Can you execute the `sh lib/sandbox/bin/sandbox.sh -p PID` command in the chaosblade directory and provide the return message?
> 
> `PID` is your java application process id.

NAMESPACE : default
                      VERSION : 1.2.0
                         MODE : ATTACH
                  SERVER_ADDR : 0.0.0.0
                  SERVER_PORT : 43679
               UNSAFE_SUPPORT : ENABLE
                 SANDBOX_HOME : /home/work/chaosblade/chaosblade-0.0.2/lib/sandbox/bin/..
            SYSTEM_MODULE_LIB : /home/work/chaosblade/chaosblade-0.0.2/lib/sandbox/bin/../module
              USER_MODULE_LIB : ~/.sandbox-module;
          SYSTEM_PROVIDER_LIB : /home/work/chaosblade/chaosblade-0.0.2/lib/sandbox/bin/../provider
           EVENT_POOL_SUPPORT : DISABLE

**Comment by smileyLuckychen** [comment]
/xxxx/xxx/java -version  ：  "1.8.0_171"   
java home：/home/work/emcjdk8/runtime
java -version: 1.6.0_24

**Comment by xcaspar** [comment]
@smileyLuckychen Please compile the latest master branch, I have fixed it.

**Comment by smileyLuckychen** [comment]
thank you so munch.
