### ISSUE TITLE
httpclient4 注入异常是否支持uri的正则匹配

### ISSUE THREAD

**Issue by angjuLin** [chaosblade-io/chaosblade#771]
目标是想要在httpclient4的客户端注入异常，但是uri这里的后两个path是动态的，所以想用 -regex-pattern来表示是正则匹配
./blade create http throwCustomException  --exception java.lang.Exception --exception-message this-is-a-mocked-exception --httpclient4 --uri-regex-pattern http://localhost:9002/server/test/[\s\S]*/[\s\S]* --pid 14581

异常提示
unknown flag: --uri--regex-pattern

想问一下httpclient4这一类客户端是否支持uri的正则匹配，

然后这个blade命令执行的参数校验是在哪个工程的，如果不支持我想自己改一下，

**Comment by Icesource** [comment]
@angjuLin 目前 httpclient4 不支持 uri 正则匹配，可以添加参数通过uri-regex-pattern进行正则匹配

chaosblade-exec-jvm执行`make build`编译后会生成`chaosblade-jvm-spec-1.6.1.yaml`，将该文件拷贝到chaosblade的yaml
目录中即可修改参数校验，因此只需要修改chaosblade-exec-jvm，使其支持`uri-regex-pattern`，编译后拷贝yaml文件即可

**Comment by Icesource** [comment]
如果您考虑为chaosblade增加该功能，可以在编码之后提交pr，在pr中附上该issue的链接即可

**Comment by angjuLin** [comment]
@Icesource 这个有没有一个开发流程的文档或者说明，就是我要支持一些新的中间 以及已经支持的中间件添加新的一些特性，但是blade命令 是有一些校验的，我看了2天 那个chaosbalde 这个工程的go代码 才发现是又个chaosblade-jvm-spec-1.6.1.yaml 这个文件，对于我想要开发一些东西来说，这块的文档我似乎没哪里能找到

**Comment by Icesource** [comment]
@angjuLin  目前还没有一个针对开发者的开发说明文档，现有的可以参考的文档大致有
https://github.com/chaosblade-io/chaosblade-exec-jvm/blob/master/doc/zh-cn/plugin.md  chaosblade-exec-jvm 插件开发文档
https://chaosblade.io/docs/community/PR-guide  官网PR提交相关的文档
https://www.bilibili.com/video/BV1b741127iw?spm_id_from=333.337.search-card.all.click  B站上关于如何调试chaosblade-exec-jvm的视频教程

chaosblade相关的开发文档较少，文档的缺失确实是目前社区的一个问题，如果您感兴趣，文档方面也欢迎参与贡献
