### ISSUE TITLE
关于blade create k8s的文档是最新的吗，pod的cpu负载和关于内存的负载是不是都不支持kubectl 执行yaml 文件进行实验

### ISSUE THREAD

**Issue by CodeHcy** [chaosblade-io/chaosblade#779]
## Issue Description

Type: question

**Comment by MandssS** [comment]
你好，如果你是通过blade命令 --help获取的注释，那么是最新的，但如果是通过官网看到的文档就不是最新的

所有的k8s场景都支持yaml文件进行实验的
