### ISSUE TITLE
how to debug in goland

### ISSUE THREAD

**Issue by jack-tang1** [chaosblade-io/chaosblade#785]
## Issue Description

Type: *question*

### Describe what happened (or what feature you want)
i want to use debug mode in goland, and i execute like this 
![image](https://user-images.githubusercontent.com/100842809/189008874-add8813c-e447-41f1-bc01-1c06ec8fc001.png)
And recieve incorrect response ,detail is 
![image](https://user-images.githubusercontent.com/100842809/189009147-d4fc0734-723c-4e43-a628-fbcf14c76e2f.png)

### Describe what you expected to happen
 i hope it can like use binary file, can debug what happened in my machine, learn it, and contribute

### How to reproduce it (as minimally and precisely as possible)

1. download the master branch code, and use debug mode

### Tell us your environment
MacOS 11.2.1

**Comment by shaobo76** [comment]
The reason is the program need to read the spec yaml file. You can try build the project first, and then output the program in the target folder, together with the blade.

**Comment by MandssS** [comment]
I will demonstrate how to debug at the weekly meeting

**Comment by MandssS** [comment]
please watch: [debug vedio](https://www.bilibili.com/video/BV1ce4y1b7qL/?spm_id_from=333.999.0.0&vd_source=2b974868bbab01c5ab36c1a66321c659)
