### ISSUE TITLE
please   make  an vedio to introduce of   how to debug in golang  and  every module of Architecture design of the whole project

### ISSUE THREAD

**Issue by Yuaninga** [chaosblade-io/chaosblade#787]
## Issue Description

Type: *bug report* , *feature request* or *question*

### Describe what you expected to happen

i hope   you   make  an vedio to introduce of   how to debug in golang  and  Architecture design of the whole project，Convenient for secondary development  and more pr.

### Tell us your environment

mac

**Comment by MandssS** [comment]
I will demonstrate how to debug at the weekly meeting

**Comment by MandssS** [comment]
please watch: [debug vedio](https://www.bilibili.com/video/BV1ce4y1b7qL/?spm_id_from=333.999.0.0&vd_source=2b974868bbab01c5ab36c1a66321c659)
