### ISSUE TITLE
./blade create jvm throwCustomException/delay and other commands, the class name method name is required

### ISSUE THREAD

**Issue by johngerwong** [chaosblade-io/chaosblade#80]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
./blade create jvm throwCustomException/delay等命令，需要类名方法名是必须的

**Comment by johngerwong** [comment]
现状help提示非必须，执行时不指定也不报错。

**Comment by xcaspar** [comment]
issue: [chaosblade-exec-jvm issue-33](https://github.com/chaosblade-io/chaosblade-exec-jvm/issues/33)
