### ISSUE TITLE
ChaosBlade may incompatible with IBM JDK in some scenarios

### ISSUE THREAD

**Issue by kevinandjanies** [chaosblade-io/chaosblade#81]
## Issue Description

Type: *bug report*

I use ChaosBlade to inject some Faults with the IBM JDK environment, but I found there is  something wrong with ChaosBlade. 
e.g.  I use "blade c disk burn --read --write" command to burn IO.  After a few minutes,I found the IO is return to normal. than I use "ps -ef | grep choas"or "ps -ef | grep blade" command ,but can not find the chaosblade process.
Another case is when i use ChaosBlade to inject mysql fault with the command "blade p jvm xxxx" and "blade c mysql throwCustomException --database xxxx --exception java.lang.Exception --host xxx.xxx.xxx.xxx --port 3306". ChaosBlade returns success but my program can continue query the database.

How to solve above problem:
After I change the IBM JDK to ORACLE JDK(jdk1.8.0_211)，the above program was perfectly solved. so i think ChaosBlade may incompatible with IBM JDK in some scenarios.

My environment:

OS:  SUSE12 SP3 
JDK: ibm-java-x86_64-80
go: 1.12.1

**Comment by xcaspar** [comment]
I will close the issue first, you can reopen it if you have any problems.
