### ISSUE TITLE
Apply to become a Reviewer

### ISSUE THREAD

**Issue by Yuaninga** [chaosblade-io/chaosblade#816]
### Apply to become a Reviewer

**PR**:
- https://github.com/chaosblade-io/chaosblade-operator/pull/191
- https://github.com/chaosblade-io/chaosblade-operator/pull/192
- https://github.com/chaosblade-io/chaosblade-operator/pull/194
- https://github.com/chaosblade-io/chaosblade-website/pull/90
- https://github.com/chaosblade-io/chaosblade-website/pull/91
- https://github.com/chaosblade-io/chaosblade-operator/pull/196
- https://github.com/chaosblade-io/chaosblade-website/pull/96
- https://github.com/chaosblade-io/chaosblade-website/pull/98
- https://github.com/chaosblade-io/chaosblade-website/pull/100
- https://github.com/chaosblade-io/chaosblade-website/pull/102
- https://github.com/chaosblade-io/chaosblade-exec-os/pull/147

**ISSUE**：

- https://github.com/chaosblade-io/chaosblade/issues/777
- https://github.com/chaosblade-io/chaosblade/issues/802
- https://github.com/chaosblade-io/chaosblade/issues/804
- https://github.com/chaosblade-io/chaosblade/issues/812
- https://github.com/chaosblade-io/chaosblade/issues/815
- https://github.com/chaosblade-io/chaosblade-operator/issues/172
- https://github.com/chaosblade-io/chaosblade-operator/issues/180
- https://github.com/chaosblade-io/chaosblade-operator/issues/181
- https://github.com/chaosblade-io/chaosblade-operator/issues/183
- https://github.com/chaosblade-io/chaosblade-operator/issues/186
- https://github.com/chaosblade-io/chaosblade-operator/issues/189
- https://github.com/chaosblade-io/chaosblade-operator/issues/190
- https://github.com/chaosblade-io/chaosblade-box/issues/139

**Comment by MandssS** [comment]
You can create pr in https://github.com/chaosblade-io/community, like proposals:
https://github.com/chaosblade-io/community/blob/main/proposals/promotion_maintainer_MandssS.md
