### ISSUE TITLE
"disk burn" task destory strategy problem

### ISSUE THREAD

**Issue by tungwoo** [chaosblade-io/chaosblade#82]
## Issue Description

Type:  bug report

###  reproduce steps
1. blade create disk burn --read     (taskid:  aaaaaa)
2. blade create disk burn --write    (taskid: bbbbbb)
3. blade d aaaaa

### Tell us your environment
ubuntu 18.04

**Comment by xcaspar** [comment]
@tungwoo Thank you for reporting the issue, we will fix it in the next version.
