### ISSUE TITLE
[feature] Support Redis scene fault

### ISSUE THREAD

**Issue by Icesource** [chaosblade-io/chaosblade#825]
各位好，社区计划在未来为 ChaosBlade 引入 Redis 场景作为新的故障注入原子能力，现计划 Redis 场景如下：
1.  Redis 缓存过期
2.  Redis 缓存限流
3.  支持 Redis 缓存穿透、
欢迎各位开发者参与该项目，参与者将根据贡献程度获取社区的相应激励

Hello everyone, the community plans to introduce Redis scenarios for ChaosBlade as a new fault injection atomic capability in the future. The current planned Redis scenarios are as follows:
1. Redis cache expires
2. Redis cache throttling
3. Support Redis cache penetration
All developers are welcome to participate in the project, and participants will receive corresponding incentives from the community according to their contribution

**Comment by caofujiang** [comment]
Redis缓存过期实验，修改key值的有效期。借助go-redis包expire实现。
Redis缓存限制实验：修改redis的maxmemory配置，设置缓存内存使用限制，借助go-redis包ConfigSet实现。

**Comment by myl1019** [comment]
问一下， redis缓存过期是真实的过期吗？ 这种方式由恢复手段吗

**Comment by myl1019** [comment]
> go


问一下， redis缓存过期是真实的过期吗？ 这种方式由恢复手段吗

**Comment by myl1019** [comment]
> 

问一下， redis缓存过期是真实的过期吗？ 这种方式由恢复手段吗

**Comment by MandssS** [comment]
https://github.com/chaosblade-io/chaosblade-exec-middleware/pull/5
