### ISSUE TITLE
virtual meachine use mem load 100%, failed to destroy, err ：destory experiment failed, cannot get the chaos_os program

### ISSUE THREAD

**Issue by dianny123** [chaosblade-io/chaosblade#867]
## Issue Description

Type: *question*

### Describe what happened (or what feature you want)
we are use mem load fault to inject in virtual meachine, command  ./blade create mem load --mem-percent 100 --timeout 1800.
the fault inject successfully, but the chaos process is killed by system oom, then chaosblade print the err destory experiment failed, cannot get the chaos_os program when try to destroy chaos.

### Describe what you expected to happen
the err is unexpected.
实验现象都正常，但是不希望在销毁时报错。

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
Linux version 3.10.0-693.21.1.el7.x86_64
chaosblade 1.7.0

**Comment by MandssS** [comment]
There is a parameter to avoid being killed, you can see it with -h, just set this value to true

**Comment by MandssS** [comment]
avoid-being-killed
