### ISSUE TITLE
pod-file chmod失败

### ISSUE THREAD

**Issue by Lttstbj** [chaosblade-io/chaosblade#892]
chaosblade-operator日志:
time="2023-05-17T07:25:19Z" level=info msg="Exec command in pod" command="[/opt/chaosblade/blade create cri file chmod  --filepath=/data/conf/ltt.sh --mark=777 --container-id 878b1257e19e --container-runtime docker]" container=chaosblade-tool podName=chaosblade-tool-9clgf podNamespace=chaosblade
time="2023-05-17T07:25:19Z" level=info msg="get err message" command="[/opt/chaosblade/blade create cri file chmod  --filepath=/data/conf/ltt.sh --mark=777 --container-id 878b1257e19e --container-runtime docker]" container=chaosblade-tool err="{\"code\":63063,\"success\":false,\"error\":\"command exec failed, exit status 2\"}" out= podName=chaosblade-tool-9clgf podNamespace=chaosblade
chaosblade-tool容器日志:
time="2023-05-17 07:41:09.978193552 UTC" level=info msg="mode: create, target: file, action: chmod, flags map[channel:nsexec debug: filepath:/data/conf/ltt.sh mark:777 ns_mnt:true ns_net:false ns_pid:true ns_target:17919 uid:ba02af8c5d84a89b]" location="/go/src/github.com/chaosblade-io/chaosblade/target/cache/chaosblade-exec-os/main.go:123" uid=ba02af8c5d84a89b

麻烦大神解答一下

**Comment by hengyoush** [comment]
same as https://github.com/chaosblade-io/chaosblade/issues/884

**Comment by Lttstbj** [comment]
改问题还存在

**Comment by tiny-x** [comment]
> 该问题还存在
1.7.3 修复了

**Comment by Lttstbj** [comment]
要放在下个版本1.7.2了吗

**Comment by tiny-x** [comment]
> 要放在下个版本1.7.3了吗

输错了，是 1.7.2 已经修复了

**Comment by Lttstbj** [comment]
我执行了一下
还是提示这个错：
time="2023-05-19T01:41:50Z" level=info msg="Exec command in pod" command="[/opt/chaosblade/blade create cri file chmod  --filepath=/data/conf/ltt.sh --mark=777 --container-id 6d418466ab20 --container-runtime docker]" container=chaosblade-tool podName=chaosblade-tool-6m4n4 podNamespace=chaosblade
time="2023-05-19T01:41:50Z" level=info msg="get err message" command="[/opt/chaosblade/blade create cri file chmod  --filepath=/data/conf/ltt.sh --mark=777 --container-id 6d418466ab20 --container-runtime docker]" container=chaosblade-tool err="{\"code\":63063,\"success\":false,\"error\":\"command exec failed, exit status 2\"}" out= podName=chaosblade-tool-6m4n4 podNamespace=chaosblade
time="2023-05-19T01:41:50Z" level=error msg="`pods/exec`: k8s exec failed, err: {\"code\":63063,\"success\":false,\"error\":\"command exec failed, exit status 2\"}\n" location=github.com/chaosblade-io/chaosblade-operator/exec/model.execCommands.func1 uid=

**Comment by tiny-x** [comment]
> 我执行了一下 还是提示这个错： time="2023-05-19T01:41:50Z" level=info msg="Exec command in pod" command="[/opt/chaosblade/blade create cri file chmod --filepath=/data/conf/ltt.sh --mark=777 --container-id 6d418466ab20 --container-runtime docker]" container=chaosblade-tool podName=chaosblade-tool-6m4n4 podNamespace=chaosblade time="2023-05-19T01:41:50Z" level=info msg="get err message" command="[/opt/chaosblade/blade create cri file chmod --filepath=/data/conf/ltt.sh --mark=777 --container-id 6d418466ab20 --container-runtime docker]" container=chaosblade-tool err="{"code":63063,"success":false,"error":"command exec failed, exit status 2"}" out= podName=chaosblade-tool-6m4n4 podNamespace=chaosblade time="2023-05-19T01:41:50Z" level=error msg="`pods/exec`: k8s exec failed, err: {"code":63063,"success":false,"error":"command exec failed, exit status 2"}\n" location=github.com/chaosblade-io/chaosblade-operator/exec/model.execCommands.func1 uid=

我试过没有问题的，你要么没升级、要么升级有问题
