### ISSUE TITLE
后续会有对windows场景故障的支持吗

### ISSUE THREAD

**Issue by myl1019** [chaosblade-io/chaosblade#894]
## Issue Description

Type:  *feature request* 

### Describe what happened (or what feature you want)
请问 会有对windows机器支持故障注入的计划吗

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by binbin0325** [comment]
暂时没有计划，不过欢迎社区提交PR共建

**Comment by MandssS** [comment]
最新的1.7.5版本的规划里，会增加对Windows场景的支持

**Comment by MandssS** [comment]
#1059
