### ISSUE TITLE
k8s v1.12.3 pod delete with Chaosblade operator occurs：server could not find the requested resource

### ISSUE THREAD

**Issue by E-GTiD** [chaosblade-io/chaosblade#897]
Type: question

### Describe what happened (or what feature you want)
K8s version: v1.12.3
Chaosblade version: 1.7.1

During the pod delete experiment, it is found that the pod expected to be deleted has not been deleted, and the following error is reported by viewing the daily operator log:

time="2023-05-24T11:22:58Z" level=error msg="update chaosblade phase to Initialized failed" Request.Name=fail-pod-by-labels error="the server could not find the requested resource (put chaosblades.chaosblade.io fail-pod-by-labels)"

Is it because the version of Chaosblade does not match the version of K8S? 
What are the solutions besides the chaosblade version?

### How to reproduce it (as minimally and precisely as possible)
blade create k8s pod-pod delete --labels app=middle --namespace demok8sj --evict-count 1

### Tell us your environment
K8s version: v1.12.3
Chaosblade version: 1.7.1

**Comment by binbin0325** [comment]
Kubernetes 服务器版本必须不低于版本 v1.16 参考：https://chaosblade.io/docs/getting-started/installation-and-deployment/environment-prepare

**Comment by E-GTiD** [comment]
使用 chaosblade 1.2.0 版本中的 crd.yaml 重新挂载 crd 资源，可以解决该问题。似乎是由于 k8s 低版本不吃 versions 这个配置。
