### ISSUE TITLE
CPU benchmark timeout support

### ISSUE THREAD

**Issue by mingcheng** [chaosblade-io/chaosblade#9]
## Issue Description

Remote host may not response while benchmarking CPU by full loads. So need add param to auto stop benchmark.

Maybe this param name can be named `timeout`, just as same as `stress`. 

```
`stress' imposes certain types of compute stress on your system

Usage: stress [OPTION [ARG]] ...
...
 -t, --timeout N    timeout after N seconds
...

```

from `stress --help` command, in blade we can use with the same param name:

```
blade create cpu fullload --timeout 5 
```

**Comment by xcaspar** [comment]
Thank you for your contribution. Welcome to develop the project together. :smile:
