### ISSUE TITLE
How to Inject Memory Leak in JVM container

### ISSUE THREAD

**Issue by ramgiteng** [chaosblade-io/chaosblade#900]
## Issue Description

Question: How can we inject a Memory Leak in a JVM running inside a docker container?

### Describe what happened (or what feature you want)
Unable to find a method to trigger a Memory Leak
on a running JVM inside Docker

### Describe what you expected to happen
To cause a Memory leak in a JVM running inside a docker container

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
Docker and Java

**Comment by MandssS** [comment]
you can try `./blade c cri jvm -h` . Find out if there is what you need

**Comment by ramgiteng** [comment]
Thank you, I noticed that the tool comes with an option to inject OOM.
