### ISSUE TITLE
chaosblade operator match containerId

### ISSUE THREAD

**Issue by binbin0325** [chaosblade-io/chaosblade#902]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)

https://github.com/chaosblade-io/chaosblade-operator/blob/master/exec/container/controller.go#L164

当用户输入的containerId是完整的， 这里从pod查询到的container先截取了前12个字符 得到短id，然后让这个短的id前缀匹配用户输入的完整的（长的）,导致匹配失败。

If the specified containerId is the full size, the container obtained from pod intercepts the first 12 characters to get the short id. Then, the short id prefix matches the full size (long) entered by the user, causing the matching failure.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by hengyoush** [comment]
can you assgn it to me，i can fix it
