### ISSUE TITLE
chaosblade默认支持containerd容器运行时吗

### ISSUE THREAD

**Issue by openstack-test** [chaosblade-io/chaosblade#904]
**版本信息**

- chaosblade-tool: 1.7.0
- chaosblade-operator: 1.7.0
- chaosblade-box: 1.0.3

请问，以上版本的chaosblade默认支持containerd容器运行时吗? 亦或是需要做哪些配置调整才支持？谢谢

**Comment by MandssS** [comment]
默认就支持的，不需要做什么特殊配制
