### ISSUE TITLE
v1.7.2  make build_linux_arm   error

### ISSUE THREAD

**Issue by caofujiang** [chaosblade-io/chaosblade#906]
## Issue Description

<img width="803" alt="image" src="https://github.com/chaosblade-io/chaosblade/assets/22960846/0a1d837b-5532-46f2-ad64-55f60b43a678">

### Describe what you expected to happen

make build_linux_arm   ,I hope it will be done;

### How to reproduce it (as minimally and precisely as possible)

I think ,if we solve this error ,we must make go version   from now 1.13 to 1.17 al least

### Tell us your environment
MacBook Pro   13.2.1

**Comment by MandssS** [comment]
you can try by 1.7.4
