### ISSUE TITLE
can not open https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/

### ISSUE THREAD

**Issue by zhangyaocheng** [chaosblade-io/chaosblade#914]
## Issue Description

Type: *question*

### Describe what happened (or what feature you want)

can not open  https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/. Is this doc continue useful?

**Comment by binbin0325** [comment]
You can access it after using a vpn

**Comment by MandssS** [comment]
You can see : https://chaosblade.io/
