### ISSUE TITLE
Apply to become a Maintainer

### ISSUE THREAD

**Issue by Yuaninga** [chaosblade-io/chaosblade#919]
### PR(25)

- https://github.com/chaosblade-io/chaosblade-operator/pull/191
- https://github.com/chaosblade-io/chaosblade-operator/pull/192
- https://github.com/chaosblade-io/chaosblade-operator/pull/194
- https://github.com/chaosblade-io/chaosblade-website/pull/90
- https://github.com/chaosblade-io/chaosblade-website/pull/91
- https://github.com/chaosblade-io/chaosblade-operator/pull/196
- https://github.com/chaosblade-io/chaosblade-website/pull/96
- https://github.com/chaosblade-io/chaosblade-website/pull/98
- https://github.com/chaosblade-io/chaosblade-website/pull/100
- https://github.com/chaosblade-io/chaosblade-website/pull/102
- https://github.com/chaosblade-io/chaosblade-exec-os/pull/147
- https://github.com/chaosblade-io/chaosblade-box-agent/pull/8
- https://github.com/chaosblade-io/chaosblade-exec-os/pull/148
- https://github.com/chaosblade-io/chaosblade-exec-middleware/pull/5
- https://github.com/chaosblade-io/chaosblade-exec-os/pull/152
- https://github.com/chaosblade-io/chaosblade-website/pull/149
- https://github.com/chaosblade-io/chaosblade-exec-os/pull/161
- https://github.com/chaosblade-io/chaosblade-operator/pull/214
- https://github.com/chaosblade-io/chaosblade-exec-cri/pull/14
- https://github.com/chaosblade-io/chaosblade/pull/917
- https://github.com/chaosblade-io/chaosblade-exec-middleware/pull/8
- https://github.com/chaosblade-io/chaosblade-spec-go/pull/51
- https://github.com/chaosblade-io/chaosblade-exec-cloud/pull/8
- https://github.com/chaosblade-io/chaosblade-exec-cplus/pull/13
- https://github.com/chaosblade-io/chaosblade-website/pull/152

### ISSUE(20)

- https://github.com/chaosblade-io/chaosblade/issues/777
- https://github.com/chaosblade-io/chaosblade/issues/802
- https://github.com/chaosblade-io/chaosblade/issues/804
- https://github.com/chaosblade-io/chaosblade/issues/812
- https://github.com/chaosblade-io/chaosblade/issues/815
- https://github.com/chaosblade-io/chaosblade/issues/817
- https://github.com/chaosblade-io/chaosblade/issues/824
- https://github.com/chaosblade-io/chaosblade/issues/859
- https://github.com/chaosblade-io/chaosblade/issues/862
- https://github.com/chaosblade-io/chaosblade/issues/895
- https://github.com/chaosblade-io/chaosblade/issues/906
- https://github.com/chaosblade-io/chaosblade-operator/issues/172
- https://github.com/chaosblade-io/chaosblade-operator/issues/180
- https://github.com/chaosblade-io/chaosblade-operator/issues/181
- https://github.com/chaosblade-io/chaosblade-operator/issues/183
- https://github.com/chaosblade-io/chaosblade-operator/issues/186
- https://github.com/chaosblade-io/chaosblade-operator/issues/189
- https://github.com/chaosblade-io/chaosblade-operator/issues/190
- https://github.com/chaosblade-io/chaosblade-operator/issues/200
- https://github.com/chaosblade-io/chaosblade-box/issues/139

**Comment by MandssS** [comment]
https://github.com/chaosblade-io/community/pull/12
