### ISSUE TITLE
current user is root, not equals xxx

### ISSUE THREAD

**Issue by zz-GuoYF** [chaosblade-io/chaosblade#924]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)

I have a elasticsearch service, i want to make it cpu full load,
run command : sudo ./blade prepare jvm --process Elasticsearch
but  chaosblade.log show: 
![image](https://github.com/chaosblade-io/chaosblade/assets/65477849/0c760f2f-6f33-4f3f-8a8b-367af6f2b4a6)

### Describe what you expected to happen

I want to know how to run command

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
blade version: 1.7.2
Euler OS
java version: openJDK 1.8.0_242

**Comment by MandssS** [comment]
This is a normal log, which is printed because the user who started the java process is different from the user who is currently executing the chaos expriment.
