### ISSUE TITLE
运行 chaosblade-demo时 连接拒绝

### ISSUE THREAD

**Issue by lh-199827** [chaosblade-io/chaosblade#950]
## Issue Description

Type: *bug report* , *feature request* or *question*

### Describe what happened (or what feature you want)
在执行chaosblade-demo时, 在容器运行之后，使用curl [http://localhost:8080/dubbo/hello?name=dubbo命令](http://localhost:8080/dubbo/hello?name=dubbo%E5%91%BD%E4%BB%A4)
会显示Failed to connect to localhost port 8080: Connection refused
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by MandssS** [comment]
you should exec `curl http://localhost:8080/dubbo/hello\?name\=dubbo` in the docker container

https://camo.githubusercontent.com/f2b3094b20bdb227eb286073cbea154c094a0d199a58208f195c01d55f4d0776/68747470733a2f2f6368616f73626c6164652e6f73732d636e2d68616e677a686f752e616c6979756e63732e636f6d2f6167656e742f72656c656173652f6368616f73626c6164652d64656d6f2d302e302e312e676966
