### ISSUE TITLE
DNS Action Destroy Failed

### ISSUE THREAD

**Issue by zhenming98** [chaosblade-io/chaosblade#962]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
CRI DNS action uses `/opt/chaosblade/blade destroy cri network dns` to destroy prompt `grep`: command not found`

### Describe what you expected to happen
can destroy experiments

### How to reproduce it (as minimally and precisely as possible)
Filter containers by labels when cri network target is destroyed
![image](https://github.com/chaosblade-io/chaosblade/assets/57651846/c0169d74-73b4-453e-b571-81d4d6ceaa77)

This is to solve the problem that the name of the pod changes after it is restarted. 
It needs to search for the pause container through the label to restore it.

However, before the dns action is destroyed, it will be judged whether commands such as grep exist. Because grep does not exist in the pause container, the destruction fails.

### Tell us your environment
chaosblade 1.7.3

**Comment by binbin0325** [comment]
If dns stops faulty, you need to use grep. If no, install it
