### ISSUE TITLE
"jvm return value" command do not support space or other invalid url char in value string

### ISSUE THREAD

**Issue by dreamquster** [chaosblade-io/chaosblade#97]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
![image](https://user-images.githubusercontent.com/4962716/59547628-5d8cd600-8f74-11e9-97ff-7c3581a4b2a4.png)

### Describe what you expected to happen
Successful executed.

### How to reproduce it (as minimally and precisely as possible)

1.  docker run demo image
2. ./blade p jvm -p business
3. ./bldae c jvm return --classname com.example.service.DemoService \
    --methodname sayHello --value "hello world"

### Tell us your environment
mac

**Comment by xcaspar** [comment]
@dreamquster The cause for this problem is that the "hello world" parameter contains a space, remove it and try again.

**Comment by xcaspar** [comment]
#98 
@dreamquster Thank you for reporting and fixing the bug.
