### ISSUE TITLE
chaosblade-ex-ec-os tc fun portSetToPortRanges miscalculation

### ISSUE THREAD

**Issue by zhenming98** [chaosblade-io/chaosblade#983]
Type: bug report

Describe what happened (or what feature you want)

An error occurred while calculating the port range
Input "22,19527" Expected return [[22 22] [19527 19527]] Actual return [[22 22]]
Input "22,30-35" Expected return [[22 22] [30 35]] Actual return [[22 22] [31 35]]

![image](https://github.com/chaosblade-io/chaosblade/assets/57651846/75187197-2774-47e8-a7f2-0716b9e38a4d)

Tell us your environment
chaosblade 1.7.3

**Comment by spencercjh** [comment]
这是一个非常严重，明显且低级的 bug，请重视！！！

**Comment by spencercjh** [comment]
![image](https://github.com/chaosblade-io/chaosblade/assets/29922079/8380fb84-a2d8-4422-a444-ad71f0ea2326)
![image](https://github.com/chaosblade-io/chaosblade/assets/29922079/dbb88abe-3286-4be3-b545-85867004a0c5)
