### ISSUE TITLE
Execute ./blade prepare jvm --process error

### ISSUE THREAD

**Issue by SakuraGaara** [chaosblade-io/chaosblade#99]
![image](https://user-images.githubusercontent.com/25793981/59562719-b5096f80-9062-11e9-99c0-1b2d1c0a2e45.png)

提示找不到JAVA_HOME

**Comment by xcaspar** [comment]
@SakuraGaara 
blade 是通过 golang os.GetEnv 函数来获取 JAVA_HOME 值的，通过错误来看是读取不到你的本地变量。你可以先执行 `export JAVA_HOME=/usr/local/java/jdk1.8.0_111` ，然后再执行 blade 命令来解决。
我们下个版本会去掉对 JAVA_HOME 变量的强依赖。
----------
The blade uses the golang `os.GetEnv` function to get the `JAVA_HOME` value. By mistake, it can't read your local variable. You can do this by executing `export JAVA_HOME=/usr/local/java/jdk1.8.0_111` 
 command and then executing the blade command.
Our next version will remove the strong dependency on the JAVA_HOME variable.
