### ISSUE TITLE
How to use chaosblade for java jvm under k8s environment?

### ISSUE THREAD

**Issue by takkaman** [chaosblade-io/chaosblade#992]
## Issue Description

How to use chaosblade for java jvm under k8s environment?

### Describe what happened (or what feature you want)

I saw guideline for jvm, for k8s seperately. But I didn't see guideline to mock exception for java vm running inside k8s pod

**Comment by MandssS** [comment]
Mock chaos for jvm under k8s environment is similar like chaos for java jvm under host environment. 

you can use like `./blade c k8s container-jvm delay xxx`, but you need add field: `--names podName --container-names containerName --namespace k8sNamespace ...` 

You can use `-h` to view the field definition
